== Demencias

=== Notas clínicas

==== Evaluación

Se evalúa: comprensión, juicio, pensamiento abstracto, razonamiento,
capacidad de aprendizaje, alteraciones sensoriales y de la atención.
Hallazgos posibles: apraxia, agnosia, afasia (funciones cognoscitivas
instrumentales), reducción del flujo de ideas y deterioro en el proceso
de almacenar información con alteraciones en la atención.

* Memoria: alteración precoz y predominante con dificultad para aprender
material nuevo y recordar lo anteriormente aprendido. Se altera en 1º
lugar la memoria próxima, inmediata, primaria y progresivamente la
memoria remota, secundaria. La memoria procesual (cómo) está menos
afectada que la declarativa (qué).
* Lenguaje: disminución de la fluidez verbal, incapacidad de nombrar
objetos, vaguedad, imprecisión. Afasia: generalmente de aparición más
tardía. Puede conservarse sintaxis con construcción de frases menos
complejas. Alteración del lenguaje escrito.
* Praxias: dificultad para realización de tareas complejas (llamar por
teléfono) y luego sencillas (desvestirse). La alteración de las
funciones ejecutivas se relaciona con alteraciones en el lóbulo frontal
y vías subcorticales asociadas. Requiere: pensamiento abstracto,
planificación, secuenciación.
* Gnosias: alteración en el reconocimiento de objetos: agnosias visuales
(no reconocer persona), táctiles, corporales (derecha izquierda).
* Pensamiento abstracto y juicio: pensamiento abstracto: incapacidad
para afrontar situaciones nuevas, operaciones de abstracción y síntesis
o dar pasos adecuados para la consecución de un objetivo.
* Orientación: orientación temporal orientación espacial –> orientación
autopsíquica.
* Atención: dificultad para mantener la atención (aprosexia).
* Síntomas psicóticos (20-50% de demencias): delirios simples, poco
elaborados. Temas: persecución, robos, celos, daño y perjuicio, delirios
de sustitución, delirio dermatozoico de Ekbon.
* Alucinaciones (15-50%): visuales, auditivas, olfatorias o
cenestésicas. Si hay alucinaciones, peor pronóstico, probable rápido
deterioro cognitivo.
* Síntomas afectivos (20-70%): sobre todo en formas vasculares con
lesiones a localización frontal izquierda anterior, también en HNT,
Huntington, Parkinson. Más frecuentes en estadíos iniciales. Son menos
frecuentes los síntomas maniformes. Doble origen: reacción psicológica a
la pérdida de facultades + alteración de neurotransmisores por el
proceso degenerativo (sobre todo locus coeruleus y sustancia nigra). En
DTA, la presencia de depresión está asociada a un aumento de la
mortalidad.

Otros síntomas psiquiátricos: insomnio, ansiedad, delirium, trastorno
adaptativo mixto ansioso-depresivo. Alteraciones del sueño con inversión
del ciclo sueño/vigilia.

Alteraciones conductuales: raptus de violencia, extravíos, agresividad,
reacciones catastróficas ante mínimos contratiempos, caídas, vagabundeo,
conductas desinhibidas e inadecuadas, descuido de aspecto o aseo
personal, excesiva familiaridad con extraños. Síndrome de Diógenes:
tendencia a la recogida de basura (silogomanía), aislamiento, falta de
higiene, oposicionismo y retraimiento.

Personalidad: acentuación de rasgos preexistentes (caricaturización).
Deterioro social que se refleja en la vida cotidiana.

Otros: síndrome de Klüver-Bucy (raro) por lesión temporal bilateral con
hiperoralidad, hipersexualidad, agnosia e hiperactividad. La aparición
de incontinencia urinaria es un indicador de aumento de la mortalidad en
los siguientes 2-3 años.

===== Memoria

* Memoria inmediata sensorial (primaria): está en la mente mientas se
usa; si no se codifica en la memoria secundaria se pierde. Exploración:
recordar y reproducir lo presentado en 30”. Amplitud de dígitos.
* Memoria explícita declarativa
** Episódica (secundaria)
*** Reciente: recordar material presentado de varios segundos a
horas/días. Exploración: recordar 3 palabras 3-5’ luego de su
presentación.
*** Remota: recordar material presentado hace largo tiempo. Exploración:
recordar datos de semanas, meses o años atrás.
** Semántica (terciaria): repositorio de información personal o bien
aprendida (conocimientos).
* Memoria implícita, no declarativa de procedimiento.

==== Clasificación de demencias

===== Corticales

Con afasia, apraxia, agnosia, amnesia, acalculia. Disminución de la
habilidad de construcción, visual-espacial, de abstracción. Apatía. No
disartria hasta etapas avanzadas.

* Tipo Alzheimer: 70% de las demencias. Diagnóstico clínico por
exclusión, diagnóstico definitivo por hallazgos histopatológicos. * No
Alzheimer ** Demencia frontotemporal: inicio insidioso, edad < 65 años,
incidencia familiar, atrofia variable en LF/LT, EEG frecuentemente
normal. ** De neurona motora (esclerosis lateral amiotrófica) ** De Pick
** Afasia progresiva primaria ** Vasculares: demencia multiinfarto,
arteriosclerosis cerebral.

===== Subcorticales

Retardo psicomotor, menor afectación de memoria, mejor capacidad de
cálculo. Trastornos en las funciones ejecutivas. Perseveración (rigidez
cognitiva). Depresión, apatía, desinhibición, irritabilidad.
Constricción de afecto. Cambio de personalidad. Disartria. Con
frecuencia también se afecta el lóbulo frontal.

* Parkinson / Parálisis supranuclear progresiva * Huntington / Wilson *
Binswanger / CADASIL,

* HIV

A cualquier nivel: cuerpos de Lewy, degeneración corticobasal.

Demencia de cuerpos de Lewy: signos extrapiramidales tempranos,
deterioro temprano en la marcha, confusión aguda y alucinaciones
fluctuantes, hipersensibilidad con antagonistas de la Dopamina, ausencia
de respuesta con levodopa.

==== Demencias corticales

.Alzheimer

Factores de riesgo: edad (factor de riesgo de mayor peso), historia
familiar (x3.5% para familiares de 1º grado, 40% de concordancia en
gemelos monocigotos), historia de trisomía 21, género femenino (riesgo x
3 vinculado a disminución de Estradiol), poca educación, MSEC
(nutrición, exposición a tóxicos), trauma cerebral, depresión, APOE4.

* Inicio insidioso, difícil de establecer. * evolución progresiva: puede
existir período evolutivo corto. * sin oscilaciones, con deterioro
homogéneo en: memoria, atención, juicio y funciones simbólicas * con
indiferencia ante déficits * no existen indicios de otra enfermedad
mental o sistémica * no alteraciones en la marcha * edad > 65 años * AF
del Alzheimer

Estadio:

{empty}1. Leve (1-3 años): disminución moderada de memoria, + eventos
recientes, anomia, problemas con concepción de tiempo. Desorientación
geográfica. 2. Moderada (2-10 años): disminución severa de memoria,
afasia receptiva, desorientación en tiempo y espacio, trastorno de
juicio y en capacidad de resolución de problemas. 3. Severa (8-12 años):
grave afectación de memoria, juicio y orientación,. Lenguaje
incomprensible o mutismo, rigidez de postura y flexibilidad.
Incontinencia.

.Vascular

Factores de riesgo: clase social, género, edad, genes, factores
aterógenos, terreno vascular (HTA AIT AIC AVE), lesiones
periventriculares blancas. Al año de un ACV 1 de cada 5 pacientes
desarrolla una demencia .

* Inicio brusco o historia corta * Deterioro escalonado con
fluctuaciones súbitas * Deterioro desigual: alteración de memoria,
intelectual, signos focales. Estando preservados: conciencia de
enfermedad y capacidad de juicio. * Síntomas y signos focales * Cambios
en el estado de ánimo y personalidad Infartos pequeños y efectos
acumulativos en progresión geométrica en el tejido cerebral secundario a
enfermedad vascular sobre todo hipertensiva.

Diagnóstico improbable: disminución de funciones cognitivas de inicio en
edad temprana y evolución lenta y sostenida. Ausencia de hallazgos
focales. Ausencia de lesiones vasculares en estudios de neuroimagen.

Diagnóstico probable (criterio de NINDS-AIREN): cumple criterios de
demencia + enfermedad cerebrovascular (por neuroimagen o x hallazgos
clínicos) + relación temporal (aparición de demencia dentro de los 3
primeros meses post AVE, deterioro abrupto y curso fluctuante o
escalonado) + manifestaciones clínicas (trastornos tempranos en la
marcha, inestabilidad y caídas, problemas urinarios no urológicos,
parálisis seudobulbar, cambios en personalidad o ánimo, problemas en
funciones ejecutivas).

Diagnóstico definitivo (NINDS-AIREN): Diagnóstico probable + evidencia
histopatológica (pérdida focal de neuronas, astrogliosis en área de
infarto) + enredos neurofibrilares y placas amiloides < edad + ausencia
de otros hallazgos clínicos o patológicos que expliquen otra clase de
demencia.

.Mixta

Alzheimer + DMI = 20%. Reúne características de ambas

.Demencia frontotemporal Grupo heterogéneo de trastornos que provocan
neurodegeneración en áreas frontales y temporales footnote:[Convery, R.,
Mead, S., & Rohrer, J. D. (2019). Clinical, genetic and neuroimaging
features of frontotemporal dementia. Neuropathology and applied
neurobiology, 45(1), 6-18.]. Clínicamente se presentan con síntomas
comportamentales, trastornos del lenguaje (afasia primaria progresiva),
pudiendo haber superposición con la enfermedad de la neurona motora y
trastornos parkinsonianos atípicos. Existen variantes genéticas
(mutaciones en la progranulina, C9orf72 y la proteína tau asociada a
microtúbulos). Síntomas comportamentales: cambios en la personalidad con
desinhibición, apatía, falta de empatía (incapacidad de leer las
emociones de otros), obsesividad (movimientos repetitivos, acumulación,
rituales de limpieza), alteración en la preferencia de las comidas
(atracones o preferencias idiosincráticas, preferencia por dulces).
Comportamiento desinhibido: interacciones sociales embarazosas,
impulsividad, gastos, juego. Falta de insight (indiferencia al déficit).
Síntomas cognitivos: declinación de las funciones ejecutivas
(planeamiento, resolución de problemas, flexibilidad mental, atención,
memoria de trabajo). En general se preservan las funciones asociadas a
regiones posteriores del cerebro (memoria episódica, habilidades
visuoespaciales). Criterios internacionales: 3 de 6 síntomas: -
Desinhibición comportamental - Apatía o Inercia - Pérdida de la empatía
- Comportamiento compulsivo estereotipado o ritualístico - Hiperoralidad
o cambios dietéticos - Déficit ejecutivo con relativa conservación de la
memoria episódica Otros: delirios, alucinaciones multimodales, manía de
inicio tardío, depresión, síntomas catatónicos, problemas autonómicos
(percepción del dolor, alteración en la termoregulación). Hipersomnia.

==== Demencias subcorticales

Síntomas y signos específicos:

* trastornos motores según etiología * retardo o inhibición motora *
conducta: retardo

Ejemplo: Parkinson y Huntington

==== Secundarias

Infecciones, Lúes, SIDA, traumatismos, alcoholismo, metabólicas o
endocrinas, tumorales, hidrocefalia normotensiva, tóxicos o
medicamentos. No existen datos que nos orienten, lo que de todos modos
descartaremos por paraclínica. Son reversibles, favorecen deterioro.
Datos epidemiológicos: DTA (55-60%), DV (10-20%), mixtas (10-20%),
frontotemporal (5-10%), con cuerpos de Lewy (5-10%), abiotróficas
[Parkinson, Huntington] (5-8%), por ingesta crónica de fármacos (1-5%),
expansiva e hidrocefalia (1-5%), metabólicas (1-2%), otras (1-5%).

==== Prevención

Recomendaciones de la OMS footnote:[WORLD HEALTH ORGANIZATION, et al.
Risk reduction of cognitive decline and dementia: WHO guidelines.
2019.]:

.Evidencia fuerte:

* Actividad física: paciente sin déficit o con déficit leve. * Cesación
de tabaco * Dieta sana, balanceada

.Evidencia moderada: * Dieta mediterránea * Reducción de bebidas con
capacidad de daño * Intervenciones para disminuir sobrepeso

.Evidencia baja o muy baja * Entrenamiento cognitivo * Manejo de la
hipertensión (solo en relación a la demencia) * Manejo de la diabetes
(solo en relación a la demencia) * Manejo de la dislipidemia

.Evidencia insuficiente * Uso de antidepresivos para reducir riesgo de
demencia * Uso de ayudas para la audición

.Sin evidencia * Actividad social * Grupos de apoyo

.No recomendado * Vitamina B y E, ácidos grasos poliinsaturados,
suplementos diatéticos

=== Encare

==== Agrupación sindromática

Destacar motivo de consulta

* Síndrome conductual Crisis de EPM, conductas absurdas, antisociales.
IAE, en contexto de impulsividad (no mide riesgo - juicio), dependiendo
de lo cognitivo. Conductas basales.
* Síndrome delirante Delirio pobre, ideación paranoide, robo, vinculado
a trastornos cognitivos. Manifestado en lo conducutal por [desarrollar].
* Síndrome confuso-onírico Ver Delirium.
* Síndrome depresivo Vinculado a lo cognitivo. Ver Depresión.

Todo esto inscrito en un contexto sintomático que pasamos a analizar.

===== Síndrome intelectual deficitario adquirido

Dado por un debilitamiento progresivo, global y profundo de las
funciones intelectuales y las conductas sociales, desde hace... y que se
manifiesta a diferentes niveles:

====== A nivel intelectual

Alteración en las funciones psíquicas superiores

* Razonamiento: con alteración del capital mental, ya que el paciente es
incapaz de ordenar con la ayuda de conceptos una construcción lógica en
relación a un fin usando técnicas intelectuales y verbales (ej.:
operaciones aritméticas simples). Con pérdida de la capacidad de
abstracción (ej: interpretación de refranes, conceptos en pruebas de
semejanzas y diferencias, conceptos abstractos [patria], etc.)
* Juicio: perturbación de los valores lógicos y de la realidad con
incapacidad para medir las consecuencias de sus actos (ej.: sale
desnudo). Con carencia autocrítica dado por los actos citados, la
carencia de conciencia de morbidez y la indiferencia frente a los
déficits.
* Adquisividad: incapacidad de utilizar la experiencia previamente
adquirida ante situaciones nuevas (ej.: manejo del dinero).

Incapacidad operatoria o de funciones operacionales

Memoria: imprecisiones e inexactitudes en el relato:

* fijación: olvido de cosas que le dicen o pensaba hacer * inmediata:
repetición de objetos * evocación: ** tardía s/p: hablar de gravedad si
está alterada ** reciente: incapacidad de retener más de un minuto el
material (ej: nombre del entrevistador). También muestra la incapacidad
de fijación. Se aprecian falsos reconocimientos, fabulación. Ley de
Ribot: solidez de recuerdos antiguos en relación a los recientes.
Orientación: . 1º alopsíquica (primero tiempo, luego espacio) .

2º autopsíquica Perderse en espacios grandes y abiertos (vinculado a la
memoria de fijación, no recuerda el recorrido andado). No puede acceder
a los pensamiento abstractos (tiempo). . Atención: dispersa y lábil.
Pérdida de concentración, dado en la repetición retrógrada de dígitos,
meses y días de la semana.

Alteración de las funciones simbólicas

* Afasia / lenguaje: vago, no finalista, superficial, anecdótico, con
tendencia a la aprobatividad, empobrecido, estereotipado.
* Gnosias: falla en el reconocimiento o identificación de objetos a
pesar de funciones sensoriales intactas. Estereognosia: reconocimiento
por el tacto.
* Praxias: incapacidad para llevar a cabo tareas motoras a pesar de que
tanto la comprensión como las funciones motoras están intactas. Praxia
del vestir. Praxias:
** Constructivas: figuras bi-tridimensionales
** Ideomotoras: gestos simples (venia, saludo)
** Ideatorias: actos que requieren coordinaciones sucesivas para
utilizar un objeto (peinarse, fósforo, etc.)

====== A nivel ético-moral

Relación estrecha con la alteración del juicio que igual destacamos por
su jerarquía. Dado por pérdida de las inhibiciones con exaltación
pulsional que se expresa por conductas sexuales anormales:
exhibicionismo, intento de violación, lenguaje soez. Conductas con
implicancias médico-legales, bulimia, higiene personal deficitaria,
alcoholismo, vagabundeo, conductas antisociales.

====== A nivel social

Reducido al mundo intrafamiliar, sin proyección social, desde hace...
alteración de pragmatismos. Destacar grado de autonomía.

Este síndrome deficitario se acompaña de elementos de alteración en la
esfera del humor y la afectividad: emotividad, labilidad afectiva,
impulsividad, autoritarismo, falta de contención emocional. El síndrome
depresivo está ligado como comorbilidad.

===== Síndrome de alteración de las conductas basales y pragmatismos

Dado por insomnio, anorexia, pragmatismos analizados en el síndrome
deficitario.

===== Síndrome somático

CV: HTA, etc. Neurológico: TEC, motor deficitario, etc. General.

==== Personalidad y nivel

Nivel: destacar empobrecimiento con balance negativo (rico que se ha
empobrecido)

Personalidad: premórbida vs. actual: acentuación de rasgos.

==== Diagnóstico positivo

===== Demencia

Por la existencia de un síndrome deficitario intelectual adquirido con
debilitamiento progresivo que interfiere con la actividad cotidiana y
lleva al paciente a una pérdida de su autonomía, donde importa destacar
el deterioro del juicio y las manifestaciones a nivel ético-moral, de X
años de evolución, en una persona de X edad, que no presentaba previo al
inicio del cuadro elementos de deterioro (+ lo orgánico).

CIE-10: “síndrome debido a una enfermedad del cerebro, generalmente de
naturaleza crónica‘ o progresiva, en la que hay déficit de múltiples
funciones corticales superiores, entre ellas: memoria, pensamiento,
orientación, comprensión, cálculo, capacidad de aprendizaje, lenguaje y
juicio”.

DSMIV: ``presencia de múltiples déficits cognitivos (que incluyen
deterioro de memoria) que se deben a los efectos fisiológicos directos
de una enfermedad médica, o a efectos persistentes de una sustancia o a
múltiples etiologías''.

===== Modelo clínico

====== Cortical

Alteración de memoria; afectación de gnosias, praxias y lenguaje,
habilidades visuoespaciales y cálculo; pueden haber dificultades en las
funciones ejecutivas (organización, abstracción, juicio y capacidad de
introspección); movimientos preservados hasta fases tardías;
personalidad poco afectada (cierta pasividad o brusquedad en las
reacciones); en la afectividad: cierta labilidad emocional. Pueden ser
conscientes del déficit.

====== Subcortical

Enlentecimiento progresivo de todos los procesos mentales, labilidad,
depresión, disartria, signos bulbares, hemiparesia motora pura;
inicialmente menos afectación en funciones cognoscitivas como
numeración, cálculo, etc.; menor alteración de memoria visual o verbal;
déficit de aprendizaje de nuevos movimientos motores o tareas;
disminución de habilidades para la organización y planificación;
alteraciones de la motilidad (movimientos involuntarios, corea,
temblor); conservación del lenguaje por más tiempo que la forma
cortical; cambios en la personalidad intensos (apatía, inercia, pérdida
de la espontaneidad); alteraciones repetidas y precoces en el humor
(depresión y ocasionalmente manía insulsa). Se asemeja más a un cuadro
de alteración del humor, con menos evidencia de alteración de las
funciones cognoscitivas. Ejemplos: Huntington, Parkinson, Parálisis
Supranuclear Progresiva.

===== Tipo clínico (CIE-10)

* Demencia en la enfermedad de Alzheimer. Especificadores: de inicio
precoz (<65 años)/ tardío; atípica o mixta. Diagnóstico por: presencia
de cuadro demencial de comienzo insidioso y curso continuo + exclusión
de otras causas + ausencia de AVE + AF DTA o Down
* Demencia vascular . Especificadores: de inicio agudo; multiinfarto;
vascular subcortical; vascular mixta cortical y subcortical; otras; sin
especificar.
* Demencia en enfermedades clasificadas en otro lugar: Pick,
Creutzfeldt-Jakobson; Huntington; HIV; enfermedades específicas
clasificadas en otro lugar.
* Demencias sin especificación: sin síntomas adicionales, con predominio
de: ideas delirantes, alucinaciones, síntomas depresivos, síntomas
mixtos.
* Síndrome amnésico orgánico no inducido por alcohol u otras sustancias
psicotropas

===== Momento evolutivo

* Incipiens: sólo déficit intelectual (no existe social o ético-moral)
* Período de estado: ya constituido.
* Terminal: deterioro importante, grave.

===== Gravedad

* Leve: deterioro laboral con vida independiente.
* Moderada: vida independiente peligrosa, supervisión, autocrítica
alterada: juicio.
* Grave: supervisión continua, no existe higiene personal mínima, juicio
muy alterado, lenguaje incoherente o mudo. Nos inclinamos a.... sabiendo
que el diagnóstico definitivo está sujeto a la compensación del cuadro
actual, con la corrección de factores que favorecen el deterioro,
incidiendo en éste.

===== Complicaciones

* Síndrome depresivo (comorbilidad)
* Excitación psicomotriz
* Síndrome delirante

Que perjudica el deterioro preexistente y sobre el cual actuaremos en lo
inmediato.

===== CIE-10

Demencia (general)

{empty}1. Trastornos de funciones corticales superiores: o memoria o
lenguaje o comprensión o aprendizaje o flujo de ideas o razonamiento y
juicio 2. Los trastornos causan disturbios en las actividades diarias 3.
Preservación del estado de conciencia (descarta confusión) 4. Seis meses
de evolución (criterio no presente en DSM).

Demencia tipo Alzheimer Criterio general para demencia +

* Inicio insidioso * deterioro lento y progresivo * exclusión de otras
demencias * ausencia de inicio súbito y de ACVs * Sin signos
neurológicos focales o daño focal

==== Diagnósticos diferenciales

{empty}1. Cambios cognitivos de la edad avanzada (``olvidos seniles
benignos''): término no bien dilucidado, disminución de memoria no
vinculada a patología que aparece en > de 50 años, con pruebas de
memoria con rendimiento inferior al adulto joven promedio, con tests de
inteligencia normales, en ausencia de patología evidenciable.
Frecuentemente se pierde la memoria de término medio. 2. Seudodemencia
depresiva: inicio relativamente abrupto, con trastornos cognitivos
exagerados, con poca motivación, agotamiento ante leves esfuerzos,
muchos ``no se'', ejecución inconsistente en las evaluaciones,
irritabilidad, insomnio. Ausencia de afasia, agnosia, apraxia. Puntean
mejor en pruebas de pares asociados. Los pacientes con demencia son más
sugestionables, los pacientes con SDD son más rígidos afectivamente.
Tomar en cuenta que la SDD puede ser un prodromo de Alzheimer. Importa
criterio temporal (primero la alteración cognitiva y luego la depresión:
demencia), presencia o no de acontecimiento depresógeno, juicio
conservado, AP o AF afectivos, prueba terapéutica. 3. Delirium:
generalmente se distingue por presentar inicio agudo, trastorno de
conciencia, importante trastorno de la atención, trastornos del
sueño/vigilia, curso fluctuante en el día, desorientación,
alucinaciones, lenguaje incoherente. Si bien estos elementos también
pueden estar presentes en una demencia, están en un grado mucho menor y
de forma aislada. Si un paciente está confuso NO es posible realizar un
diagnóstico de demencia. 4. Drogas / medicamentos /alcohol 5. Trauma
cerebral externo / interno 6. Procesos expansivos intracraneales 7.
Infecciones: lúes / SIDA, TBC 8. Enfermedades metabólicas (tiroides,
hepáticas, diabetes, vitaminas: B12, tiamina). 9. Enfermedad sistémica
10. Retraso mental: según edad.

==== Diagnóstico etiopatogénico y psicopatológico

.Fisiopatología Estrés oxidativo: pérdida del balance
prooxidativo/antioxidativo, relacionado con procesos de envejecimiento,
contribuye a cambios en el sistema colinérgico. Hay refuerzo mutuo entre
el estrés oxidativo y la transmisión glutamatérgica (frente a un aumento
de radicales libres, hay mayor acción glutamatérgica). Radicales libres:
son especies oxigenadas altamente reactivas que contribuyen a la
fagocitosis. Cuando aumentan los radicales libres, se promueve el daño
neuronal. Apoptosis: muerte celular inducida por radicales libres.
Excitotoxicidad: acción neurotóxica por exceso de estimulación, mediada
por Glutamato. Se postula un rol en la enfermedad de Parkinson,
Huntington y Alzheimer. A nivel neuroanatómico: Hallazgos macroscópicos:
no hay hallazgos que sean patognomónicos. Atrofia cerebral, dilatación
ventricular, reducción del volumen cerebral. Hallazgos microscópicos:
placas amiloides (estructuras extracelulares con centro de proteína beta
amiloide rodeado de axones y dendritas atróficas, su densidad no guarda
relación con el deterioro cognitivo, son más numerosas en pacientes con
demencia tipo Alzheimer, sobre todo en corteza e hipocampo), enredos
neurofibrilares (estructuras intracelulares [no exclusivos de DTA] en
forma de pares de filamentos helicoidales [proteína Tau que ha tenido
fosforilación extrema] y restos de neurotúbulos destruidos, respuesta a
eventos degenerativos tóxicos y traumáticos), degeneración
granulovacuolar, cuerpos de Hirano.

.Psicopatología El estado demencial comporta una desorganización del ser
razonable (trastorno del juicio) y de la autoconducción con regresión
del comportamiento y alteración de su adaptación a la realidad con
incapacidad de integrar comportamientos de actividad intelectual
superior debido a un deterioro a nivel del fondo mental y del patrimonio
mental (escala de valores lógicos y éticos). Para Jaspers: corresponde a
un proceso orgánico que lleva a una destrucción de la vida psíquica y
creación de un nuevo estado de la personalidad.

Demencia tipo Alzheimer

Etiología desconocida. Hay una reducción de las fibras colinérgicas en
particular en el LT, en especial en áreas de asociación. Anatomía
patológica Disminución del número de neuronas sobre todo en el
hipocampo, sustancia innominada, locus coeruleus y corteza
temporoparietal y frontal. Hallazgos microscópicos 1. Degeneración
neurofibrilar en forma de ovillos o haces neurofibrilares,
intracelulares, en las dendritas de las neuronas piramidales o en las
neuronas multipolares. Son una colección de filamentos de la proteína
fosforilada t, componente normal de microtúbulos que se hace anormal y
excesivamente fosforilada, formando filamentos helicoidales apareados.
Se ven sobre todo en el hipocampo, corteza entorrinal, subiculum y
corteza (capas III y IV). 2. Placas amiloides (seniles): terminaciones
axonales degeneradas y dendritas anormales que rodean una zona central
de sustancia amiloide. Son extracelulares, compuestas por fibras de
proteína beta-amiloide. Presentes sobre todo en hipocampo y corteza. 3.
Cuerpos de Hirano: estructuras intracelulares eosinófilas, visibles al
MO. 4. Degeneración vacuolar con vacuolas intracitoplasmáticas,
centradas por un gránulo argirófilo. Los haces (1) y placas (2) pueden
verse en ancianos no demenciados pero en menor número. La presencia de 5
o más placas x campo microscópico indica DTA. Pueden encontrarse cuerpos
de Lewy en las neuronas corticales. Neurotransmisores Colinérgico:
afectación especial del núcleo basal de Meynert, sustancia inominada y
región sublenticular (primera fuente de las proyecciones colinérgicas) y
reducción de hasta el 90% de la actividad cortical de la
colinoacetiltransferasa. Serotoninérgico: pérdida neuronal en los
núcleos del rafe (responsable de los cambios de conducta).
Catecolaminas: pérdida neuronal en el locus coeruleus. Sistema
peptidérgico: somatostatina, sustancia P, sustancia Y, vasopresina.
Sistema histaminérgico y aminoacidérgico (disminución del ácido
glutámico y aspártico y GABA). Factores de riesgo Historia familiar de
demencia y presencia de sndrome de Down. Otros: no confirmados.

==== Paraclínica

El diagnóstico de demencia es clínico. La paraclínica estará destinada
a:

* cuantificar el grado de déficit y evolución de éste * corroborar
diagnóstico etiopatogénico planteado * descartar diferenciales

Valoración general y de polo neurológico, cardiovascular, medio interno,
focos infecciosos neurólogo + internista. Son de importancia los
instrumentos de evaluación rápida, que si bien no son sustitutos de la
evaluación clínica y no son específicos para cada tipo particular de
demencia son breves y de fácil administración complementando datos
clínicos y evolutivos. Puede realizarse el MMSE (Mini Mental State
Examination), BOMC (Bless), test de la carátula del reloj.

Minimental (Folstein - MMSE): máximo 30 puntos: orientación temporal
(5), orientación espacial (5), registro (3), atención y cálculo (5),
memoria reciente (3), lenguaje [nombrar (2), repetir (1), secuenciación
(3), lectura (1), escritura (1), copia de figura (1)]. 0-10 = trastorno
cognitivo severo. 11-20 = moderado. 21-26 = leve. Función cognitiva
normal = > 26.

Test del reloj: pedir que dibuje un reloj, con las marcas de horas y que
ponga las agujas a una hora determinada. Evalúa: habilidad
témporo-espacial, existencia de perseveración, habilidad ejecutiva y
capacidad de abstracción.

.Biológico Evaluación sistemática Examen físico completo, con énfasis en
lo neurológico, con fondo de ojo y consultas con neurólogo. Deben
buscarse signos focales, hidratación, nutrición. valoración CV con
examen central y periférico. Consulta con internista o cardiólogo para
valoración CV clínica y paraclínica y evaluación de terreno ATC e HTA y
su control. Rutinas: hemograma, glicemia, ionograma, azoemia,
creatininemia, orina. ECG y RxTx Función tiroidea. Dosificación de B12.
VDRL. Evaluación selectiva Orina, toxicología, radiografías, HIV, ANA
(anticuerpos antinucleares), ApoE (apolipoproteína E), Tau, proteína
beta amiloide plaquetario, Tropicamida (antagonista muscarínico que se
usa como gotas oftálmicas en una prueba que evalúa midriasis en
pacientes con Alzheimer). Punción lumbar: solo si hay síntomas de
irritación meníngea de evolución muy rápida. TAC de utilidad relativa
para el diagnóstico planteado ya que sabemos que no existe correlación
anatomo-clínica pudiéndose ver signos inespecíficos: atrofia cortical y
dilatación ventricular, hipodensidades que nos indiquen infartos
múltiples. Descartaremos causas reversibles que pueden estar incidiendo.
RMN: aunque no existe correlación anátomo-clínica, puede ser de
relevancia para descartar diagnósticos diferenciales y causas
reversibles de demencia, así como para control evolutivo. Puede
evidenciarse hiperdensidad de la sustancia blanca: son debidas a gliosis
y esclerosis. Se pueden ver en personas sanas, con demencia vascular,
Alzheimer o con depresión. Cuando son solamente ventriculares, son más
frecuentes en Alzheimer. Otros procedimientos estructurales: SPECT
(flujo sanguíneo, menor resolución, bajo costo), PET (mejor resolución,
alto costo), RMF (resonancia magnética funcional: resolución espacial
milimétrica) EEGQ (electroencefalografía cualitativa = mapeo): utilidad
relativa, excepto en casos de comorbilidad. Si hay alcoholismo:
funcional hepático y enzimograma. Si se piensa en sífilis: VDRL,
FTA-ABS, signo de Argyll-Robertson, PL: citológico, bacteriológico y
bioquímico. .Psicológico Una vez superado el cuadro actual (depresivo,
delirante, confusional) consulta con neuropsicólogo para valorar
funciones instrumentales y simbólicas. Evaluación psicométrica: Weschler
(WAIS) para: cuantificar deterioro, control evolutivo del paciente.
.Social Composición familiar, terceros, vínculos, red de soporte,
dinámica de funcionamiento: evaluando aspectos positivos de éste.
Relaciones afectivas, MSEC. AP ingesta de fármacos. Historias
anteriores.

==== Tratamiento

Internar en sala de Hospital General, preferentemente aislado. Breve por
las dificultades adaptativas (ruptura de referencias de orientación y
afectivas). Equipo multidisciplinario... Destinado a compensar el cuadro
actual, estudio completo, instrumentación de medidas que ataquen
factores de riesgo. Conjuntamente con internista. Compensaremos
alteraciones orgánicas para asegurar ausencia de tóxicos endógenos...
minimizando agravio encefálico...

===== Del cuadro actual

====== Cuidados generales

* * orientación de realidad (reloj, calendario)
* * asegurar buen soporte hídrico y nutritivo
* * higiene de emuntorios
* * vigilar conductas peligrosas y deambulación
* * asegurar reposo y tranquilidad
* * control de conciencia, PA, pulso, temperatura
* * controles diarios de cumplimiento con la medicación

====== Farmacológico

Con dosis menores a las del adulto e incrementos lentos dado la
hipersensibilidad propia de esta patología y las alteraciones orgánicas
propias de la edad que llevan a un aumento de la concentración de
fármacos en sangre. Será sintomático:

* Agitación: dependerá del estadío de la demencia. En estadíos iniciales
y agitación leve-moderada, puede usarse un ISRS como el citalopram 20
mg/día footnote:[Schneider, Lon S., et al. "Heterogeneity of treatment
response to citalopram for patients with Alzheimer’s disease with
aggression or agitation: the CitAD randomized clinical trial." American
Journal of Psychiatry 173.5 (2016): 465-472.] * Crisis de excitación PM:
Tioridacina (evitándolo si es prostático, está confuso: en ese caso dar
solo Haloperidol) en solución v/o 5 mg H:8, 5 mg H:14, 10 mh H:20
(atentos a efectos secundarios anticolinérgicos [s/t confusión],
hipertensión prostática, vigilando sobresedación y caídas lo que nos
obligará a disminuir la dosis). Según la evolución valoraremos el
agregado de 1 mg de Haloperidol v/o H:20 para combatirla. * Delirio:
Haloperidol v/o 1,5 mg c/8 hs (1,5 - 1,5 - 2,0) en solución. * Ansiedad:
Clonazepam (sedante, control de impulsos, estabilizante del humor, pocos
efectos paradójicos) 1mg v/o H:8, 2mgH:20 a regular según evolucón y no
pasar de 6-8 mg/día ya que las benzodiacepinas la confusión, amnesia,
efectos paradójicos, sobresedación, agravan síntomas deficitarios. *
Depresión: ISRS por sus pocos efectos secundarios y por no ser
anticolinérgico Fluoxetina 10 mg H8. Agregar a los 2-3 días 10 mg v/o
H14 y esperar respuesta, pudiendo aumentar según tolerancia hasta un
máximo de 40 mg/día. Sertralina: 25 mg H8 inicial, luego 50 mg/día.
Latencia de 7-15 días. Atentos a efectos secundarios (ansiedad,
insomnio). * Trastornos del sueño: ** Higiene del sueño: laborterapia,
evitar cafeína y alcohol, caminatas, evitar sueño diurno. En caso de que
éstas medidas no sean suficientes usar tratamiento farmacológico **
Ritmo circadiano: melatonina footnote:[Vecchierini, M. F., Kilic-Huck,
U., & Quera-Salva, M. A. (2021). Melatonin (MEL) and its use in
neurological diseases and insomnia: Recommendations of the French
Medical and Research Sleep Society (SFRMS). Revue Neurologique, 177(3),
245-259.] ** Conciliación: Zopiclona: ½ comp de 7,5 mg H:20 v/o •
Zolpidem: 5 mg v/o H:20 ** Mantenimiento: Flunitrazepam: 1 mg v/o que
iremos según necesidad y retiraremos pronto. * Como favorecedores de la
circulación cerebral, conjuntamente con internista, realizaremos: **
Nimodipina: 30 mg v/o c/8 hs, que mejora la circulación cerebral sin
fenómeno de robo. ** Pentoxifilina: 400 mg v/o c/8hs que elasticidad de
glóbulos rojos.

Al alta hospitalaria: retiro de medicación evitando polifarmacia (mínimo
indispensable).

* Situaciones clínicas especiales Paciente agitado Determinar grado:
perturbado / conducta inapropiada / violento. Reducir riesgos, modificar
el ambiente.

===== A largo plazo

.Demencia Tipo Alzheimer

Inhibidores de la Acetilcolinesterasa (AcE): retardan el deterioro
sintomático a corto plazo. A largo plazo: disminuyen la velocidad de
progreso de la enfermedad, retardan la institucionalización del paciente
y reducen la mortalidad.

Donepezilo: inhibidor reversible. 5-10 mg en dosis única (presentación
comprimidos de 5 y 10 mg). Util en formas leves y moderadas. Efectos
secundarios: náuseas, vómitos, diarreas, estreñimiento, bradicardia
(disminuyen con la continuación del tratamiento). Puede haber lesión
hepatocelular reversible al suspender el tratamiento. Debe suspenderse
1-2 semanas antes de intervenciones quirúrgicas. NO administrar si hay
asma, EPOC, arritmias, IC y alteraciones de la micción.

Rivastigmina: inhibidor seudo-irreversible. Se inicia con 1.5 mg c/12 ,
con las comidas, x 2 semanas, la dosis terapéutica es de 3-6 mg cada 12
horas (6-12 mg/día) llegando a ésta con aumentos escalonados de a 1.5-3
mg, con al menos 2 semanas en cada nivel de dosis. Efectos secundarios
que más frecuentemente llevan al abandono: náuseas, vómitos, anorexia.
Presentación: comprimidos de 1.5, 3, 4.5 y 6 mg. Duración del
tratamiento: tiempo indefinido. No tiene interacciones a través del
citocromo P-450, no requiere monitoreos de laboratorio. Mecanismo:
aumenta la transmisión colinérgica especialmente en el hipocampo y
corteza cerebral. No debe administrarse en caso existencia de alteración
de la conducción cardíaca.

Antioxidantes: vitamina E - IMAO B. Los antioxidantes tienen el objetivo
de disminuir la producción de radicales libres, minimizando el riesgo de
muerte neuronal por apoptosis.

Selegilino: antioxidante, IMAOB. 2.5-5 mg v/o cada 12 horas. Efectos
secundarios: síncopes, caídas por hipotensión. Riesgo de crisis
hipertensivas e interacción con ISRS y ADT. Vitamina E: antioxidante
usado en prevención y tratamiento. Dosis 800-1000 UI en toma única. No
mejora la función cognitiva comparado con el estado basal, pero
disminuye o detiene el proceso, lentifica la lesión de la neurona
provocada por depósitos amiloides. Efectos secundarios: prolongación del
tiempo de coagulación.

Otros

Ginko Biloba: 120-240 mg/día fraccionados en 2-3 tomas. Antioxidante,
aumenta perfusión de los tejidos, aumenta tolerancia a la hipoxia,
estimula la formación de circulación colateral, estabilizador capilar,
reduce inhibición de receptores colino-muscarínicos asociados con la
edad avanzada. Efectos secundarios escasos: cefaleas, GI, alergia.
Mejoría cognitiva demostrada. Presentación: cm 40 - 80 mg (Tebokan,
Tebokan Forte, Clarvix, Ginkgo 80 fuerte).

Estrógenos: Estradiol E4: dosis = 0.625-2.5 mg en única toma diaria.
Acción antioxidante y neuroprotectora (protegen la neurona de la
proteína beta-amiloide). Ayudan a mantener la memoria y capacidad de
aprendizaje. Retrasan el inicio de la DTA y produce mejoría en la DTA
establecida. Modulan la secreción de Acetilcolina en el hipocampo por
acción sobre la colinoacetiltransferasa (s/t en los núcleos basales y
áreas de proyección), genera un incremento de ramificaciones
dendríticas, modulan los receptores específicos de la Serotonina, actúan
sobre las neurotrofinas (proteínas que mantienen los axones y
dendritas), disminuyen densidad de receptores beta-adrenérgicos y 5HT2,
inhibe la actividad glutamatérgica. Efectos secundario: menorragia,
sensibilidad de senos, GI, HTA, tromboembolias. Manejo con múltiples
precauciones. Presentaciones: Estrofem 2mg y 4 mg. Estrógenos
conjugados: Premarin 0.625 mg-1.25 mg. Quinestrol 1.5 mg.

Antiinflamatorios: Indometacina, Ibuprofeno. Dosis: 100-150 mg/día.
Efectos secundarios: GI, ulcus, anemia, función renal.

Nimodipina: bloqueador de canales de calcio, vasodilatador cerebral,
antiisquémico, alta liposolubilidad (> concentración en SNC). Mecanismo
aumento de somatostatina en LCR (disminuida en pacientes con DTA).

Es dudosa la eficacia de precursores de la acetilcolina (lecitina,
colina y CDP colina): agentes presinápticos que supuestamente aumentan
la síntesis y liberación de acetilcolina.

No existe tratamiento farmacológico. Debemos instrumentar un seguimiento
regular pesquisando toda alteración metabólica o infecciosa que debe ser
rápidamente corregida. Estará destinado a obtener una mejora adaptación,
para lo que implementaremos s/t medidas psicosociales.

Control de medicación semanal en policlínica (que se irán espaciando
hasta ser mensuales).

.Demencia vascular

Control de riesgos: HTA, hiperlipidemia, diabetes, fibrilación
auricular. Tratamiento específico: Acido acetil-salicílico. Ginko
Biloba. Pentoxifilina: utilidad discutida. Antagonistas del calcio:
Nimodipina: ayuda a controlar HTA, actúa como protector en situación de
hipoxia o toxicidad neuronal y protegen neurona (el Ca++ libre
intracelular activa los sistemas enzimáticos intracelulares que causan
muerte celular).

Intervenciones farmacológicas en trastornos no cognitivos Apatía:
Metilfenidato, anfetaminas. Depresión: ISRS, Nortriptilina, Desipramina,
ASRS. Segunda línea: ECT. Agitación: VAL, CBZ, Trazodona,
beta-bloqueante. Segunda línea: benzodiacepinas de acción corta.
Psicosis o agitación severa, delirio: Risperidona, Haloperidol,
Quetiapina, Olanzapina, Clozapina, Tioridazina. Segunda línea:
combinación. Insomnio: Trazodona, benzodiacepinas, Zolpidem.
Intervenciones no farmacológicas Psicoeducación familiar. Terapia de
reminiscencias, estimulación positiva. Terapia recreativa (ejercicios,
danza) Casos leves: grupos de terapia de sostén.

Social: Psicoeducación, explicando la enfermedad y el pronóstico y la
importancia de las medidas terapéuticas continencia y estímulo:
instrucción y apoyo con conexión a grupos de Alzheimer (familiares).
ambiente estable y predecible, para que el paciente excluya nuevo
aprendizaje, lectura y comentario de periódicos, actividad física
regular, reconocimiento de lugares. a largo plazo se podría plantear la
institucionalización, efectuando un balance entre la evolución del
paciente y su necesidad de supervisión continua y la continencia del
medio.

==== Evolución y pronóstico

Está marcado por la enfermedad de fondo. Pensamos que el cuadro actual
será controlado con el tratamiento instituido. Una vez corregido dicho
cuadro, mejorará el déficit cognitivo. Si bien tal función le permite
por el momento mantener cierta autonomía, nos orientamos a un pronóstico
regular/malo ya que estamos:

* ante una enfermedad irreversible sin tratamiento específico
(Alzheimer, Pick, Huntington, Parkinson) * ante una enfermedad sobre la
cual podremos instrumentar un tratamiento paliativo de su HTA (DMI).

Complicaciones frecuentes en DTA:

* apatía, pérdida de afecto y motivación
* agitación, ansiedad
* depresión
* desinhibición
* alucinaciones y cuadros delirantes

Complicaciones: - episodios depresivos frecuentes, para lo cual
mantendremos la medicación AD - alteración de juicio: conductas con
implicancias ML Pronóstico ligado a continencia sociofamiliar.

Pronóstico vital alejado: ligado a trastornos orgánicos. DMI: dependerá
del control CV. En el seguimiento del paciente demente:

* rastrear condiciones de comorbilidad
* operar en consonancia con familiares y cuidadores
* medidas para mejorar la conducta / ánimo
* medidas para la modulación del ambiente.
