= Síndrome de Korsakoff

== Descripción

Parte del Síndrome de Wenicke-Korsakoff (SWK) descrito en 1881
(Wernicke) y 1889 (Korsakoff). Cuadro de comienzo súbito con un período
de confusión y ocasionalmente con oftalmoplegia-nistagmo o ataxia.
Post-mortem se encontraban pequeñas hemorragias en los cuerpos mamilares
(área del cerebro involucrada en la memoria reciente y en la visión
binocular)

Los síntomas precoces comprenden: deficiencia de tiamina, pérdida de
memoria reciente retrógrada, pérdida de memoria anterógrada, precedida
de consumo crónico de alcohol. La pérdida de ambras memorias, producen
una extinción de la evocación de eventos desde el inicio del cuadro.

== Terminología

- Síndrome de Wernicke: generalmente se aplica a la deficiencia de
Tiamina sin uso de alcohol. - Síndrome de Korsakoff: deficiencia de
Tiamina precedida de uso crónico de alcohol, con inicio agudo y florido.

== Clínica Presentaciones muy dispares con diferentes componentes de:
amnesia footnote:[Blansjaar, B. A., Takens, H., & Zwinderman, A. H.
(1992). The course of alcohol amnestic disorder: a three‐year follow‐up
study of clinical signs and social disabilities. Acta Psychiatrica
Scandinavica, 86(3), 240-246.], delirium footnote:[ Wijnia JW, Oudman E
(2013) Biomarkers of delirium as a clue to diagnosis and pathogenesis of
Wernicke-Korsakoff syndrome. Eur J Neurol. 20:1531–1538.], demencia
footnote:[Ridley NJ, Draper B, Withall A (2013) Alcohol-related
dementia: An update of the evidence. Alzheimers Res Ther. 5:3.],
encefalopatía footnote:[Isenberg-Grzeda E, Hsu AJ, Hatzoglou V, Nelso C,
Breitbart W (2015) Palliative treatment of thiamine-related
encephalopathy (Wernicke’s encephalopathy) in cancer: A case series and
review of the literature. Palliat Support Care. 13:1241–1249], trastorno
de personalidad footnote:[Plutchik R, DiScipio WJ (1974) Personality
patterns in chronic alcoholism (Korsakoff’s syndrome), chronic
schizophrenia, and geriatric patients with chronic brain syndrome. J Am
Geriatr Soc. 22:514–516.], abstinencia de alcohol footnote:[Trevisan LA,
Boutros N, Petrakis IL, Krystal JH (1998) Complications of alcohol
withdrawal: Pathophysiological insights. Alcohol Health Res World.
22:61–66.], trumatismo footnote:[Brion S, Plas J, Mikol J, Jeanneau A,
Brion F (2001) Post-traumatic Korsakoff’s syndrome: Clinical and
anatomical report. Encephale. 27:513–525.] y psicosis footnote:[Ramayya
A, Jauhar P (1997) Increasing incidence of Korsakoff’s psychosis in the
east end of Glasgow. Alcohol Alcohol. 32:281–285.]

Por el consumo de alcohol puede haber: neuropatía, falla hepática,
várices esofágicas, otros trastornos neuro-psiquiátricos, infeciones,
ansiedad-depresión, formas de cáncer vinculadas al alcohol
footnote:[Westermeyer JJ, Soukup B (2021) Late-onset cases of Korsakoff
amnestic syndrome with CNS comorbidities: Suggestions for long-term
management. Addict Disord Treat. 20:69–73.].

=== Signos patognomónicos y curso Los pacientes poseen una evocación
"arcaica" intacta a pesar de las diferentes alteraciones en la memeoria
presentes footnote:[Cutting J (1978) The relationship between
Korsakoff’s syndrome and `alcohol dementia'. Br J Psychiatry.
132:240–251.] footnote:[Spiegel DR, O’Connell K, Stocker G, Slater J,
Spiegel A (2020) A case of Wernicke-Korsakoff syndrome initially
diagnosed as autoimmune limbic encephalitis: Differential diagnosis of
delirium and short-term memory deficits. Prim Care Companion CNS Disord.
22:20l02693.]. Existe una afectación de memoria y aprendizaje de forma
desproporcionada en relación a otras funciones cognitivas, en un
paciente alerta footnote:[Victor M (1989) The Wernicke-Korsakoff
syndrome and related neurologic disorders due to alcoholism and
malnutrition. Philadelphia: F.A. Davis.].

A esto se le agrega neuropatía periférica y signos oftalmológicos
footnote:[Caine D, Halliday GM, Kril JJ, Harper CG (1997) Operational
criteria for the classification of chronic alcoholics: Identification of
Wernicke’s encephalopathy. J Neurol Neurosurg Psychiatry. 62:51–60.].
Sin embargo la ataxia ocurre solo en 23

El tratamiento con tiamina (aunque demore 1 o 2 días) puede provocar una
recuperación parcial. Si se continúa el tratamiento por meses o años,
puede verse una mejoría incremental lenta con cierta amnesia
persistente. Si el tratamiento se retrasa 1-2 semanas, puede
comprometerse la recuperación parcial footnote:[Thomson AD, Guerrini I,
Marshall EJ (2012) The evolution and treatment of Korsakoff’s syndrome:
Out of sight, out of mind?Neuropsychol Rev. 22:81–92].

La memoria inemdiata en el SWK dura pocos minutos. Los detalles
relacionados a eventos recientes con componente emocional (por ejemplo
una tormenta eléctrica reciente) se pierden, aunque por condicionamiento
puede aparecer una respuesta emocional en relación al evento original.
Este déficit implica la imposiblidad de una vida autónoma. La falta de
conciencia de los eventos que llevan a la circunstancia actual implican
una falla en la resolución de problemas y en el juicio. El estado
emocional del paciente puede ir desde una indiferencia calma hasta la
conducta demandante e irritabilidad. La desinhibición puede precipitar
conductas violentas footnote:[Gerridzen IJ, Hertogh CM, Depla MF,
Veenhuizen RB, Vershuur EML, Joling KJ (2018) Neuropsychiatric symptoms
in people with Korsakoff syndrome and other alcohol-related cognitive
disorders living in specialized long-term care facilities: Prevalence,
severity, and associated caregiver distress. J Am Med Dir Assoc.
19:240–247.].

La memoria "arcaica" (eventos pre inicio del SWK) permanece accesible
(nombres, eventos, aritmética básica, lecto-escritura). Puede perderse
por falta de uso. Puede conservarse la realización de conductas
complejas (nadar, tipear, conducir) si se practican (memoria
procedural). Pueden continuar una actividad laboral en entornos
supervisados. Con cuidados adecuados la sobrevida es buena
footnote:[Sanvisens A, Zuluaga P, Fuster D, Rivas I, Tor J, Marcos M,
Chamorro AJ, Muga R (2017) Long-term mortality of patients with an
alcohol-related Wernicke-Korsakoff syndrome. Alcohol Alcohol.
52:466–471.].

.Funciones mnésicas en el SWK [ |=== |Categorías cronológicas
relacionadas con la memoria|Estado en el SWK |Memoria inmediata (hasta
varios minutos)|Intacta: luego de la fase aguda, el paciente funciona
normalmente en aspectos inmediatos del estado mental y en el examen
psicométrico |Memoria reciente (minutos-días) | Falla: se pierde la
memoria de episodios recientes y de episodios experimentados de forma
personal, así como reportados por otros. |Memoria remota: intermedia
(semanas-meses) y a largo plazo (años-décadas)| Intacta: se retienen
recuerdos pre inicio del SWK (experimentados o aprendidos de otros).
Esto se conoce como "memoria arcaica".

Falla: recuerdos posteriores al inicio del SWK (experiencia personal o
transmitida).

Intacta: memoria post inicio del SWK con contenido emocional,
dependiente del estado, somática (todo lo no-semántico o episódico).
|===

== Diagnóstico

El reconocimiento del SWK depende de tenerlo presente como diagnóstico
footnote:[Wijnia JW, Nieuwenhuis KG (2011) Difficulties in identifying
Wernicke-delirium. Eur J Intern Med. 22:e160–e161.]. Es necesario una
anamnesis que se remonte décadas atrás, un examen psiquiátrico que
contemple lo cognitivo, un examen neurolóico y el acceso a datos de
terceros. Es útil intentar provocar la confabulación (relatos imaginados
por el paciente para llenar lagunas mnésicas).

Descartar otros consumos de sustancias, trastornos del control de los
impulsos, trastornos de ansiedad, trastornos del humor.

== Diagnóstico diferencial

El SWK representa una de las posibles causas de amnesia vinculada a
alcohol y nutricionales. Estas patologías difieren en su fisiopatología,
signos, síntomas, curso y pronóstico.

- Amnesia transitoria, reversible ("blackout") que acompaña algunos
episodios de intoxicación. Revierte luego de algunas horas de
abstinencia. Puede ocurrir precozmente en el curso del alcoholismo. -
Pérdida de memoria asociada a disfunción ejecutiva y desinhibición
sugerente de atrofia del lóbulo temporal, que ocurre tardíamente en el
alcoholismo o bien por TEC. - Demencia progresiva, por atrofia
pan-cortical que puede asemejarse a una Enfermedad de Alzheimer, pero de
inicio más precoz. - Lesiones cerebrales localizadas secundaria a
complicaciones del alcoholismo (traumatismos, infección, cáncer,
patología vascular) - Deficiencias nutricionales (especialmente otras
formas de vitamina B, C o deficiencia proteica [pelagra, escorbuto])

Los medicamentos antipsicóticos, antidepresivos, ansiolíticos y usados
para el tratamiento de la demencia no provocan mejoría en los síntomas
nucleares del SWK. De todos modos se usan para tratamiento de
comorbilidades.

== Confabulación como adaptación

Los pacientes con SWK se habitúan a llenar los huecos de memoria
reciente y remota. Si se les pregunta por eventos del día anterior
inventados, responden apoyando la afirmación agregando información
inventada o percepciones sensoriales falsas. Con el tiempo cesa la
confabulación en la esfera sensorial, pero pueden continuar con la
conceptual a la hora de explicar eventos sobre los cuales tienen
amensia. Eventualmente pueden llegar a admitir que tienen un problema de
memoria. Si el entorno deja de preguntar por eventos que no puede
recordar, en general se detiene la conducta.

== Epidemiología Los estudios de mortalidad dependen de las autopsias en
las que se encuentra hemorragia en los cuerpos mamilares. Se plantea una
prevalencia de 1

== Desencadenantes En general se identifican como desencadenante el
agotamiento de las reservas de tiamina que resulta en una disfunción
mitocondrial, con deterioro de la oxidación celular y disminución de la
energía neuronal disponible. Desencadenantes comunes:

- abstinencia alcohólica severa (como el DT) - sepsis, neumonia,
infecciones urinarias footnote:[Wijnia JW, Oudman E, van Gool WA,
Wierdsma AI, Bresser EL, Bakker J, van de Wiel A, Mulder CL (2016)
Severe infections are common in thiamine deficiency and may be related
to cognitive outcomes: A cohort study of 68 patients with
Wernicke-Korsakoff syndrome. Psychosomatics. 57:624–633.] - falla
orgánica (páncreas, hígado, corazón, riñones) - trauma tisular (cirugía,
TEC, fracturas)

Se desconocen las vías por las cuales estos eventos agotan la tiamina.
La abstinencia de alcohol aumenta los niveles de cortisol
footnote:[Keedwell PA, Poon L, Papadopoulos AS, Marshall EJ, Checkley SA
(2001) Salivary cortisol measurements during a medically assisted
alcohol withdrawal. Addict Biol. 6:247–256.] que podría ser un mediador.

== Estudios de neuroimagen

PET: muestra hipometabolismo durante el SWK footnote:[Reed LJ, Lasserson
D, Marsden P, Stanhope N, Stevens T, Bello F, Kingsley D, Colchester A,
Kopelman MD (2003) FDG-PET findings in the Wernicke-Korsakoff syndrome.
Cortex. 39:1027–1045.] con hipermetabolismo en la sustancia blanca
cercana. Esto sugiere muerte celular en las áreas vinculadas a la
memoria reciente con actividad axonal compensatoria.

RNM volumétrica: muestra atrofia de los cuerpos mamilares, de otras
áreas talámicas, de lóbulos frontales y otras áreas footnote:[Sullivan
EV, Deshmukh A, Desmond JE, Lim KO, Pfefferbaum A (2000) Cerebellar
volume decline in normal aging, alcoholism, and Korsakoff’s syndrome:
Relation to ataxia. Neuropsychology. 14:341–352.] footnote:[Sullivan EV,
Pfefferbaum A (2009) Neuroimaging of the Wernicke-Korsakoff syndrome.
Alcohol Alcohol. 44:155–165.].

Pueden verse anmesias similares a la del SWK en otras afecciones:

- Lesiones cerebrales localizadas de etiología vascular footnote:[Rahme
R, Mousa R, Awada A, Ibrahim I, Ali Y, Maarrawi J, Rizk T, Nohra G,
Okais N, Samaha E (2007) Acute Korsakoff-like amnestic syndrome
resulting from left thalamic infarction following a right hippocampal
hemorrhage. AJNR Am J Neuroradiol. 28:759–760.], neoplásica footnote:[de
Falco A, De Simone M, Spitaleri D, de Falco FA (2018) Non-alcoholic
Wernicke-Korsakoff syndrome heralding non-Hodgkin lymphoma progression.
Neurol Sci. 39:1493–1495.] y traumáticas footnote:[Kahn EA, Crosby EC
(1972) Korsakoff’s syndrome associated with surgical lesions involving
the mammillary bodies. Neurology. 22:117–125.]. - Desnutrición asociada
caquexia por hambruna footnote:[DeWardener HE, Lennox B (1947) Cerebral
beriberi (Wernicke’s encephalopathy); Review of 52 cases in a Singapore
prisoner-of-war hospital. Lancet. 1:11–17.], pelagra, beriberi
footnote[Di Marco S, Pilati L, Brighina F, Fiero B, Cosentino G (2018)
Wernicke-Korsakoff syndrome complicated by subacute beriberi neuropathy
in an alcoholic patient. Clin Neurol Neurosurg. 164:1–4.] y ayuno de
causa psiquiátrica footnote:[Hargrave DD, Schroeder RW, Heinrichs RJ,
Baade LE (2015) Wernicke-Korsakoff syndrome as a consequence of
delusional food refusal: A case study. Cogn Behav Neurol. 28:215–219.].
- Malabsorción intestinal y alteración en fluidos por by-pass gástrico y
disfunción intestinal footnote:[Fandiño JN, Benchimol AK, Fandiño LN,
Barroso FL, Coutinho WF, Appolinário JC (2005) Eating avoidance disorder
and Wernicke-Korsakoff syndrome following gastric bypass: An
under-diagnosed association. Obes Surg. 15:1207–1210.], enfermedad
celíaca footnote:[Sahu M, Beal M, Chism K, Becker MA (2020)
Wernicke-Korsakoff syndrome in a patient with celiac disease and
obsessive-compulsive disorder: A case report. Psychosomatics.
61:375–378.], tratamiento excesivo con inhibidores de la bomba de
protones footnote:[Miyanaga R, Hisahara S, Ohhashi I, Yamamoto D,
Matsumura A, Suzuki S, Tanimoto K, Hirakawa M, Kawamata J, Kato J,
Shimohama S (2020) Hyperemesis-induced Wernicke-Korsakoff syndrome due
to hypergastrinemia during long-term treatment with proton pump
inhibitors. Intern Med. 59:2783–2787.], hiperemesis gravídica
footnote:[Ashraf VV, Prijesh J, Praveenkumar R, Saifudheen KJ (2016)
Wernicke’s encephalopathy due to hyperemesis gravidarum: Clinical and
magnetic resonance imaging characteristics. Postgrad Med. 62:260–263.] -
Cáncer con niveles séricos bajos de tiamno, baja ingesta, pérdida de
peso y afectación gastrointestinal o hematológica
footnote:[Isenberg-Grzeda E, Alici Y, Hatzouglou V, Nelson C, Breitbart
W (2016) Nonalcoholic thiamine-related encephalopathy
(Wernicke-Korsakoff syndrome) among inpatients with cancer: A series of
18 cases. Psychosomatics. 57:71–81.]

== Medios alternativos de aprendizaje

Alternative Means of Learning Intact Brain Functions The sentinel
learning deficit in WKS involves recall of events, also known as episode
amnesia (Pitel et al., 2009). These episodes or events fail to register
in short-term memory stores after WKS onset—a liability that prevents
the selective entry of new events and semantic information into
long-term memory. Therefore, before launching into extensive
rehabilitation, clinicians serving WKS patients obtain multidisciplinary
assessments to identify intact versus damaged brain structures and
functions. Depending on the patient, these assessments might include
consultations with neurology, neuroimaging, neuropsychology, primary
care, addiction psychiatry, addiction nursing, and psychosocial
rehabilitation (Van Dam et al., 2020). ``A WKS patient with extensive
frontal lobe vascular damage required 1 year of behavioral therapies to
address addictive behaviors besides AUD (e.g., pathological gambling,
online pornography, nicotine dependence). Another WKS patient with
earlier Agent Orange exposure had extensive basal ganglia lesions,
parkinsonian tremors, and parkinsonian-gait ataxia. He responded to
antiparkinsonian medications and physical therapy for his gait. Both
patients have since lived at home with their families for several
years.'' After adequate assessments have been completed, with strengths
and deficits identified, a treatment team can plan appropriate, often
staged interventions. The latter rely extensively on language-free
approaches, such as emotional arousal, state-dependent paradigms, and
other approaches that typically remain operational in WKS. Operant
Conditioning The link between a causal behavior and its consequential
effect underlies operant conditioning. Addiction processes follow the
principles of operant conditioning (Koob, 2017), which usually survives
WKS onset and can contribute to learning, adaptation, and recovery from
addiction. People with WKS rapidly learn the location of bathrooms in
buildings, heated areas in cold weather, and places to rest after
strenuous activity. Caregivers can foster operant learning by observing
what pleases the WKS patient. ``A WKS patient enjoyed the hospital
cafeteria where his quarterly clinic visits occurred. He could locate
the cafeteria from most areas of the building. His spouse could find him
in the cafeteria if they became separated during the day.'' Classical
Conditioning This method involves pairing a natural reward to a
desirable new behavior (O’Brien et al., 1992). The new behavior may be
desired by the patient, family, or caregiver. For example, breakfast may
be available for a reasonable period after a morning alarm, to establish
daily schedules and avoiding oversleeping, or an after-dinner treat for
clearing the table and helping to clean up can elicit participation in
household chores. ``A WKS patient who owned rental property had enjoyed
making repairs and upgrades to his property prior to WKS onset.
Post-WKS-onset, he started three complex projects, each of which led to
a large mess and expensive repairs when he could not complete them.
Subsequently, his spouse hired skilled workman to undertake challenging
projects. The WKS spouse happily served as an assistant in the process,
anticipating the tools and supplies that workmen needed and assisting
with clean-up. Paired with a teenaged grandson, the spouse was able to
undertake simpler, repetitive chores, such as repairing a fence or doing
gardening chores.'' Aversive Conditioning This approach involves
negative or unpleasant consequences linked to unhealthy or dangerous
behavior. For example, WKS patients, despite their grave disability, can
be amazingly persistent and creative in pursuing alcohol and other
addictions. Access to even small, infrequent volumes of alcohol can goad
WKS patients to devote time and ingenuity to this pursuit, with painful
consequences. ``Within weeks of onset, a WKS patient began creatively
collecting funds to purchase alcohol. He saved church and hospital Bingo
winnings, searched furniture cushions for loose change, took coins from
unattended purses, and spent a family coin collection. The attending
physician and the patient’s legal guardian (his spouse) agreed to
administer monitored disulfiram on a daily basis, beginning after they
informed the patient and providing him with written materials. Although
he agreed to the intervention, he forgot the details and tried drinking.
Since that single alcohol-disulfiram reaction, he has not attempted
alcohol use during the intervening decade.'' Metronidazole, an
antiprotozoal drug that produces a milder acetaldehyde reaction, can be
used in patients whose health contravenes disulfiram use. Ethical
analyses must be considered in aversive conditioning to ensure that the
goal is recovery and not punishment, with reasonable risk and equity
(Sullivan et al., 2008). Bioethical committees in clinical settings can
help in addressing these concerns and devising a humane conditioning
protocol. When caretakers fail to interrupt alcohol use, WKS patients
usually enter a crisis-ridden period ending in liver failure within a
few years. Contingency Contracting Contractual agreements can entail a
therapeutic exchange between a patient and a friend, relative, spouse,
or employer (Sullivan et al., 2008). For example, a family might shelter
an alcohol-addicted member willing to take monitored disulfiram daily.
The federal government can assign payment of federal pension funds
through a representative payee, who ensures that alcohol or drug
purchases do not replace expenditures for food, shelter, and clothes.
Errorless Learning Training so as to prevent learning errors has been
helpful in learning disabilities. This approach requires extra time and
nuance, but it reduces negative corrections and provides more pleasant
learning experiences. It has helped WKS patients with nonsemantic
learning (Rensen et al., 2019). Affective Recruitment Pairing affective
responses with successfully achieving learning objectives is key to this
approach. It does not favor new learning if the same positive outcome
occurs regardless of the patient’s behavior. Emotional experiences can
assist WKS patients in learning to distinguish categories (Labuddha et
al., 2010). Social network support for abstinence has facilitated
recovery in non-WKS AUD (Galanter et al., 1990) and appears therapeutic
for WKS patients. Schedules, Structures, and Keeping on Track WKS
patients retain the ability to read and comprehend written material,
despite inability to retain new semantic materials. The key lies in
enabling them to access an external data source when anxious or
confused. For example, providing a daily schedule can reduce caregiver
burdens imposed by repeated questions regarding ``what comes next.''
Bulletin boards, smart phones, or iPads can help patients implement a
daily plan. WKS survivors become motivated by rewarding outcomes when
checking the daily plan (e.g., obtaining lunch) and driven by negative
outcomes when not consulting them (e.g., missing lunch). These resources
can also help WKS patients manage unexpected problems (e.g., becoming
lost). Becoming lost comprises a common WKS problem, which caregivers
can address by using structure, schedules, and anticipation. The
following case exemplifies how some WKS patients become rigid homebodies
and how to reverse this dilemma. ``A man with recent-onset WKS walked
away from his family’s newly acquired residence. He wandered through the
night into a forested rural area. He was found several miles away from
home, dehydrated, with scratches and torn clothes. Although unable to
describe his experience, he subsequently became anxious away from home.
As a vehicular passenger on a shopping trip or clinic visit, he became
visibly agitated and shouted every several minutes `Where are we? Where
are we going?' Responses to these queries reassured him for some minutes
until the reassurance slipped from his immediate memory. The resolution
lay in providing him before each trip with 1) the destination and
rationale for the current trip and 2) a map with the route denoted. Over
time, these documents relieved his anxiety with assuring reorientations
to his location, the destination, and the purpose for the trip.'' The
following vignette, observed years apart in two patients from different
states, epitomizes the panicky ``flight'' scenario that can erupt in
lost WKS patients. ``Family caretakers of two employed WKS patients
eventually allowed them to drive alone to and from work, after having
ensured that they could drive safely along the same route. This system
worked for years until road repairs resulted in detours off the usual
route. Each man became lost but continued driving through the night
until they ran of fuel. The next day, police located each stranded man
over a hundred miles from home.'' Helping WKS patients to avoid becoming
lost requires strategic planning. The plan might involve a cell phone, a
list of instructions, or localizer-transmitters manufactured for
trekkers who might become lost. Caregivers can limit such crises by
considering how their WKS relative or patient might use their still
partially intact but amnestic brain to manage various problems, along
with access to printed materials and modern technology. Experienced
caregivers, once oriented to alternative learning principles, may
acquire dependable intuitions on such matters. Predictably, a
longitudinal study has shown that WKS patients do better in small-scale,
individualized, homey residences than in large, more impersonal
hospitals or boarding institutions (Cutting, 1978). Calendars and Smart
Phones Chronological and geographic aids have improved WKS patients’
management skills and functionality (de Joode et al., 2013; Lloyd et
al., 2019). Time, effort, training, and on-going technological support
are needed to achieve practical computer-based utility. Modern
technologies can facilitate the constant supervision so often needed,
while alleviating the spatial and temporal constraints that can restrict
WKS patients and their caregivers. Day Programs Attendance at day
programs can aid rehabilitation for AUD patients facing major life
changes (Favazza and Thompson, 1984). Day programs likewise enable WKS
patients to expand their daily routines, adapt to another place and
different activities, and reexpand their intimate social network back
toward normal (Westermeyer and Neider, 1988). These forays involve
trying out new emotion-challenging roles (e.g., reading a newspaper to
the group, preparing or serving a meal, leading chair exercises).
Programs range from 2 to 6 hours daily, and from one to several sessions
weekly. Our WKS patients have done well in day programs designed for
other diagnostic groups, such as Alzheimer dementia or Parkinson
disease. WKS patients can rely on other patients for recent memory
support, while contributing abilities that other patients lack. Day
programs can replicate the multigroup affiliation of intimate social
networks that are central to human well-being (Pattison, 1977) and to
AUD recovery (Gorden and Zrull, 1991). Programs also relieve primary
caregivers from constant supervisory duties and burnout. Adjunctive
Treatments Neural Transmission Rivastigmine, a cholinergic medication
beneficial in some dementias, has not been effective in a controlled
study of WKS patients (Luykx et al., 2008). Transcranial magnetic
stimulation has not been correlated with cholinergic activity in WKS
syndrome, suggesting that reduced choline does not cause WKS’s amnesia
(Nardone et al., 2010). Antidepressants and other medications can
relieve depression, anxiety, Parkinson disease, Alzheimer dementia,
psychosis, or insomnia associated with WKS, but they do not relieve
uncomplicated WKS amnesia. Alcoholics Anonymous Wernicke syndrome and
Korsakoff syndrome patients share certain core brain lesions, but they
do not share previous addiction. Familiarity with both Wernicke and
Korsakoff syndromes can abet clinicians who treat either disorder. Our
Wernicke cases consisted of refugees, combatants, and prisoners of war
encountered in Asia and Minnesota (Westermeyer, 1982; Westermeyer, 1989;
Williams and Westermeyer, 1986). By definition, Wernicke syndrome
patients do not typically require intervention for AUD. Therein lies an
enormous difference. Korsakoff syndrome patients can cathect readily to
AA groups. Using their intact archaic memory, they can identify with AA
members who have similar life experiences. AA affiliation can contribute
another group to the WKS patient’s recovery-oriented social network
(Hall and Nelson, 1996). Orienting the sponsor and the AA group to WKS
pathophysiology (see Table 1) helps to understand and relate to their
WKS member. Avoiding AUD Recurrence Some families and guardians
erroneously believe that memory losses erase addiction from the WKS
brain. Others aver that their relative ``deserves a drink now and then''
after years of sobriety. More malignant motivations may emerge if an
inheritance is involved. ``A married man continued working for several
years following onset of WKS syndrome. During that time, he received
monitored disulfiram treatment, but no AA or other recovery
interventions. When he reached retirement age, his wife and adult
offspring discussed his resuming alcohol use, believing that they could
limit his intake to one standard drink daily. Contrary to their
expectations, the patient began obsessing about alcohol and finding
means to obtain it. He died 2 years later from liver failure.'' ``A
single man was placed in an abstinence-oriented adult foster home
following diagnosis of WKS syndrome. The patient requested that his
court-appointed guardian transfer him to a program where he could resume
drinking. His guardian ignored clinical recommendations and approved
transfer to a `wet' setting, where the patient received a cash sum
weekly and was permitted to leave the premises to purchase beverage
alcohol. He resumed daily drinking and died within 1 year from bleeding
esophageal varices and liver failure.'' Courts handling WKS cases might
consider appointing two guardians, one for person and the other for
property, so that these interests can be separated, monitored, and
arbitrated when necessary. Courts can add convenances for vulnerable
adults at mortal risk to self and others if readdicted. Comorbid Brain
Conditions Additional brain lesions in WKS may ensue from falls, fights,
obstructive sleep apnea, alcohol-drug overdoses, disuse atrophy of
neglected brain centers, infections, and neoplasms. Among 63
hospitalized WKS patients, 13 (or 21 WKS Research Unique aspects of WKS
pathophysiology present opportunities for creative research. One team
compared two autobiographical interviewing methods to facilitate optimal
assessment in WKS versus controls (Rensen et al., 2017). The two methods
did not differ within the WKS subsample, although differences did exist
between WKS patients versus controls. Surgical decompression of
supracellar masses producing acute WKS syndromes in four patients
rapidly reversed the syndrome (Savastano et al., 2018), enhancing
knowledge regarding WKS pathophysiology. A translational rodent model
showed neuroanatomical substrates for memory loss resembling, although
not wholly replicating human WKS (Savage et al., 2012). A European
center found that WKS patients started on supplemental vitamin D within
the previous year had a higher cancer rate than other WKS patients at p
< 0.011 (Wijnia et al., 2019). Logistic regression analysis further
revealed that tobacco smoking and length of stay significantly increased
the odds ratios for cancer in WKS patients (respectively, odds ratio =
2.74 and 1.68). An in vitro study of cancer cells indicated that, after
hypoxic stress, supplemental thiamine increased cancer cell growth—an
effect that may theoretically be reversed by cell-permeable antioxidants
(Jonus et al., 2018). The ability to conduct ethical studies among large
numbers of WKS patients has begun to guide their treatment. Clinical and
research protocols increasingly use specific test batteries for WKS (see
Table 2). Some tests have shown minimal or no pathology in some WKS
cases; the Montreal Cognitive Assessment is an example. Such exploratory
work holds promise for improved understanding and care of WKS patients.
DISCUSSION Historical Changes Underdiagnosis of WKS poses a worldwide
problem today (Barata et al., 2020; Donnelly, 2017; Nikolakaros et al.,
2018; Sechi and Serra, 2007; Wijnia et al., 2014). The Australian
autopsy study suggests that 80 If the life-time WKS incidence were 1
Limitations, Implications, and Opportunities Without sufficient
epidemiological understanding, targeted health planning remains stymied.
Several health measures suggest a serious and evolving problem worldwide
in countries like ours. These data include increasing alcohol
consumption among middle-class people aged 50 to 70 years and case
reports of missed diagnoses in otherwise first-class medical facilities.
The stigma associated with AUD can sway many people toward secrecy even
when the diagnosis is known. Training in WKS prevention, early
diagnosis, and timely care needs to expand into the several disciplines
that nowadays provide acute health care for AUD patients, that is,
nursing, social work, psychology, physician assistants, police, and jail
guards. Within clinical services, instruction on WKS prevention and care
should involve emergency departments, consultation-liaison services,
anesthesiology, surgical specialties, infectious disease and
gastroenterology medicine, neurology, psychiatry, and addiction medicine
(Barata et al., 2020; Donnelly, 2017; Donnino et al., 2007). Perhaps
most heartrending, every new case of WKS syndrome creates a costly
tragedy that could have been prevented by timely administration of a
vitamin. ACKNOWLEDGMENT Brian A. Conn at the Minneapolis VAHCC library
greatly enhanced our literature search through his skills in accessing
special databases, international publications, and articles available
online but not yet in printed form. We also appreciate the perspectives
and experiences conveyed to us by families of our WKS patients.
DISCLOSURE The authors declare no conflict of interest.

REFERENCES Barata PC, Serrano R, Afonso H, Luís A, Maia T (2020)
Wernicke-Korsakoff syndrome: A case series in liaison psychiatry. Prim
Care Companion CNS Disord. 22:19br02538.[Context Link] Bermejo-Velasco
EB, Ruiz-Huete C (2006) Korsakoff’s syndrome secondary to left thalamic
bleeding. Neurologia. 21:733–736.[Context Link]

Blazer DG, Wu LT (2011) The epidemiology of alcohol use disorders and
subthreshold dependence in a middle-aged and elderly community sample.
Am J Geriatr Psychiatry. 19:685–694.[Context Link] Brion M, DeTimery P,
Mertens de Wilmars S, Maurage P (2018a) Impaired affective prosody
decoding in severe alcohol use disorder and Korsakoff syndrome.
Psychiatry Res. 264:404–406.[Context Link] Brion M, Dormal V, Lannoy S,
Mertens S, de Timary P, Maurage P (2018b) Imbalance between cognitive
systems in alcohol-dependence and Korsakoff syndrome: An exploration
using the alcohol flanker task. J Clin Exp Neuropsychol.
40:820–831.[Context Link] Brion M, Pitel AL, Beaunieux H, Maurage P
(2014) Revisiting the continuum hypothesis: Toward an in-depth
exploration of executive functions in Korsakoff syndrome. Front Hum
Neurosci. 8:498.[Context Link]

de Joode EA, van Boxtel MP, Hartjes P, Verhey FR, van Heugten CM (2013)
Use of an electronic cognitive aid by a person with Korsakoff syndrome.
Scand J Occup Ther. 20:446–453.[Context Link] Diener HC, Dichgans J,
Bacher M, Guschlbauer B (1984) Improvement of ataxia in alcoholic
cerebellar atrophy through alcohol abstinence. J Neurol.
231:258–262.[Context Link] Donnelly A (2017) Wernicke-Korsakoff
syndrome: Recognition and treatment. Nurs Stand. 31:46–53.[Context Link]
Donnino MW, Vega J, Miller J, Walsh M (2007) Myths and misconceptions of
Wernicke’s encephalopathy: What every emergency physician should know.
Ann Emerg Med. 50:715–721.[Context Link] El Haj M, Nandrino JL (2017)
Phenomenological characteristics of autobiographical memory in
Korsakoff’s syndrome. Conscious Cogn. 55:188–196.[Context Link]

Favazza AR, Thompson JJ (1984) Social networks of alcoholics: Some early
findings. Alcohol Clin Exp Res. 8:9–15.[Context Link] Galanter M,
Talbott D, Gallegos K, Rubenstone E (1990) Combined alcoholics anonymous
and professional care for addicted physicians. Am J Psychiatry.
147:64–68.[Context Link]

Gerridzen IJ, Hertogh CM, Joling KJ, Veenhuizen RB, Vershuur EM, Janssen
T, Depla MF (2021) Caregivers’ perspectives on good care for nursing
home residents with Korsakoff syndrome. Nurs Ethics. 28:358–371.[Context
Link] Gerridzen IJ, Joling KJ, Depla MF, Veenhuizen RB, Verschuur EML,
Twisk JWR, Hertogh CMPM (2019) Awareness and its relationships with
neuropsychiatric symptoms in people with Korsakoff syndrome or other
alcohol-related cognitive disorders living in specialized nursing homes.
Int J Geriatr Psychiatry. 34:836–845.[Context Link] Gorden AJ, Zrull M
(1991) Social networks and recovery: One year after inpatient treatment.
J Subst Abuse Treat. 8:143–152.[Context Link] Hall GB, Nelson G (1996)
Social networks, social support, personal empowerment, and the
adaptation of psychiatric consumers/survivors: Path analytic models. Soc
Sci Med. 43:1743–1754.[Context Link]

Harper C, Fornes P, Duyckaerts C, Lecomte D, Hauw JJ (1995) An
international perspective on the prevalence of the Wernicke-Korsakoff
syndrome. Metab Brain Dis. 10:17–24.[Context Link] Harper C, Gold J,
Rodriquez M, Perdices M (1989) The prevalence of the Wernicke-Korsakoff
syndrome in Sydney, Australia: A prospective necropsy study. J Neurol
Neurosurg Psychiatry. 52:282–285.[Context Link]

Irving W (1819–1820) The sketch book. Chicago: Encyclopedia
Britannica.[Context Link]

Isenberg-Grzeda E, Kutner HE, Nicholson SE (2012)
Wernicke-Korsakoff-syndrome: Under-recognized and under-treated.
Psychosomatics. 53:507–516.[Context Link] Jonus HC, Hanberry BS, Khatu
S, Kim J, Luesch H, Dang LH, Bartlett MG, Zastre JA (2018) The adaptive
regulation of thiamine pyrophosphokinase-1 facilitates malignant growth
during supplemental thiamine conditions. Oncotarget.
9:35422–35438.[Context Link]

Kok AF (1991) Developments in the care of Korsakoff patients.
Tijdschrift voor Alcohol, Drugs, en Andere Psychotopic Stoffen.
17:3–9.[Context Link] Koob GF (2017) The dark side of addiction. J Nerv
Ment Dis. 205:270–272.[Context Link] Korsakoff SS (1889) Etude
medical-psychologique sur une forme des maladies de la memoire. Revue
Philosophie. 20:501–530.[Context Link] Labuddha K, von Rothkrech N,
Pawlikowski M, Laier C, Brand M (2010) Categorization abilities for
emotional and nonemotional stimuli in patients with alcohol-related
Korsakoff syndrome. Cogn Behav Neurol. 23:89–97.[Context Link] Lloyd B,
Oudman E, Altgassen M, Postma A (2019) Smartwatch aids time-based
prospective memory in Korsakoff syndrome: A case study. Neurocase.
25:21–25.[Context Link] Luykx HJ, Dorresteijn LD, Haffmans PM,
Bonebakker A, Kerkmeer M, Hendriks VM (2008) Rivastigmine in
Wernicke-Korsakoff’s syndrome: Five patients with rivastigmine showed no
more improvement than five patients without rivastigmine. Alcohol
Alcohol. 43:70–72.[Context Link]

Nardone R, Bergmann J, De Blasi P, Kronbichler M, Kraus J, Caleri F,
Tezzon F, Ladurner G, Golaszewski S (2010) Cholinergic dysfunction and
amnesia in patients with Wernicke-Korsakoff syndrome: A transcranial
magnetic stimulation study. J Neural Transm (Vienna).
117:385–391.[Context Link] Nikolakaros G, Kurki T, Paju J, Papageorgiou
SG, Vataja R, Ilonen T (2018) Korsakoff syndrome in non-alcoholic
psychiatric patients. Variable cognitive presentation and impaired
frontotemporal connectivity. Front Psychiatry. 31:204.[Context Link]
Nikolakaros GT, Kurki T, Myilymäki A, Ilonen T (2019) A patient with
Korsakoff syndrome of psychiatric and alcoholic etiology presenting as
DSM-5 mild neurocognitive disorder. Neuropsychiatr Dis Treat.
15:1311–1320.[Context Link] O’Brien CP, Childress AR, McClellan AT,
Ehrman R (1992) Classical conditioning in drug-dependent humans. Ann N Y
Acad Sci. 654:400–415.[Context Link] Oslin DW, Cary MS (2003)
Alcohol-related dementia: Validation of diagnostic criteria. Am J
Geriatr Psychiatry. 11:441–447.[Context Link] Oudman E, Postma A, Van
der Stigchel S, Appelhof B, Wijnia JW, Nijboer TC (2014) The Montreal
Cognitive Assessment (MoCA) is superior to the mini mental state
examination (MMSE) in detection of Korsakoff’s syndrome. Clin
Neuropsychol. 28:1123–1132.[Context Link] Pattison EM (1977) Clinical
social systems interventions. Psychiatry Dig. 38:25–33.[Context Link]
Pitel AL, Beaunieux H, Guillery-Girard B, Witkowski T, de la Sayette V,
Viader F, Desgranges B, Eustache F (2009) How do Korsakoff patients
learn new concepts?Neuropsychologia. 47:879–886.[Context Link]

Rensen YCM, Egger JIM, Westhoff J, Walvoort SJW, Kessels RPC (2019) The
effect of errorless learning on psychotic and affective symptoms, as
well as aggression and apathy in patients with Korsakoff’s syndrome in
long-term care facilities. Int Psychogeriatr. 31:39–47.[Context Link]
Rensen YCM, Kessels RPC, Migo EM, Wester AJ, Eling PATM, Kopelman MD
(2017) Personal semantic and episodic autobiographical memories in
Korsakoff syndrome: A comparison of interview methods. J Clin Exp
Neuropsychol. 39:534–546.[Context Link]

Robin F, Moustafa M, El Haj M (2020) The image of memory: Relationship
between autobiographical memory and mental imagery in Korsakoff
syndrome. Appl Neuropsychol Adult. 1–7. doi:
10.1080/23279095.2020.1716759.[Context Link]

Savage LM, Hall JM, Resende LS (2012) Translational rodent models of
Korsakoff syndrome reveal the critical neuroanatomical substrates of
memory dysfunction and recovery. Neuropsychol Rev. 22:195–209.[Context
Link] Savastano LE, Hollon TC, Barkan AL, Sullivan SE (2018) Korsakoff
syndrome from retrochiasmatic suprasellar lesions: Rapid reversal after
relief of cerebral compression in 4 cases. J Neurosurg.
128:1731–1736.[Context Link]

Sullivan MA, Birkmayer F, Boyarsky BK, Frances RJ, Fromson JA, Galanter
M, Levin FR, Lewis C, Nace EP, Suchinsky RT, Tamerin JS, Tolliver B,
Westermeyer J (2008) Uses of coercion in addiction treatment: Clinical
aspects. Am J Addict. 17:36–47.[Context Link]

Van Dam MJ, Van Meijel B, Postma A, Oudman E (2020) Health problems and
care needs in patients with Korsakoff’s syndrome: A systematic review. J
Psychiatr Ment Health Nurs. 27:460–481.[Context Link]

Visser PJ, Krabbendam L, Verhey FR, Hofman PA, Verhoeven WM, Tuinier S,
Wester A, Den Berg YW, Goessens LF, Werf YD, Jolles J (1999) Brain
correlates of memory dysfunction in alcoholic Korsakoff’s syndrome. J
Neurol Neurosurg Psychiatry. 67:774–778.[Context Link] Wernicke C (1881)
Die acute haemorrhagische poliencophalitis superior. Lehrbuch der
Gehirnkkrankheiten fur Aerzle und Studirende (Vol. 2–3, pp 229–242).
Berlin: Verlag von Theodor Fischer.[Context Link] Westermeyer J (1982)
Poppies, pipes, and people: Opium and its use in Laos. Berkeley:
University of California Press.[Context Link] Westermeyer J (1989)
Psychiatric care of migrants: A clinical guide. Washington: American
Psychiatric Press.[Context Link] Westermeyer J, Neider J (1988) Social
networks and psychopathology among substance abusers. Am J Psychiatry.
145:1265–1269.[Context Link]

Wijnia JW, Oudman E, Bresser EL, Gerridzen IJ, van de Wiel A, Beuman C,
Mulder CL (2014) Need for early diagnosis of mental and mobility changes
in Wernicke encephalopathy. Cogn Behav Neurol. 27:215–221.[Context Link]

Wijnia JW, Oudman E, Wierdsma AI, Oey MJ, Bongers J, Postma A (2019)
Vitamin D supplementation after malnutrition associated with
time-related increase of cancer diagnoses: A cohort study of 389
patients with Wernicke-Korsakoff syndrome. Nutrition.
66:166–172.[Context Link] Williams CL, Westermeyer J (Eds) (1986)
Refugee mental health in resettlement countries. Series in clinical and
community psychology. Washington: Hemisphere Publishing Corp.[Context
Link] Wong A, Moriarity K, Crompton S (2007) Wernicke-Korsakoff
syndrome: Who cares?Gastroenterology Today. 17:46–49.[Context Link]
