== Trastornos por consumo de opioides

=== Notas clínicas

==== Evaluación del Trastorno por consumo de opioides

Descartar otros trastorno psiquiátricos. Descartar otros consumos de
sustancias actuales y previos. En caso de comorbilidad con otros
consumos, considerar el tratamiento en nivel superior de atención.

==== Recomendaciones diagnósticas

Confirmar diagnóstico (a pesar de que venga con diagnóstico hecho).

=== Encare

==== Paraclínica

===== Biológico

Primer paso: identificar cualquier trastorno médico o psiquiátrico que
requiera tratamiento de urgencia y hacer la derivación adecuada (por
ejemplo: intoxicación son sobredosis).

HC completa con evaluación de toda condición médica incluyendo las
infecciosas (hepatitis, HIV, tuberculosis), traumatismos, embarazo.
Examen físico.

* Hemograma completo
* Funcional y enzimograma hepático
* Serología de hepatitis
* HIV y VDRL
* beta HCG
* tóxicos en orina

===== Psicológico

Pueden usarse escalas validadas: OOWS (Objective Opioid Withdrawal
Scale), SOWS (Subjective Opioid Withdrawal Scale), COWS (Clinical Opioid
Withdrawal Scale).

===== Social

Evaluación de barreras de acceso al tratamiento, en especial
farmcológico. Obtención de consentimiento informado para el tratamiento
(donde consten aspectos vinculados a riesgos de recaida y otros riesgos
vinculados a la retirada gradual como único tratamiento).

==== Tratamiento

Encuadre: adicción como enfermedad bio-psico-social-espiritual. El
tratamiento debe ser una decisión compartida con el paciente. Debe
contemplarse la preferencia del paciente, y la efectividad de
tratamientos previos. Elegir el nivel de tratamiento:

* Ambulatorio (OBOT: Office Based Opioid Treatment)
* Internación: considerarlo si hay comorbilidad con otros trastornos por
consumo de sustancias (alcohol, sedantes, hipnóticos). Considerarlo aún
en conexto de consumo que parezca no problemático.
* Centro de rehabilitación especializado en adicciones

Alternativas footnote:[*Kampman K, Jarvis M. American Society of
Addiction Medicine (ASAM) National Practice Guideline for the Use of
Medications in the Treatment of Addiction Involving Opioid Use. J Addict
Med. 2015;9(5):358-367. doi:10.1097/ADM.0000000000000166 ]: *
Buprenorfina: primera línea * Metadona: pacientes bajo supervisión o con
falla de tratamiento con buprenorfina. Contexto: internación. *
Naltrexona: generalmente tiene escasa adherencia. Reservado para
pacientes que pueden cumplir.

WARNING: la retirada controlada del opioide como única estrategia no se
considera un tratamiento válido.

En opiodes de acción corta, se pueden usar dosis decrecientes diarias de
la metadona comenzando con 20-30 mg x día completando la retirada en
6-10 días.

Se recomienda la inclusión de clonidina como coadyuvante para la
abstinencia de opioides. No está aprobada por la FDA, pero su uso es
extendido: v/o 0.1-0-3 mg c/ 6-7 horas con un máximo de 1.2 mg/día. Debe
vigilarse la hipotensión.

Otros fármacos: benzodiacepinas (ansiedad), loperamida (diarrea),
acetaminofeno o AINEs (dolor), ondansetron (náuseas).

.Metadona Tratamiento recomendado para pacientes con dependencia
fisiológica de opioides, con capacidad de dar consentimiento y que no
tienen contraindicaciones específicas para el tratamiento con agonistas
en el contexto de un plan apropiado que incluya intervenciones
psicosociales.

Dosis inicial: 10-30 mg con evaluación en 3-4 horas y una eventual
segunda dosis no superior a los 10 mg el primera día si persisten los
síntomas de abstinencia. Dosis habitual: 60-120 mg con aumentos de 5-10
mg cada 7 días según respuesta clínica (para evitar sobresedación,
toxicidad iatrogénicas). No hay un límite recomendado en el tiempo de
tratamiento. Debe monitorizarse la administración de la medicación hasta
que clínicamente sea apropiado prescribir sin monitorización.

Falta de eficacia: considerar buprenorfina. Primero se debe bajar la
dosis de metadona si la dosis es superior a 40 mg/día.

Cambio a naltrexona: primero debe retirarse por completo la metadona y
otros opioides ANTES de recibir naltrexona (esto puede llevar 14 días)
-> contexto de instalación especializada.

.Buprenorfina Con la buprenorfina: el paciente debe esperar a presentar
síntomas de abstinencia leves a moderados antes de tomar la primera
dosis de buprenorfina para reducir el riesgo de precipitación de la
abstinencia.

Inducción: comenzar con 2-4 mg, con aumentos de a 2-4 mg
(preferentemente en contexto hospitalario).

Luego de que se establece la buena tolerancia de la dosis inicial, puede
aumentarse de forma rápida a dosis que sean eficaces para 24 horas (de a
8 mg x día). Máximo: 24 mg/día.

Luego del alta: controles semanales al inicio. Prescripción de
cantidades controladas de comprimidos.

Discontinuación: lenta, de duración indefinida y con controles
frecuentes (aún después de la suspensión). Duración: meses.

Cambio a naltrexona: debe mediar un lapso de 7-14 días SIN buprenorfina
antes de empezar con Naltrexona (no debe haber dependencia). Puede hacer
un test de dosis inicial para comprobar que no haya dependencia física.

Cambio a metadona: sin interrupción. La adición de un agonista completao
a un agonista parcial en general no da reacciones adversas.

.Naltrexona Se recomienda para la prevención de recaídas de un TCO.

===== Otros Durante el tratamiento: test de tóxicos en orina. Ofrecer
vacunación para hepatitis. Ofrecer asesoramiento y tratamiento para
cesación de tabaco.

===== Psicosocial

Orientación y apoyo con énfasis en mantener el cumplimiento luego del
alta (pacientes que no tienen seguimiento recaen con más frecuencia).

Contactar con grupos de apoyo para pacientes y familiares.

Paciente y familiares deben recibir psicoeducación en cuanto a riesgo de
sobredosis si retoma el uso de opioides luego del tratamiento. En
Uruguay solo hay v/o. Dosis: 50 mg x dia (350 mg x semana) o repartido
en la semana en 3 tomas (100, 100, 150). No hay una duración de
tratamiento recomendad. No hay dependencia física. Se puede suspender de
forma abrupta.

Cambio a metadone o buprenorfina: planificado (no antes de 24 horas
libre de medicación en la VO). En general menos complejo que el cambio
inverso. La dosis inicial de buprenorfina o metadona pueden ser más
bajas (al no haber dependencia física).

===== Poblaciones especiales

.Mujeres Embarazo: si hay dependencia física deben recibir metadona o
buprenorfina y no solo retiro de medicación con manejo de abstinencia.
Debe comenzarse el tratamiento de forma precoz en el embarazo. Se
recomienda hospitalización, en especial en el primer trimestre.

Metadona: en internación, 20-30 mg, sin exceder los 40 mg en el primer
día. Dosis incrementales de 5-10 mg cada 3-6 horas según sea necesario
para tratar la abstinencia. El emabrazo afecta la farmacocinética de la
metadona. A medida que avanza la edad gestacional los niveles de
metadona bajan (aumenta el clearance). Puede requerir aumento de dosis
y/o la frecuencia (en 2 tomas es más efectivo y tiene menos efectos
secundarios).

Buprenorfina (alternativa a la metadona): comenzar cuando hayan sintomas
de abstinencia leves-moderados, antes de que sean severos (6 horas
aproximadamente luego de la última dosis de un opiode de acción corta y
24-48 horas luego de un opioide de acción prolongada). Se recomienda
hospitalización. Luego de la inducción aumentos de 5-10 mg x semana. No
requiere de ajuste de dosis. No se recomienda la discontinuación antes
de una cesárea electiva ya que aumenta el riesgo de abstinencia fetal.

Debe incluirse a obstetra en el equipo.

Embarazo durante el tratamiento con naltrexona: discontinuarla. Puede
continuarse si hay alto riesgo de recaída y con consentimiento
informado.

Lactancia: se recomienda estimular la lactancia durante el tratamiento
con metadona o buprenorfina.

.Dolor

En los pacientes con dolor es importante contar con un correcto
diagnóstico y que se identifiquen alternativas de tratamiento
(acetaminofeno, AINEs).

Metadona: los pacientes pueden requerir dosis adicionales de opioides
además de la dosis diaria de matadona para el manejo del dolor agudo
severo. Pueden requerir opioides de acción corta adicionales para el
manejo del dolor postoperatorio.

Buprenorfina: se peude aumentar transitoriamente para el dolor moderado
agudo. Para el dolor severo agudo se recomienda discontinuar
buprenorfina y comenzar con un opioide alta potencia (como fentanil).
Debe controlarse al paciente para evaluar si necesita intervenciones
adicionales (tales como anestesia regional). La decisión de discontinuar
la buprenorfina antes de una cirugía electiva debe ser hecha en conjunto
con anestesista. De hacerlo debe ser 24-36 horas antes de la cirugía
recomenzando en el postoperatorio luego de que no se necesite analgesia
con agonistas opioides postoperatoria.

Naltrexona: los pacientes con naltrexona no responen a la analgesia con
opioides del modo usual. Se recomienza usar AINEs para dolor leve y
ketorolac por períodos cortos en dolor moderado-severo. La naltrexona
oral debe discontinuarse 72 horas antes de una cirugía.

.Adolescentes Buprenofrina está aprobado para >= 16 años.

.Comorbilidad psiquiátrica Evaluar existencia de riesgo suicida.
Controlar de forma más estricta a pacientes con antecedentes de IAEs.

.Población carcelaria Se recomienda tratamiento de forma independiente
de la duración de la sentencia. Debe iniciarse la farmacoterpia al menos
30 días antes de la salida de prisión.

.Sobredosis En caso de sobredosis debe adminstrarse naloxona (indicado
también en embarazadas con sobredosis). Se recomienda psicoeducación a
familiares en el manejo de la naloxona y dar prescripciones con
indicaciones de administración en caso de sobredosis.

=== Bibliografía * Nielsen, S., Larance, B., & Lintzeris, N. (2017).
Opioid agonist treatment for patients with dependence on prescription
opioids. Jama, 317(9), 967-968. * Nielsen, S., Larance, B., Degenhardt,
L., Gowing, L., Kehler, C., & Lintzeris, N. (2016). Opioid agonist
treatment for pharmaceutical opioid dependent people. Cochrane Database
of Systematic Reviews, (5). * Center for Substance Abuse Treatment.
Medication-Assisted Treatment for Opioid Addiction in Opioid Treatment
Programs. Rockville (MD): Substance Abuse and Mental Health Services
Administration (US); 2005. * Veilleux, J. C., Colvin, P. J., Anderson,
J., York, C., & Heinz, A. J. (2010). A review of opioid dependence
treatment: pharmacological and psychosocial interventions to treat
opioid addiction. Clinical psychology review, 30(2), 155-166.
