== Depresión

=== Notas clínicas

==== Depresión en el adulto mayor

Es un constructo clínicamente útilfootnote:[Agüera-Ortiz, L.,
Claver-Martín, M. D., Franco-Fernández, M. D., López-Álvarez, J.,
Martín-Carrasco, M., Ramos-García, M. I., & Sánchez-Pérez, M. (2020).
Depression in the Elderly. consensus statement of the Spanish
Psychogeriatric Association. Frontiers in psychiatry, 11, 380.]. Otros
conceptos clínicos útiles: depresión de inicio tardío, depresión de
causa vascular. Depresión en el adulto mayor:

* Mayores niveles de ansiedad.
* Mayores niveles de síntomas hipocondríacos
* Más asociado a ideación suicida
* Más impacto en el funcionamiento.
* Asociado a transición de autonomía a dependencia
* La demencia es un factor de riesgo significativo
* Las enfermedades somáticas graves son un factor de riesgo
significativo para el suicidio en varones más que en mujeres
* Tratamiento de primera línea: ISRS. Realizar antes rutinas y ECG.
Considerar duales. La latencia del antidepresivo es mayor que en los más
jóvenes.
* Si hay síntomas psicóticos, hay mayor riesgo de demencia y de
suicidio.

Depresión psicótica en adultos mayores: antidepresivos (duales) +
antipsicóticos. Segunda línea: ECT. Mantenimiento: si respondió a ECT ->
ECT de mantenimiento + fármacos. Se sugiere no usar litio, ni mantener
los antipsicóticos durante el mismo lapso que los antidepresivos. Los
antidepresivos son eficaces para el tratamiento de la depresión en
pacientes con demencia. Depresión vascular y depresión en demencia:
puede usarse ECT.

.Recomendaciones según situación clínica

[options="header"] |================== |Situación|1ª línea | 2ª línea |
Evitar |Cardiopatía isquémica | SERT, AGOM | DESV, VENL, FLUV, VORT,
MIRT|CITA, ESCI, REBO, NORT |Arritmias|SERT, AGOM|DESV, FLUO, FLUV,
VORT, MIRT|CITA, ESCI, REBO, NORT, BUPR |Hipertensión|SERT, AGOM|CITA,
ESCI, FLUO, FLUV, PARO, VORT, MIRT|VENL |Anticoagulación| |DESV, VENL,
DULO, SERT, CITA, ESCI, MIRT, BUPR, AGOM, VORT| |Diabetes|| DESV, VENL,
DULO, FLUO, SERT, CITA, ESCI, AGOM, VORT, BUPR, REBO| |Dislipidemia| |
FLUO, SERT, CITA, ESCI, DULO, BUPR, VORT, AGOM| |Obesidad| FLUO, BUPR,
AGOM | DESV, VENL, DULO, CITA, ESCI, FLUV, SERT, VORT, REBO | MIRT
|Adelgazamiento, anorexia| MIRT | DESV, VENL, DULO, PARO, SERT, CITA,
ESCI, NORT | FLUO |Constipación| | FLUO, FLUV, SERT, CITA, ESCI, BUPR,
AGOM, VORT | |Hemorragia digestiva | | DESV, VENL, MIRT, BUPR, NORT |
FLUO, CITA, ESCI |Hiponatremia| | DESV, VENL, DULO, MIRT, BUPR, AGOM,
VORT|FLUO, CITA, ESCI |Mareos|BUPR|DESV, VENL, FLUO, SERT, CITA, ESCI,
REBO, AGOM, VORT| MIRT |Caídas| | DESV, VENL, DULO, FLUO, SERT, CITA,
ESCI, BUPR, VORT|NORT |Alcoholismo| |DESV, VENL, DULO, FLUO, PARO, SERT,
CITA, ESCI, MIRT, BUPR, VORT| |Disfunción sexual| AGOM, BUPR, MIRT |
REBO VORT | FLUO PARO |Glaucoma| | DESV, SERT, CITA, ESCI, BUPR, AGOM,
VORT, TIAN|NORT, VENL |Convulsiones | | MIRT | NORT, BUPR |ACV| | DESV,
SERT, CITA, ESCI, AGOM, VORT, MIRT | |Parkinson | BUPR | DESV, VENL,
DULO, SERT, AGOM, VORT, MIRT, TIAN| |Demencia| | DESV, VENL, DULO, SERT,
CITA, ESCI, BUPR, AGOM, VORT, MIRT | NORT |Dolor| DULO, DESV, VENL |
NORT | |==================

.Algoritmo Resistencia al tratamiento:

. Escalar dosis . Cambio de antidepresivo . Combinación de AD .
Potenciación con antipsicótico o con lamotrigina . Potenciación con
litio . Potenciación con un agonista dopaminérgico o metilfenidato

==== Depresión en adolescentes

- Escitalopram footnote:[EMSLIE, Graham J., et al. Escitalopram in the
treatment of adolescent depression: a randomized placebo-controlled
multisite trial. Journal of the American Academy of Child & Adolescent
Psychiatry, 2009, vol. 48, no 7, p. 721-729.]] footnote:[FINDLING,
Robert L.; ROBB, Adelaide; BOSE, Anjana. Escitalopram in the treatment
of adolescent depression: a randomized, double-blind, placebo-controlled
extension trial. Journal of child and adolescent psychopharmacology,
2013, vol. 23, no 7, p. 468-480.]

=== Encare

==== En suma

Paciente de X años, procedente de MSEC X, con AF de trastornos afectivos
/ alcoholismo / suicidio, con AP de X, que es traído por una cuadro
centrado en la esfera afectiva.

==== Agrupación sindromática

===== Síndrome depresivo

De inicio insidioso / permanente, de X evolución, que centra el cuadro
clínico, dado por alteraciones en: el humor y afectividad ,
psicomotricidad, pensamiento, conductas basales y pragmatismos

.Humor y afectividad Trastorno que centra el cuadro y del cual nacen las
otras alteraciones. Está dado por un humor en menos cualitativamente
distinto a la tristeza normal. Está evidenciado por una tristeza vital y
profunda transcurso de la entrevista, monótona, que no responde a
estímulos externos, que no calma con la entrevista, con polo matinal de
peoría, con correlato en la presentación (facies triste, omega
melancólico), con deseos de llorar sin poder hacerlo o con llanto
intenso. Se acompaña de una anhedonia (pérdida de capacidad para sentir
placer con cosas que previamente eran gratas) tanto anticipatoria como
de consumación, con apatía (pérdida de interés), desánimo, desgano,
abulia (aburrimiento), abatimiento. En la afectividad se presenta un
afecto embotado que puede llegar a una anestesia afectiva: incapacidad
de querer, de sentir, por fuera del sufrimiento. Hipersensibilidad a
acontecimientos no placenteros con insensibilidad para acontecimientos
placenteros.

.Pensamiento En lo formal se destaca la bradipsiquia, percibida a través
de un relato de curso lento y pausado, con silencios prolongados, voz
tenue y monocorde, respuestas con latencia, asociaciones dificultosas,
evocaciones penosas, sensación de "mente en blanco" o embotamiento,
puede estar en mutismo o semimutismo. Caudal pobre. Frases monosilábicas

En el contenido destacamos la autodevaluación, con ideas de minusvalía
("no valgo nada", "soy un desgraciado", "soy menos"), ideas de culpa
excesiva, autoacusación, ideas de ruina (no ve salida, se percibe sin
futuro, no será perdonado, no puede esperar sino cosas malas), lo que
constituye el dolor moral. Puede llegar a constituir un síndrome
delirante.

TIP: Dolor moral: culpa, ruina, minusvalía.

Pueden existir ideas de muerte (desinterés por vivir), de
autoeliminación (deseo, plan y búsqueda), de indignidad, de
transformación corporal, elaboraciones hipocondríacas (temor y deseo de
enfermedad), elaboración paranoica.

Rumiación: ideación lenta centrada en temas tristes que se repiten
indefinidamente.

.Psicomotricidad Inhibición psicomotriz: definida como disminución
global de las fuerzas que orientan el campo de la conciencia, dado en:
Presentación:

* Presentación: abatimiento, postura encorvada, inmóvil, cabizbajo.
Descuido del aspecto personal, desaliño. * Actitud de colaboración
pasiva, disminución de iniciativa verbal. * FMYG: Pobreza gestual.
hipomimia, hipogestualidad. Rostro marmóreo. * Impresiona distante *
Inercia: disminución de movilidad espontánea, fatiga ("todo es un
esfuerzo"). * Clinofilia

TIP: AAAC: Apatía, Astenia, Anhedonia, Clinofilia

* Apatía: disminución de interés * Astenia: fatiga psíquica y física *
Anhedonia: incapacidad para obtener y experimentar placer (de intención
y/o realización) * Clinofilia

.Síntomas de subtipos de depresión: Dentro del síndrome depresivo, hay
una serie de síntomas que apuntan a un subgrupo de depresiones con
características diferenciales:

Síntomas melancólicos: marcada anhedonia Falta de reactividad al
entorno. Cualidad distintiva del estado de ánimo. Peoría matutina (polo
matinal de la depresión). Despertar precoz. Enlentecimiento o agitación
psicomotor. Anorexia significativa o pérdida de peso. Culpabilidad
excesiva o inapropiada.

Síntomas atípicos: reactividad del estado de ánimo al entorno Aumento
significativo de peso o del apetito. Hipersomnia. Abatimiento (parálisis
plúmbea) Patrón de larga duración de sensibilidad al rechazo
interpersonal (no limitado al episodio depresivo).

Síntomas catatónicos: inmovilidad motora con o sin catalepsia. Actividad
motora excesiva, sin propósito. Negativismo extremo. Peculiaridades del
movimiento voluntario (manierismos). Ecolalia o ecopraxia. Depresión
puerperal: inicio dentro de las primeras 4 semanas del postparto.

Patrón estacional: relación temporal sostenida entre el inicio de los
episodios afectivos y una determinada épica del año. Las remisiones
totales también se dan en de-terminada época del año.

Episodio mixto: humor excitado, disfórico, ira, agitación, ideación
suicida, mezcla con grandiosidad/hipersexualidad. Importante diferenciar
de depresión agitada.

TIP: Atención a la presencia de elementos mixtos. A veces se presentan
de forma tal que no es posible diferenciar episodios. En ese caso quizás
se debería hacer un Síndrome de alteración del humor y poner los
elementos de humor en más y en menos.

.Catalogar síndrome depresivo:

* X tiempo de evolución, con inicio brusco/insidioso * reactivo
(atípico) o no reactivo a estímulos externos * con ritmo circadiano
(polo matinal o no) * intensidad: leve, moderado, grave.

===== Síndrome de ansiedad-angustia

TIP: Ansiedad psicótica: MIDI.

Subsidiara al síndrome depresivo. Angustia MIDI (masiva, invasiva,
desestructurante, incompartible). Expresada sobre todo a nivel de la
psicomotricidad.

===== Síndrome delirante

En el cual las ideas melancólicas adquieren persistencia y convicción
delirante volviéndose incompartibles, irreductibles a la lógica y con
pérdida del juicio de la realidad quedando en primer plano.

.Temática De frustración, ruina, desgracia, de autodepreciación moral
(autoacusación), culpa, somática (transformación o negación corporal),
hipocondría, psíquica (dominación, pasividad Influencia). Puede haber un
Síndrome de Cotard completo/incompleto: forma mayor de melancolía (CINE:
condenación, inmortalidad, negación, enormidad). Negación: de la
existencia, del cuerpo, del mundo. Transformación corporal: creencia de
estar muerto, de ser un cadáver, de no tener órganos o de que éstos no
funcionan (combinación de nihilismo con megalomanía). Puede haber un
síndrome de influencia subsidiario. El contenido puede ser congruente
(culpa, ruina, hipocondría, humillación, influencia, etc.) o no
(persecutorio) con el estado de ánimo. Puede ser subdelirante / ideación
sobrevalorada (excesivas, inapropiadas, que admiten cierta crítica)
centrado en ideas de pérdida, disminución de autoestima, autorreproche,
culpa excesiva, pesimismo.

TIP: Cotard: condenación, inmortalidad, negación, enormidad (completo o
incompleto).

.Mecanismo Intuitivo, autorreferencial (delirante o subdelirante).

TIP: Características del delirio melancólico: ToMoPoPaDiR

Cumple con las características descritas por Seglas para el delirio
melancólico: tonalidad afectiva penosa , monotonía (reiterativo, fijo),
pobreza (más ricos en emoción que en contenido ideico, escaso desarrollo
temático), pasivas (el paciente acepta su desgracia como si se tratara
de una fatalidad, paciente indefenso), divergentes (se extienden a los
que lo rodean y al ambiente, con riesgo de homicidio piadoso), referidas
al pasado o al futuro (ruina).

===== Síndrome conductual

Dado por IAE (si ansiedad es elevada puede ser en contexto de excitación
psicomotriz). icon:directions[] Ver encare correspondiente.

Alteración de conductas basales: insomnio (destacar despertar precoz) o
hipersomnia (síntoma atípico), anorexia con adelgazamiento o hiperfagia
(síntoma atípico). Disminución del cuidado personal (vestimenta e
higiene). Disminución de la libido.

Alteración de las conductas complejas / pragmatismos. Disminución de la
libido, tendencia al aislamiento social. Abandono o descuido del
trabajo.

===== Síndrome de alteración de la conciencia

Desestructuración de conciencia de 1º nivel (ético-temporal) según lo
propuesto por Ey. Evidenciado por incapacidad del paciente de adaptar el
campo fenomenológico del ser consciente a las exigencias del aquí y
ahora. En general está BOTE (aunque en ocasiones no, por desinterés o
por inatención). Polarización por el estado de humor. Sensación
subjetiva de enlentecimiento del tiempo.

==== Síndrome de alteración cognitiva

TIP: no es un síndrome clásico, pero puede adecuarse más a la
comprensión actual de la sintomatología depresiva.

Pérdida de capacidad de concentración, olvidos. Déficit atencional.
Incapacidad para tomar decisiones.

TIP: recordar que no debería diagnosticarse demencia solamente con los
síntomas que aparecen dentro de un episodio depresivo.

==== Personalidad y nivel

icon:clipboard[] Ver Fragmentos: "Nivel en diferido"

Personalidad: rasgos X que nos evocan X rasgos del grupo Y.
Re-evaluaremos en la evolución pues el cuadro actual no permite un
diagnóstico preciso. Realizaremos entrevistas con terceros y de ser
necesario recurriremos a tests de personalidad. Podemos encontrar:
dificultad para superar frustraciones y adaptarse a situaciones
dolorosas de la vida yo débil, duelo patológico, dependencia, existir
depresivo.

==== Diagnóstico positivo

===== Nosografía clásica

Los clásicos clasificaban las depresiones de forma distinta al
DSM/CIE-10, con lo cual el encare "clásico" se adapta más a la depresión
melancólica. Para otros formatos, evaluar hacer diagnóstico por el
DSM/CIE.

.Diagnóstico del episodio

icon:clipboard[] Ver Fragmentos: "Psicosis"

icon:clipboard[] Ver Fragmentos: "Psicosis aguda"

Crisis de melancolía: por las características melancólicas del síndrome
depresivo ya analizado. Importa destacar desde ya el RIESGO VITAL del
diagnóstico establecido, basado en el riesgo de suicidio, ya que en la
melancolía la muerte es sentida como una obligación, castigo necesario y
solución para poner fin a la situación vivida. El riesgo está implícito
en el diagnóstico establecido ya que si bien a veces no manifiestan sus
ideas de muerte, la reticencia a manifestarlos es frecuente.

.Forma clínica

* Simple: IPM + poco DM ("con conciencia"). Predomina la IPM con
tendencia a la inacción, inercia, astenia. Dolor moral escaso o falta.
Tiene cierta conciencia mórbida (pero sin llegar a configurar una
depresión "neurótica" o "reactiva"). * Franca: IPM + DM (dolor moral).
Inicio progresivo con o sin desencadenante. * Estuporosa: gran IPM.
Paciente espontáneamente inmóvil, en mutismo, no come, no hace gestos,
reactividad disminuida (inhibición extrema con vigilia conservada).
Fascies marmóreo con expresión de dolor/desespero (facilita el DD con
otras etiologías). Riesgo de muerte por deshidratación/inanición. Ver
encare de "Estupor". * Ansiosa: inquietud , búsqueda de muerte: riesgo
de IAE. Cuadro dominado por agitación, ansiedad MIDI, psicomotricidad
aumentada (caminar, frotarse las manos, zapatear, moverse, gritar,
golpearse, correr, frotarse las manos, sollozar, gemir). * Delirante: Sº
depresivo + Sº delirante. * Estados mixtos: presencia simultánea o
rápidamente alternante de síntomas depresivos y síntomas de exaltación
del humor. Clínicamente: turbulencia, agitación, perplejidad,
irritabilidad / disforia.

.Diagnóstico nosológico

A. PMD unipolar: AF de cuadros afectivos o alcoholismo; AP de cuadros
similares con restitución ad-integrum. No existen episodios previos de
manía o hipo-manía B. PMD: similar, pero en la evolución presentó uno o
más episodios de exaltación del humor.

===== DSM-IV

.Diagnóstico del episodio

Para DSM IV: Episodio Depresivo Mayor + especificadores.

Especificadores principales:

* Gravedad: L/M/G * Con síntomas psicóticos: congruentes / incongruentes
con el estado de ánimo. * En remisión parcial / total (2 meses sin
síntomas)

TIP: Síntomas catatónicos: CINEMIA

Especificadores de síntomas catatónicos: 2 o + de 5 síntomas dominando
el cuadro (CINEMIA):

* Catalepsia / Inmovilidad motora: incluye flexibilidad cérea o estupor.
Inercia, actitudes de pasividad y automatismo (latencia en respuestas,
obediencia automática, sugestionabilidad) (CI). * Negativismo:
resistencia inmotivada a órdenes, mantenimiento de postura rígida ante
intentos de ser movido. Mutismo. Oposicionismo (al interrogatorio, a la
alimentación) (N) * Ecolalia / ecopraxia / estereotipias (actos motores
reiterativos / en el lenguaje: verbigeración)(E) * Manierismos:
tonalidad de afectación teatral, pudiendo llegar al pateticismo.
Sonrisas inmotivadas / posturas extrañas. (M) * Impulsiones (I). Actos
en cortocircuito, insensibles a estímulos externos, sobre los cuales el
paciente no puede dar cuenta. Pueden ser impulsiones verbales. *
Agitación motora: hiperactividad sin propósito aparente, no influida por
factores externos (A)

Especificadores de síntomas melancólicos:

A. Anhedonia y/o humor no reactivo B. 3 o + de 6: * Cualidad distintiva
del estado de ánimo. * Peoría matutina (polo matinal) * Depertar precoz
(2 horas antes de lo habitual) * Inhibición o agitación psicomotriz *
Anorexia significativa / pérdida de peso * Culpa excesiva o inapropiada

Especificadores de síntomas atípicos:

A. Humor reactivo B. 2 o + de 4 * Aumento de peso o apetito *
Hipersomnia * Abatimiento (pesadez plúmbea) * Patrón de larga duración
de sensibilidad al rechazo interpersonal (con afectación de
pragmatismos) C. Exclusión: síntomas melancólicos o síntomas
catatónicos.

Especificador de patrón estacional:

A. Relación temporal sostenido entre episodio afectivo y épica del año.
B. REmisión total o cambio de polaridad en determinada época del año. C.
En ultimos 2 años, 2 EDM con período estacional y NINGUN EDM fuera del
patrón. D. Lo EDM estacionales tienen que ser más numerosos que los no
estacionales.

Importante al plantear el tratamiento.

Otros especificadores:

* Crónico: > 2 años * Postparto: inicio < 4 semanas luego del parto *
Curso longitudinal: con o sin recuperación interepisódica total.

.Diagnóstico nosológico

TDM - TDM-R - TB I - TB II Cursando episodio actual X.

Trastorno Depresivo Recurrente: más jóvenes, puede estar precedido por
distimia (depresión doble). Mayor porcentaje de antecedentes familiares.
Importante realizar este diagnóstico por cambios al plantear
tratamiento.

==== Diagnósticos diferenciales

===== Nosografía clásica

. Depresión sintomática de un trastorno médico o consumo de sustancias.
Sobre todo en un primer episodio, si los síntomas son atípicos, cuando
la evolución no es la esperada, hay mala respuesta al tratamiento o los
hallazgos del EF nos hacen sospechar. .. Neoplasmas: genital, mamas,
cabeza de páncreas, pulmón. .. Fármacos: neurolépticos, reserpina,
alfametildopa, betabloqueantes, ACOs. .. UISP: OH, BZD, anfetaminas /
cocaína. Depende de tipo: abstinencia, intoxicación, dependencia, abuso.
.. Endócrino: hipotiroidismo, encefalopatía hepática, efermedad de
Addison, diabetes. .. Neurológico: enfermedad de Parkinson . Depresión
reactiva: previamente llamada "Depresión Neurótica". Cuadro más leve,
con humor reactivo, mejora con el contacto de la entrevista, oscila,
permite vibrar con el relato, se establece mejor rapport, pedido de
ayuda, sin síntomas psicóticos, sin dolor moral. Está ligada a
acontecimientos vitales. . Otras psicosis agudas: .. Otras formas
clínicas de melancolía: franca/simple/ansiosa/estuporosa/delirante. ..
Manía (en caso de estados mixtos). Si bien comparte el nivel de
desestructuración de la conciencia, la clínica es opuesta a la
depresiva. .. PDA (en caso de melancolía delirante). En la melancolía la
experiencia delirante es secundaria al estado de ánimo. No hay
polimorfismo. El nivel de desestructuración de la conciencia es menor.
.. Confusión Mental: descartado, pues el paciente está BOTE. . Psicosis
crónicas .. Depresión como debut clínico de Demencia. Tienen el común
algunos síntomas cognitivos (atencionales, memoria a corto plazo,
bradipsiquia, indiferencia al entorno). Pero nos aleja del diferencial
la presencia de AF y AF afectivos, ausencia de AP de trastornos de las
funciones instrumentales, simbólicas y psíquicas superiores. ..
Esquizofrenia: lo descartamos por no haber clínicamente un síndrome
disociativo-discordante, ni un existir autista, ni alteración de los
pragmatismos fuera del episodio. La inhibición psicomotriz y la
indiferencia pensamos que son secundarias al cuadro afectivo. ..
Depresión en una Paranoia (cuando hay delirio incongruente con el estado
de ánimo): en la depresión el delirio carece de continuidad con la
personalidad y carece de la estructura paranoica típica. El orden
temporal en la depresión es primero el síntoma afectivo y luego el
delirio.

===== DSM/CIE

. Causa orgánica de depresión: .. Endócrina: hipotiroidismo, Cushing,
Addison .. Metabólica. .. Tumorales: cabeza pancreática y cerebrales ..
Fármacos y drogas: antihipertensivos, ß bloqueantes, ACO, fenotiazinas,
benzodiacepinas .. Infecciones: mononucleosis, neurolúes, HIV 2. Inicio
de deterioro demencial (en pacientes > 65 años) . Cuadros Delirantes: •
Agudo: PDA, confusión. • Crónico: delirios crónicos: AP. . Estupor: ..
Confusiónal: organicidad, elementos de infección, oscilación rápida
estupor-agitación, no existe catalepsia .. Catatónico de origen
esquizofrénico: precedido de SDD, MC es absurdo/impulsivo .. Histérico .
Ansiosas: diferencial con neurosis.

==== Diagnóstico etiopatogénico y psicopatológico

===== Etiopatogenia

Se postulan 3 factores que interactúan en la patogénesis de la depresión
footnote:[]: * Factores internalizantes: por ejemplo genética y
neuroticismo footnote:[Sullivan, P.F., Neale, M.C., Kendler, K.S., 2000.
Genetic epidemiology of major depression: review and meta-analysis. Am J
Psychiatry 157, 1552–1562. https:// 10.1176/appi.ajp.157.10.1552.]. *
Factores externalizantes: por ejemplo consumo de sustancias
footnote:[Compton, W.M., Conway, K.P., Stinson, F.S., Grant, B.F., 2006.
Changes in the prevalence of major depression and comorbid substance use
disorders in the United States between 1991-1992 and 2001-2002. Am J
Psychiatry 163, 2141–2147. https://10.1176/ajp.2006.163.12.2141. ]. *
Eventos adversos: por ejemplo trauma y pérdida parental footnote:[Green,
J.G., McLaughlin, K.A., Berglund, P.A., Gruber, M.J., Sampson, N.A.,
Zaslavsky, A.M., Kessler, R.C., 2010. Childhood adversities and adult
psychiatric disorders in the national comorbidity survey replication I:
associations with first onset of DSM-IV disorders. Arch Gen Psychiatry
67, 113–123. https://10.1001/arch genpsychiatry.2009.186.].

.Biológico * Hereditario: importante penetrancia genética. *
Neurotransmisores: alteración en sistemas noradrenérgicos y/o
serotoninérgicos en SNC, basado en criterios farmacológicos. *
Neuroendócrinos: alteraciones en niveles de cortisol con alteraciones a
nivel del eje HHSR e Hipófiso-tiroideo. * Edad: disminución de defensas
psicológicas + factores biológicos: * Embarazo/parto, climaterio. *
Mecanismos inflamatorios: factor de necrosis tumoral alfa(TNF-alfa),
interleuquinas. Se postula que la inflamación podría alterar la barrera
hematoencefálica con entrada de moléculas inflamatorias y células
inmunes del CNS footnote:[Lee, C.H., Giuliani, F., 2019. The Role of
Inflammation in Depression and Fatigue. Front Immunol 10, 1696.
https://10.3389/fimmu.2019.01696.].

.Comprensión psicológica

Puede encontrarse dificultad para superar pérdidas y para adaptarse a
situaciones nuevas. Sobre un terreno de vulnerabilidad (personalidad
dependiente, poca autonomía) actúan factores psicosociales: pérdidas,
dificultades interpersonales.

Hay etapas vitales con mayor riesgo de presentación de sintomatología
depresiva: adolescencia, embarazo, puerperio, climaterio, menopausia,
envejecimineto, duelo. Se reviven en la esfera inconsciente pérdidas y
abandonos tempranos reales o imaginarios.

.Comprensión social

Estresores sociales como factor exterior sobre la vulnerabilidad de
base. Pérdida de roles laborales, pérdida de posición social.

===== Psicopatología

.Psicoanálisis Para la depresión esta teoría se basa en las relaciones
ambivalentes de objeto. Este objeto perdido en etapas tempranas del
desarrollo psicológico (amado y odiado al mismo tiempo) es
posterior-mente introyectado. Las pérdidas de la vida adulta (reales,
temidas o fantaseadas) reactivan este proceso volcando la libido y la
agresividad hacia el interior, donde se encuentra este objeto
introyectado, lo que desencadena una lucha autodestructiva del Yo con un
Superyó sádico que se manifiesta como depresión.

.Teoría organodinámica (Ey)

Estructura positiva y negativa:

* Negativa: pérdida de adaptación a las exigencias del presente con
falta de proyección al futuro. El sujeto se halla inmerso en el pasado.
* Positiva: contiene la producción subdelirante.

Binswanger y Ey insistieron en la estructura temporal (tiempo subjetivo)
de la melancolía (según TOD: 1º nivel de desestructuración de la
conciencia o ético-temporal) en la cual el sujeto está anclado en la
fatalidad del pasado y para quien el tiempo es una perspectiva de
muerte, lo que nos muestra una incapacidad de adaptación a las
exigencias del presente. Lo ético está vinculado a la incapacidad de
separarse de la culpa y lo temporal por la incapacidad de proyectarse al
futuro si no es desde una perspectiva de dolor.

.Teoría cognitivo-comportamental

Basado en el planteo de Beck de la tríada cognitiva de la depresión:
visión peyorativa de sí mismo, del futuro y del mundo.

==== Paraclínica

El diagnóstico es clínico. Se solicitará paraclínica de valoración
general, para descartar diferenciales, descartar comorbilidad, con
vistas al tratamiento y a evaluar aspectos biológicos de la depresión.

Se solicitará desde un punto de vista integral: biológico, psicológico y
social.

===== Biológico

Luego de una valoración clínica general del paciente y según hallazgos:

* Consulta con especialistas según hallazgos clínicos. * Interconsulta
con cardiólogo en caso de plantearse tratamiento con AP con potencial
alteración del intervalo QT. * Estudios imagenológicos, según la
clínica: TAC, RNM, SPECT, PET. * Rutinas: hemograma, glicemia,
ionograma, función renal, funcional y enzimograma hepático, HIV, VDRL. *
Dosificación de drogas en sangre y orina * Estudio de hormonas
tiroideas: T3, T4 y TSH * Descartar contraindicaciones relativas de ECT:
IAM reciente, arritmias inestables (ECG, cardiólogo), aneurisma de aorta
(RxTx), HTEC por proceso expansivo (examen neurológico con fondo de
ojo). En pacientes añosos: valoración cognitiva basal.

Marcadores de endogenicidad de la depresión (con fines académicos, no se
piden de rutina): * Dosificación de TSH a la estimulación con TRH: donde
esperamos encontrar una respuesta plana. * Hipnograma: donde esperamos
encontrar una disminución de la latencia REM, con aumento de actividad
REM, disminución del tiempo to-tal de sueño con despertares frecuentes.
De ser negativo no descarta endogenicidad, pero de ser positivo apoya
nuestro diagnóstico.

Si es BIPOLAR: valoración según estabilizador del humor que se plantee
usar (ver encare correspondiente).

===== Psicológico

Entrevistas diarias para obtención de datos, valorando repercusión de
pérdidas actuales y curso de vida. Entrevistas de continentación, no
prolongadas.

Luego de superado el cuadro actual: tests de personalidad proyectivos y
no proyectivos donde valoraremos fortaleza yoica, mecanismos de defensa,
focos de ansiedad y manejo de la agresividad.

De ser necesario: test de nivel, estudio neuropsicológico.

===== Social

Entrevistas con terceros para:

* objetivar adaptabilidad a las pérdidas * explicar medidas terapéuticas
a efectuar, riesgos y beneficios de ECT, consentimiento informado por
escrito. Comienzo del proceso de psicoeducación. * evaluación de red de
soporte social * valorar funcionamiento premórbido e intercrítico así
como existencia de corte existencial.

==== Tratamiento

Será realizado por un equipo interdisciplinario, centrado en el
paciente, coordinado por el médico psiquiatra, con enfermería,
psicólogo, asistente social y especialistas necesarios.

Destinado a:

{empty}1. Yugular cuadro actual acortando duración de las crisis,
aliviando el sufrimiento. 2. A largo plazo actuando sobre la enfermedad
de fondo, tratando la comorbilidad, previniendo complicaciones y
realizando profilaxis de futuras recaídas, reintegrando el paciente a su
medio en el mejor estado.

===== Episodio actual

Internación en sala psiquiátrica de hospital general / hospital
psiquiátrico (formas más graves), con acompañante a permanencia,
fundamentado en:

* Se trata de una urgencia psiquiátrica que coloca al paciente en un
riesgo de muerte por auto-eliminación. * Presencia de síntomas
psicóticos * Repercusión somática: anorexia, adelgazamiento * Necesidad
de reversión rápida del cuadro.

Con supervisión de enfermería las 24 horas, control de hidratación,
alimentación y toma de medicación, vigilando eventual intento de fuga o
autoeliminación. Acompañante a permanencia. Visitas reguladas según la
mejoría clínica de personas significativas, continentadoras, no
conflictivas.

====== Biológico

.Antidepresivos

La elección estará determinada entre otras cosas por AP de respuesta a
tratamientos previos. En caso de ausencia de antecedentes
seleccionaremos antidepresivos según situación clínica
footnote:[Cipriani, A., Furukawa, T. A., Salanti, G., Chaimani, A.,
Atkinson, L. Z., Ogawa, Y., ... & Geddes, J. R. (2018). Comparative
efficacy and acceptability of 21 antidepressant drugs for the acute
treatment of adults with major depressive disorder: a systematic review
and network meta-analysis. The Lancet, 391(10128), 1357-1366.]:

* Paciente sin tratamientos previos: preferimos el uso de un ISRS, tal
como Sertralina 50 mg 1 comp/día, por la menor incidencia de efectos
secundarios. En caso de coexistencia de ansiedad, preferimos un ISRS
sedativo (Fluvoxamina, Paroxetina). En caso de tratarse de un paciente
añoso: Escitalopram. Estos antidepresivos actúan mediante el bloqueo de
la recaptación se serotonina produciendo a mediano plazo una regulación
a la baja (desensibilización) de los autorreceptores 5HT1a
(presinápticos) y 5HT1d (postinápticos) de la neurona serotoninérgica.
Estaremos atentos a la aparición de efectos secundarios, sobre todo a
nivel digstivo en etapas iniciales, la posibilidad de viraje en plazos
medianos y la disfunción sexual (disminución de la libido, retardo en el
orgasmo) a mediano/largo plazo. * Paciente con tratamiento previo con
ISRS sin respuesta: planteamos el uso de Venlafaxina, antidepresivo con
doble mecanismo (acción sobre sistema noradrenérgico y
serotroninérgico). Comenzaremos con 75 mg/día, aumentando a 150 mg/día.
Según respuesta puede llevarse hasta 300 mg/día.

Depresión bipolar:

* Primera línea. Nivel 1: Quetiapina, Lurasidona + Litio/Divalproato.
Nivel de evidencia 2: Litio, Lamotrigina, Lurasidona
* Segunda línea. Nivel 1: Sertralina/Bupropion (adjuntos), Cariprazina.
Nivel 2: Divalproato, Olanzapina/Fluoxetina. Nivel 4: ECT.

* Paciente bipolar: planteamos de primera línea el uso de
estabilizadores del humor (Lamotrigina, Litio) con o sin combinación con
antipsicóticos atípicos (Aripiprazol). En caso de que haya que usar un
antidepresivo, preferimos el uso de Bupropion 150 mg LP, 1 comp/día, ya
que hay menos chances de que se produzca un viraje en el humor.

Estaremos atentos a la evolución del tratamiento ya que secuencialmente
mejoran: 1° la anorexia y el insomnio, luego la inhibición psicomotriz y
recién al final el dolor moral. Previo a este período, el paciente se
encuentra desinhibido con potencial suicida por la presencia del dolor
moral. En caso de que se trate de un paciente bipolar: controlaremos la
posibilidad de viraje del humor.

.ECT

Puede plantearse ante el fracaso del tratamiento farmacológico o (en
algunos casos clínicos) puede plantearse de entrada.

De entrada:

Por tratarse de icon:paperclip[] estamos ante una indicación formal de
ECT (depresión mayor con síntomas melancólicos, catatónicos o
psicóticos; melancolía ansiosa) ya que:

* El tratamiento farmacológico tiene latencia de al menos 15 días *
Ansioso: pasaje al acto con máximo riesgo vital * Las ideas de muerte
pueden no manifestarse por reticencia * Para provocar alivio sintomático
al intenso sufrimiento del paciente * La posibilidad de AE durante el
tratamiento con antidepresivos una vez mejorada la inhibición con
persistencia de dolor moral y las ideas de AE

Se realizará con el paciente con al menos 6 horas de ayuno, con el pelo
adecuadamente aseado, suspendiendo en esa mañana los fármacos que puedan
aumentar el umbral convulsivo (benzodiacepinas, antiepilépticos) o que
aumenten las probabilidades de confusión (litio).

El tratamiento conjunto desde el inicio con AD y ECT posee mejor índice
de mejoría que c/u por separado.

La ECT será realizada por anestesista y psiquiatra, una sesión cada día
por medio, con anestesia general (por ejemplo con Propofol),
oxigenoterapia, monitorización ECG y EEG; con el paciente curarizado
(por ejemplo con succinilcolina). Regularemos la cantidad de sesiones
según respuesta pero pensamos que serán necesarias entre 8-12 sesiones
para lograr el efecto deseado. Vigilaremos al paciente después de cada
sesión sabiendo que pueden existir cefaleas y trastornos mnésicos de
breve duración.

.Estabilizadores del humor Ver encare de Manía (F31) para el uso del
litio.

Lamotrigina: se trata de un fármaco con efecto de estabilización del
humor desde abajo con capacidad de prevención de recurrencias depresivas
(no de recurrencias maníacas). Debiendo aumentarse de forma gradual por
el riesgo de la presentación de rash (8 Comenzaremos con 25 mg/día
aumentando en 15 días a 50 mg, luego en 15 días a 100 mg para llegar
finalmente a una dosis de 200 mg. En caso de usarse conjuntamente con
divalproato, debe ajustarse la dosis de la lamotrigina a la mitad. En
caso de usarla conjuntamente con carbamazepina, debe usarse el doble de
dosis que lo habitual.

.Otras formas clínicas

* Delirante: agregar antipsicóticos, preferentemente atípicos:
Aripirazol icon:arrow-right[] Olanzapina icon:arrow-right[] Risperidona
icon:arrow-right[] Haloperidol. * Agitada-ansiosa: preferentemente ISRS
sedativo (Fluvoxamina). ECT si la agitación es intensa. * Bipolares: ver
encare correspondiente.

.Síntomas accesorios

Para combatir el insomnio usaremos Flunitrazepam 2 mg v/o en la noche
para controlar el insomnio (las horas de la madrugada son las de mayor
riesgo suicida). En caso de persistir insomnio, agregaremos Midazolam 1
amp i/m si no duerme.

Para la ansiedad, usaremos benzodiacepinas (Diazepam, Lorazepam,
Clonazepam, Alprazolam) que proven un rápido alivio de la ansiedad hasta
que el resto de los fármacos pasen su período de latencia.

.Refractariedad

Ante la falta de respuesta a la farmacoterapia luego de 4-8 semanas se
debe:

. revisar el diagnóstico . verificar que cumpla con el tratamiento .
descartar problemas médicos concomitantes . descartar UISP . descartar
comorbilidad con otros trastornos psiquiátricos . re-evaluar aspectos
psicosociales

Desde el punto de vista farmacológico, considerar agregado de:
antidepresivo con distinto mecanismo icon:arrow-right[] Aripiprazol
icon:arrow-right[] Litio icon:arrow-right[] T4.

.Alta

Criterios de alta:

. Rectificación de las ideas de muerte . Desaparición del delirio .
Normalización de las CB . Mejoría global de la depresión .
Estabilización de los niveles plasmáticos de fármacos

Otorgaremos el alta hospitalaria una vez superado el cuadro actual en el
cual es fundamental la rectificación de la conducta suicida.
Mantendremos el antidepresivo a dosis plenas por largo plazo.
Controlaremos en policlínica quincenalmente en un principio y luego se
espaciarán hasta ser mensuales.

====== Psicológico

Realizaremos entrevistas diarias orientadas a:

* Continentar al paciente sin provocar fatiga (para el paciente la
entrevista representa un esfuerzo psíquico)
* Generar y consolidar el vínculo terapéutico con el paciente y la
familia
* Psicoeducación: generar conciencia de la importancia de la adhesión al
tratamiento como determinante del pronóstico a mediano y largo plazo. Se
educará acerca de signos y síntomas de recaída.
* Evaluar evolución del tratamiento

Realizaremos apoyo psicológico para reelaboración de pérdidas.

====== Social

Entrevistas con la familia para integrarla al proceso terapéutico.
Psicoeducación para familiares. Información sobre el uso de recursos
pertinentes para la enfermedad. Biblioterapia.

===== Mantenimiento

====== Psicológico

Luego del alta y/o cuando el paciente esté en condiciones de hacerlo, se
comenzará con psicoterapia.

Depresión Bipolar: no existe psicoterapia de primera línea. De segunda
línea: psicoterapia cognitivo-comportamental, psicoterapia enfocada en
la familia, psicoterapia interpersonal y de ritmos sociales. No hay
evidencia suficiente para otras formas de psicoterapia.

==== Evolución y pronóstico

Sabemos que la PMD mono/bipolar es una enfermedad crónica que evoluciona
por accesos que pueden reiterarse. Pautas previas de recaídas predicen
índice futuro. Si bien con el tratamiento profiláctico esperamos los
períodos intercríticos y disminuir gravedad de los accesos. Pronóstico
alejado depende de adhesión al tratamiento. A mayor edad más episodios,
ML, IAE.

PVI PPI: bueno, sujeto a complicaciones: IAE.

PVA: lo que tenga, sujeto al psiquiátrico. Mayor prevalencia de
suicidios (en especial depresiones con síntomas psicóticos). La
depresión no tratada disminuye la expectativa y la calidad de vida.

PPA:

* orgánico: AF/AP IAE, edad * psiquiátrico: situaciones adversas, falta
de elaboración de pérdidas, sentimiento de abandono. * social:
aislamiento, pérdida de roles, relaciones interpersonales

Hay una tendencia a la pérdida de la reactividad en los episodios con
progresiva autonomía de factores desencadenantes.

Se postulan formas evolutivas a la cronicidad (nosografía clásica): .
Melancolía crónica simple (acceso con remisión parcial) . Delirio
crónico melancólico (persiste al desaparecer la depresión), a forma
hipocondríaca o a forma de síndrome de Cottard crónico.

===== Factores de mal pronóstico . Antecedentes de maltrato o abuso en
la infancia: factor de riesgo para severidad, precocidad, resistencia y
cronificación de cuadros depresivos footnote:[Nelson, Janna, et al.
"Childhood maltreatment and characteristics of adult depression:
meta-analysis." The British Journal of Psychiatry 210.2 (2017):
96-104.]. . Síndrome metabólico footnote:[Pan, An, et al. "Bidirectional
association between depression and metabolic syndrome: a systematic
review and meta-analysis of epidemiological studies." Diabetes care 35.5
(2012): 1171-1180.].

==== En suma

Hemos visto un paciente de sexo X, de X años de edad, con un MSEC X, con
AF de X, con APM de X, con AP de X, que consulta por X síntomas, en
quien diagnosticamos un episodio X en un trastorno X, planteándose DD
con X, que hemos estudiado con X, planteando un tratamiento X, cuyo
pronóstico es X.
