== Trastornos fóbicos

=== Notas clínicas

Ansiedadfootnote:[Kalin, Ned H. "Novel insights into pathological
anxiety and anxiety-related disorders." American Journal of Psychiatry
177.3 (2020): 187-189.] : función adaptativa. Ansiedad patológica:
preocupación excesiva, hipervigilancia, activación fisiológica,
conductas de evitación. Incidencia de lo genético: 30-50%, multigénico.
Factores no genéticos: estilo parental, aprendizaje social, adversidad
en la infancia (exposición a estrés, maltrato, NSEC deficitario).
Epidemiología: prevalencia en 12 meses: 18%. M a H -> 3 a 1. En niños y
adolescentes prevalencia 15-20%. Predictor de mala evolución para otros
trastornos. Clasificación DSM5: trastorno de ansiedad de separación,
mutismo selectivo, trastorno de ansiedad social, trastorno de pánico,
agorafobia, trastorno de ansiedad generalizada, trastorno de ansiedad
inducido por sustancias o fármacos, trastorno de ansiedad debido a
enfermedad médica. Quedan aparte: trastornos relacionados a estresores
(previamente TEPT y trastorno por estrés agudo) y TOC. De todos modos se
siguen considerando todos trastornos de ansiedad. Marcador más fiable en
infancia: inhibición comportamental en respuesta a extraños o a
situaciones nuevas -> estable en el tiempo -> x3 o x 4 riesgo de
trastorno de ansiedad y FR para depresión y trastornos por consumo de
sustancias. Circuitos involucrados: núcleo central de la amígdala y
corteza orbitofrontal posterior).

=== Encare

En suma: paciente de sexo X, de X años de edad, con AFP de trastornos de
ansiedad que consulta por cuadro de X tiempo de evolución centrado en
temores específicos / inespecíficos que pasamos a analizar.

==== Agrupación sindromática

===== Síndrome fóbico

Entendiendo por fobia, la presencia de un temor irracional y exagerado,
persistente en el tiempo, con objeto colocado en el exterior que le
genera conductas de evitación y de tranquilización. Está dado por:

* Temor irracional intenso, independiente del control voluntario
* Reconocido como absurdo por parte del paciente
* Originado por objeto o situación que en sí misma no tiene
características de peligrosidad
* Cuya presencia desencadena crisis de ansiedad que puede tomar la forma
de Crisis de Pánico.
* Que desaparece al margen del objeto-situación (lo que favorece la
aparición de conductas de evitación).
* Que genera conductas tranquilizadoras: elementos que cumplen función
aseguradora de protección: personaje, habitación, objeto, ingesta de
alcohol.

La exposición al objeto genera una experiencia intensamente
displacentera, constituida por la vivencia en forma brusca paroxística:

* en el ámbito psíquico (afectivo-cognitivo) de miedo, sensación de
peligro inminente, temor, malestar, espera penosa, expectación
aprensiva, temor a perder el control o enloquecer, miedo a morir
* en el ámbito somático (psicomotriz y neurovegetativo) de
palpitaciones, taquicardia, opresión torácica, sudor, escalofríos,
sofocaciones, temblores, parestesias, vértigos, mareos, demsayos,
disfagia, náuseas, malestar abdominal.

El cuadro puede tomar la forma de:

* Agorafobia (F40.00, F40.01): aparición de ansiedad el encontrarse en
lugares o situaciones donde escapar puede resultar difícil (o
embarazoso) o donde, en el caso de aparecer síntomas de angustia puede
no disponerse de ayuda. Suelen ser temores relacionados con un conjunto
de situaciones características (estar solo fuera de la casa, mezclarse
con gente, hacer cola, pasar por un puente, viajar en ómnibus, tren o
automóvil). Estas situaciones se evitan o se resisten a costa de intenso
malestar o bien requieren de la presencia de un conocido para
soportarlos.
* Fobia social (F40.1): temor irracional persistente y reconocible de
turbarse o verse humillado cuando se desempeña en situaciones sociales.
* Fobia simple o específica (F40.2): temor persistente a un objeto o
situación.

===== Síndrome de ansiedad-angustia

Bajo la forma de ansiedad generalizada (ver F41.1) o crisis de pánico
(ver F41.0).

===== Síndrome conductual

Subsidiario de la fobia ya analizada.

* consumo de alcohol y/o benzodiacepinas
* pragmatismos: indican gravedad de la fobia, de X evolución

===== Síndrome hipocondríaco

Definido como la interpretación no realista de signos y sensaciones
físicas que conducen a preocupación o temor de padecer una enfermedad.
Elaboración hipocondríaca de los síntomas de angustia. Diferenciar
hipocondría (la consulta al médico no calma ansiedad) de:

* Nosofobia (la consulta al médico calma la angustia y es equivalente a
una conducta tranquilizadora)
* Psicosis: convicción delirante de padecer enfermedad.

===== Síndrome de despersonalización

Constituido x 3 elementos clásicos:

* Despersonalización
* Desanimación: cambio del yo psíquico: "como otra persona".
* Desrealización: cambia el ambiente. Especificar si aparece vinculado
la angustia.

==== Personalidad y nivel

Nivel: cualquiera (independencia de ejes I y II).

Personalidad:

* Conflictiva infantil
* Rasgos neuróticos globales
* Rasgos de la serie fóbica:
** Huida hacia adelante: comportamiento de desafío, hiperocupación
** Tímido, pasivo, dependiente
** Actitud evitativa
** Dificultad para sobreponerse a pérdidas
** Tendencia a la inestabilidad motora (vértigo, falta de equilibrio) e
hiperestesia somática
* Buena relación interpersonal, pedido de ayuda

==== Diagnóstico positivo

===== Nosografía Clásica

====== Neurosis

Fragmentos: Neurosis.

====== Neurosis fóbica

Por el síndrome fóbico que centra el cuadro con su tríada característica
de: fobia + evitación + tranquilización, hacemos diagnóstico de neurosis
fóbica para la nosografía clásica a forma clínica (Agorafobia, social,
simple).

====== Gravedad

Leve-moderada-grave- incapacitante.

====== Descompensada

Por:

* Síndrome de ansiedad angustia
* Depresión (disfórica)
* Exacerbación de síntomas

===== DSM IV - CIE-10

====== F40.0: Agorafobia (sin historia de trastorno de angustia)

Requiere:

A. Agorafobia B. sin criterios de trastorno de angustia + C. descartar
sustancias o enfermedad médica + D. si hay enfermedad médica, el temor
es claramente excesivo en comparación con el habitualmente asociado a
enfermedad médica.

====== F40.1: Fobia social

Requiere:

A. temor acusado y persistente por una o más situaciones sociales o
actuaciones en público en las que el sujeto se ve expuesto a personas
que no pertenecen al ámbito familiar o a la posible evaluación por parte
de los demás. Teme actuar de un modo que resulte humillante o embarazoso
+ B. la exposición provoca respuesta de ansiedad (con o sin crisis de
pánico) + C. reconoce que el temor es excesivo o irracional + D.
evitación (o las soporta con malestar intenso) + E. interferencia con
desempeño + F. más de 6 meses en menores de 18 años + G. descartar
sustancias, enfermedad médica y otros trastornos mentales + H. si hay
otro diagnóstico, la fobia no se relaciona con estos procesos (por
ejemplo, el miedo no es debido a tartamudez o a exhibición de conductas
vinculadas a un trastorno de la alimentación)

Especificadores: generalizada: si los temores hacen referencia a la
mayoría de las situaciones sociales.

====== F40.2: Fobia específica

Requiere:

* A. temor acusado y persistente que es excesivo e irracional,
desencadenado por la presencia o anticipación de un objeto o situación
específicos (volar, precipicios, animales, inyecciones, sangre) +
* B. desencadenamiento de reacción de ansiedad (puede ser o no crisis de
pánico) si se expone al estímulo +
* C. la persona reconoce que el miedo es excesivo o irracional +
* D. conductas de evitación (o soportan las situaciones con un malestar
acusado) +
* E. interferencia con desempeño +
* F. más de 6 meses en menores de 18 años +
* G. descartar otros trastornos mentales.

Especificadores: tipo (animal, ambiental, sangre-inyecciones-daño,
situacional, otros)

==== Diagnósticos diferenciales

===== Nosografía clásica

* Neurosis de angustia: no existen conductas de evitación ni
tranquilización. En la NF los elementos de AA son subsidiarios al
síndrome fóbico que aparece descompensando. En la NA no existen
mecanismos de defensa estructurados. * Otras neurosis. * Fobia
sintomática de Trastorno de la Personalidad. * Fobia sintomática de un
trastorno psicótico: dismorfofobia, nosofobia, hipocondría delirante. *
Crisis de angustia: descartar origen orgánico: ** Hiperglicemia **
Feocromocitoma ** Prolapso de válvula mitral (comorbilidad) **
Hipertiroidismo * Drogas: abstinencia (barbitúricos, benzodiacepinas),
intoxicación (anfetaminas y similares) * Si hay un S° depresivo:
Trastorno afectivo primario

===== DSM / CIE-10

Los diagnósticos diferenciales son diferentes dado que estos sistemas
clasificatorios permiten acumular diagnósticos en uno o más ejes. Los
principales diagnósticos diferenciales son:

* Entre los diferentes trastornos de ansiedad: ** Agorafobia con/sin
crisis de pánico: ** Fobia específica: x ej. evitación limitada a
situaciones aisladas (ascensores). ** Fobia social: x ej. evita
determinadas situaciones sociales por temor a ruborizarse. ** TOC: x ej.
evita situaciones vinculadas a obsesión (evita suciedad si hay ideas
obsesivas de contaminación. ** TEPT: evitación de estímulos relacionados
con situación altamente estresante o traumática. ** Trastorno por
ansiedad de separación: evitación de abandonar el hogar o la familia. *
Causas médicas * Inducidos por sustancias * Como diagnósticos
adicionales (más que diferenciales) considerar Trastorno de la
Personalidad del grupo C (sobre todo TP por Evitación).

==== Etiopatogenia y psicopatología

Se propone una gran heterogeneidad causal, aplicándose en general el
modelo de estrés-diátesis.

===== Biológico

Algunos autores proponen un modelo vulnerabilidad-estrés, citando una
predisposición constitucional en personas que nacen con un temperamento
específico conocido como "inhibición conductual a lo desconocido", que
ante factores de estrés constituirían una fobia.

Para el caso de la fobia específica y la fobia social, podría existir un
componente genético (tiende a darse en la misma familia: 2/3 de los
sujetos tienen al menos un familiar de primer grado con una fobia del
mismo tipo). Para la fobia social hay mayor concordancia entre gemelos
monocigóticos. Los familiares de primer grado de pacientes con fobia
social tiene 3 veces más probabilidades de tenerlas que los familiares
de personas sanas.

Para el caso de la fobia social, diversos autores postulan la existencia
de alteraciones en sistemas de neurotransmisión (adrenérgico,
serotoninérgico y dopaminérgico), basado en la eficacia de fármacos como
los antagonistas beta-adrenérgicos, los ISRS y los IMAO en este
trastorno. Los pacientes con FS liberarían más adrenalina a nivel
central y periférico que los no-fóbicos.

En la fobia social generalizada podría estar alterado el sistema
dopaminérgico, esta afirmación se basa en:

* Eficacia de los IMAO y Bupropion (que afectan el sistema Dopa) *
Desarrollo de síntomas de ansiedad social luego del tratamiento con
fármacos que bloquean la Dopamina * Correlación existente entre rasgos
de introversión y bajos niveles de Dopamina en el LCR * Altas tasas de
Fobia Social en pacientes con Enfermedad de Parkinson. * Baja actividad
dopaminérgica detectada en cepas de ratones "tímidos" * Bajos niveles en
LCR de ácido homovanílico en pacientes con T de Pánico y Fobia Social. *
En SPECTs aparece una disminución en la densidad de sitios de
recaptación de Dopamina a nivel del estriado.

Neuroimagen: los estudios sugieren la presencia de circuitos neurales
específicos involucrados en la Fobia Social (cíngulo anterior, cortex
prefrontal dorsolateral, cerebelo, cortex orbitofrontal).

===== Psicológico

====== Psicoanálisis

Para Freud la ansiedad es una señal del Yo que se pone en marcha cuando
algún impulso inconsciente prohibido está luchando para expresarse en
forma consciente, lo que lleva al Yo al uso de mecanismos de defensa
auxiliares:

* Represión: mecanismo destinado a mantener la pulsión fuera de la
representación consciente. Este mecanismo fracasa por lo cual la
conflictiva rechazada irrumpe en la conciencia debiendo recurrir el yo a
defensas auxiliares para combatir la angustia que provocan las pulsiones
genitales edípicas incestuosas * Desplazamiento: separa el afecto de la
representación prohibida y lo desplaza a una situación u objeto en el
exterior, aparentemente neutro, pero en conexión asociativa con la
fuente del conflicto (simbolización como mecanismo de defensa). *
Evitación como mecanismo adicional de defensa. El objeto sobre el que se
desplaza la angustia puede ser evitado.

La reactivación del conflicto sobrepasa los mecanismos de defensa ya
estructurados y se manifiesta como angustia. Se trata de una regresión y
fijación a etapa edípica del desarrollo psicosexual, vinculado a intensa
angustia de castración (el impulso sexual continuaría teniendo una
marcada connotación incestuosa en el adulto por lo que la activación
sexual tiende a transformarse en ansiedad que de forma característica es
un miedo a la castración).

Teorías más recientes también proponen la existencia de otras angustias:
de separación (Agorafobia), ansiedad del Superyo (vergüenza vinculada a
la eritrofobia).

Dentro del modelo psicoanalítico se destaca la existencia de actitudes
contra-fóbicas, patrón conductual que representa una negación (del temor
ante el objeto). La persona busca y se enfrenta a situaciones de
peligro. Podría estar implicado el mecanismo de defensa de
"identificación con el agresor".

.Teoría Cognitivo-comportamental

El modelo teórico del aprendizaje (Watson) vincula la fobia y la
evitación consiguiente al modelo estímulo-respuesta pavloviano
tradicional de los reflejos condicionados, donde un estímulo
originalmente neutro se transforma en condicionado para producir
ansiedad al presentarse apareado a un estímulo amenazante. Si bien el
condicionamiento clásico puede explicar el origen de la fobia, no
explica el mantenimiento, para lo cual se postula la intervención del
condicionamiento operante: el patrón de evitación se muestra eficaz para
reducir la ansiedad por lo que se refuerza el mantenimiento de la fobia.

Otro mecanismo de aprendizaje que podría estar implicado es el
moldeamiento (por observación de reacciones de un tercero).

===== Social

Estrés psicosocial en el curso de vida, en especial: muerte de un
progenitor, separación de progenitores, crítica o humillación por
terceros, violencia intrafamiliar: activarían la diátesis latente con la
consiguiente aparición de síntomas.

==== Paraclínica

===== Biológico

Examen físico completo: neurológico, signos de intoxicación por
psicoestimulantes (midriasis, PA, pulso), tiroides, CV (eventual EcoCG,
ECG, para uso de AD y buscando trastornos de la conducción). Paraclínica
general.

===== Psicológico

Superado el cuadro actual: tests de personalidad proyectivos (TAT,
Rorscharch), no proyectivos (Minnesota), evaluando:

* Fortaleza yoica * Elementos para el análisis de los mecanismos de
defensa * Implementación de psicoterapia Tests de nivel (Weschler).

Para el seguimiento del trastorno, pueden ser útiles las escalas de
cuantificación de síntomas.

===== Social

Familiares y terceros. Valoración de red de soporte. Datos de HC y
tratamientos previos.

==== Tratamiento

* Ambulatorio con control en policlínica * Hospitalizar según entidad de
síndromes asociados (ej. depresión)

Objetivos del tratamiento:

* Alivio de afectos y cogniciones vinculadas al temor * Reducción de la
ansiedad anticipatoria * Atenuar el comportamiento de evitación *
Reducir los síntomas autonómicos y fisiológicos de ansiedad * Lograr
mejores niveles de funcionamiento Directivas: compensar el cuadro actual
y tratar la enfermedad de fondo.

===== Biológico

.Agorafobia sin trastorno de pánico El tratamiento de la agorafobia sin
crisis de pánico sería, en primera instancia, psicoterapéutico. Como
coadyuvante o para casos resistentes pueden usarse ISRS.

Primera línea: ISRS/Venlafaxina.

Segunda línea: Clorimipramina (o Imipramina). Iniciar con 10 mg con
comida, con aumentos progresivos de 10 mg cada 2-3 días y luego aumentos
de 25 mg cada 2-3 días (estos pacientes pueden presentar
sobreestimulación si se comienza de forma brusca) hasta 100-300 mg en
2-4 tomas (o en 1-2 tomas en preparados de liberación sostenida). Está
contraindicada en caso de IAM reciente, arritmia severa, glaucoma,
retención urinaria, 1º trimestre de embarazo. Precauciones en: ancianos,
epilépticos, bipolares, riesgo suicida, trabajos de riesgo. Efectos
secundarios: anticolinérgicos. Interacciones: IMAOs, simpaticomiméticos.

Tercera línea: si no hay respuesta con Clorimipramina, puede haber
respuesta con Fenelzina 45-90 mg/día (máximo = 1.2 mg/Kg/día). Iniciar
con 15 mg/día aumentando de a 15 mg lentamente hasta lograr control de
manifestaciones. Está contraindicada en caso de insuficiencia cardíaca,
AP o riesgo de AVE, insuficiencia hepática y Feocromocitoma. Debe
informarse al paciente de las restricciones dietéticas referidas a
alimentos que contienen tiramina (pueden desencadenar crisis
hipertensivas): quesos, embutidos, conservas de carne, habas, bananas,
pasas de uva, higos, dátiles, levadura, cerveza, vino, café, chocolate,
bebidas cola. Se proscribirán los siguientes medicamentos: aminas
vasopresoras (incluso las contenidas en gotas nasales y antigripales),
Meperidina, otros IMAO, tricíclicos, anorexígenos, Dopamina. Debe
suspenderse 10 días antes de una cirugía de elección. Reacciones
adversas: CV (hipotensión postural, crisis hipertensivas),
neuropsíquicas, digestivas, leucopenia. Interacciones medicamentosas
importantes.

La duración de cada prueba terapéutica debe ser de 8-12 semanas (mayor
que en la depresión). El tratamiento se continuará a las dosis con las
que se obtuvo mejoría por 6-12 meses luego de la remisión sintomática. A
partir de ese momento se continúa con la dosis mínima eficaz por 2-5
años.

.Fobia específica El tratamiento básico es psicoterapéutico, el
tratamiento farmacológico será de apoyo pudiendo utilizarse:
Benzodiacepinas: de cualquier tipo a dosis adecuadas para cada caso,
generalmente en monodosis para disminuir la ansiedad en el momento de la
exposición. Por ejemplo: Alprazolam 1 mg media hora antes de la
situación fóbica. Ambos fármacos deben dejar de usarse cuando
desaparezcan los síntomas. Propranolol: en monodosis (20-40 mg) media
hora antes de la situación fóbica. El uso de medicación en forma
continua queda reservado para casos refractarios: Alprazolam 0.5-1 mg
c/8 o Propranolol 20-80 mg/día. Los fármacos en pauta fija se mantendrán
hasta 6 meses después de la remisión sintomática.

.Fobia social Fobia social restringida o limitada

* Primera línea: beta bloqueantes (Propranolol 40-80 mg 30 minutos antes
de la previsible situación fóbica). * Segunda línea: benzodiacepinas,
dosis de 5-15 mg de equivalentes Diazepam.

Fobia social generalizada o difusa Si bien el fármaco mejor estudiado y
con mayores índices de eficacia es la Fenelzina, su manejo complicado
(con contraindicaciones y restricciones) lo relegan a un segundo plano.

* Primera línea: Paroxetina 20 - 60 mg/día > Sertralina > Fluvoxamina
(orden según calidad de evidencia en estudios realizados) * Segunda
línea: Clorimipramina, Paroxetina, Sertralina, Moclobemida (eficacia
clínica limitada). Fenelzina 45-90 mg/día, iniciando con 15 mg/día,
aumentando hasta 45-60 mg/día, esperando 4 semanas y luego, según
resultados y tolerancia puede aumentarse hasta. * Casos resistentes:
pueden asociarse benzodiacepinas: Alprazolam o Clonazepam (la terapia
única con BZD es de eficacia dudosa o limitada).

En casos de fobia generalizada se mantendrá el tratamiento hasta 12
meses luego de remisión sintomática, a las dosis con las que se logró
mejoría. Luego pueden disminuirse de forma progresiva, si aparece
recidiva se vuelve a las dosis eficaces que se mantendrán por 12 meses
más. Tratamientos superiores al año podrían estar indicados en:
pacientes con síntomas significativos persistentes, presencia de
comorbilidad, inicio precoz con TP por Evitación severo y pacientes con
historia previa de recaídas.

===== Psicológico

Entrevistas en ambiente cálido y de escucha, afianzar vínculo, explicar
enfermedad.

====== Agorafobia sin trastorno de pánico

Terapia cognitivo-comportamental: explicar los mecanismos generadores de
ansiedad fóbica. La técnica más usada es la exposición in vivo, con
terapeuta o en autoexposición. Debe realizarse de forma progresiva según
una jerarquía creciente de enfrentamiento al estímulo fóbico.

====== Fobia simple/específica

Terapia cognitivo-comportamental: en especial técnicas de entrenamiento
en relajación, desensibilización sistemática y exposición in vivo o
imaginada. En caso de fobia a las heridas, sangre, etc., se recomienda
el uso de técnicas de tensión muscular en lugar de técnicas de
relajación.

====== Fobia social

Terapia cognitivo-comportamental: en especial técnicas de inoculación de
estrés (exposición para reducción del miedo), entrenamiento en
asertividad y habilidades sociales, reestructuración cognitiva.

===== Social

Terapia familiar, grupo de apoyo. Alianza terapéutica con familiar por
tendencia de los fóbicos a abandonar la terapia.

==== Evolución y pronóstico

Puede seguir varios caminos evolutivos:

* Mejoría total * Mejoría parcial permaneciendo síntomas residuales *
Refractariedad * Comorbilidad con depresión y abuso de sustancias

Es una enfermedad crónica con tendencia a la recidiva. PVI: bueno PPI:
crisis y depresión bueno. PVA: depende de complicaciones del cuadro.
PPA: depende de adhesión al tratamiento.

Dentro de las complicaciones, destacamos la alta tasa de comorbilidad
(hasta 80%, con EDM, entre fobias, alcohol, abuso de benzodiacepinas) y
la mayor tasa de suicidio en esta población.

El pronóstico depende de:

* Gravedad del trastorno al inicio del tratamiento
* Edad de comienzo del tratamiento
* Continuidad del tratamiento
* Nivel intelectual
* Nivel socioeconómico
* Comorbilidad (depresión, alcoholismo, TP)
* Antecedentes familiares (predictor negativo para el caso de la fobia
social).

==== Fuentes

* RTM II * The Journal of Clinical Psychiatry 59(supp 17), 1998.
