== Trastornos conversivos y disociativos / Neurosis histérica

=== Encare

==== Agrupación sindromática

===== Síndrome conversivo

Entendiendo por conversión la pérdida o alteración del funcionamiento
físico que sugiere trastorno somático/físico pero sin base orgánica
demostrable, que se interpreta como vinculado a un conflicto o necesidad
psicológica/intrapsíquico dado por:

====== A nivel motor

* Crisis de excitación psicomotriz que motivan el ingreso, de X tiempo
de evolución, paroxísticas, con movimiento de los 4 miembros, con caída
al suelo, rotura de objetos, emisión de gritos, en presencia de público,
con o sin pérdida de conocimiento, sin incontinencia esfinteriana ni
sopor postcrítico, sin mordedura de lengua, sin cianosis. Relata crisis
mostrando indiferencia hacia ésta, frecuencia diaria, duración,
desencadenada por conflicto emocional (ejemplo). Por lo que la
calificamos de crisis conversiva, expresión atenuada de la gran crisis
de Charcot. * Manifestaciones deficitarias permanentes de X duración: **
Astasia-abasia: incapacidad de andar y mantenerse de pie, quedando la
posibilidad de realización de movimientos activos que no sean de
deambulación. ** Parálisis y contracción localizadas: sin
sistematización anatómica. Incluye afonía por parálisis de músculos
fonadores. ** Movimientos anormales.

====== A nivel sensitivo

* Anestesia: sin sistematización anatómica, en bota, en guante,
hemicuerpo. * Puntos hiperestésicos * Algias, con impotencia funcional
desproporcionada

====== A nivel sensorial

* Visuales: obnubilación, diplopía, ceguera (con las características de:
reducción concéntrica del campo visual y diplopía monocular). *
Auditivos

====== A nivel neurovegetativo

* Espasmos de músculo liso y esfínteres, faringe, vómitos, respiratorio,
vesical, vaginal

Crisis de inhibición psicomotriz ("ataques catalépticos", "sueño
histérico"), simula un coma. Se recupera por técnicas sugestivas o
dolorosas. Sin la tríada característica del sueño normal: miosis,
estrabismo divergente por el predominio del tono del gran oblicuo,
contracción activa del orbicular de los párpados).

===== Síndrome disociativo histérico

Definido como la alteración súbita y transitoria de las funciones
integradoras de la conciencia, memoria, identidad, percepción, dado por:

====== Trastornos mnésicos

Amnesia disociativa psicógena: evocación biográfica imprecisa, amnesia
lacunar y selectiva, con dificultad para evocar determinados recuerdos
importantes de valor simbólico (Ej.: experiencias dolorosas o
vergonzosas), con desencadenante psicológico. Puede ser global y total a
partir del desencadenante (generalizada y continua). La evocación de
violación/seducción puede corresponder a una ilusión de la memoria,
alteración frecuente en estos pacientes footnote:[Políticamente
incorrecto, actualmente]. Puede haber identificación imaginaria con
otras personas (por ejemplo con otras pacientes de la sala: siente sus
síntomas). No hay evidencias de un trastorno mental orgánico.

====== Fuga disociativa

Con desencadenante emocional. Amnesia disociativa + desplazamiento
intencional (lejos del hogar o lugar de trabajo), en la cual mantiene
cuidados básicos de sí mismo, lleva a cabo una interacción simple con
extraños y presenta amnesia del episodio, por lo que lo calificamos de
fuga psicógena. Puede presentar confusión sobre su identidad.

====== Estupor disociativo

Ver encare de estupor. Clínicamente reconocido por una disminución
profunda o ausencia de movilidad voluntaria, disminución de reactividad
a estímulos exteriores, no está dormida ni inconsciente.

====== Estados crepusculares

Debilitamiento del nivel de consciencia, que puede llegar en profundidad
desde la obnubilación al estupor. Comporta una experiencia
semiconsciente de despersonalización y extrañeza.

====== Estados segundos

Caracterizados por un estado de consciencia debilitado dentro del cual
ocurre una producción de gran riqueza visual compleja (fenómenos
seudoperceptivos). Son de alto valor simbólico afectivo, en las que
podemos inferir la expresión de conflictos internos, que recuerda al
ensueño, admiten crítica, estereotipadas, parahípnicos (hipnagógicos o
hipnapómpicos). Dados por elementos sensorailes excitatorios de
diferente complejidad (acufenos, fosfenos). Pueden plantear DD con
crisis uncinadas si hay alteraciones olfativas. Otros nombres:
alucinosis histérica, síndrome seudoperceptivo.

====== Otros

Sonambulismo, personalidad múltiple.

===== Síndrome de ansiedad-angustia

Vivencial: estado de alerta y tensión, inquietud permanente sin objeto,
desmesurado de las preocupaciones.

Somático: tensión motora, hiperfuncionamiento autónomo, vigilancia y
control.

===== Síndrome depresivo

Humor y afectividad: irritabilidad (disforia histeroide), anhedonia. A/v
depresión atípica (irritabilidad, hipersomnia, hiperorexia). Inhibición
psicomotriz (presentación, pensamiento: ideas tristes, apatía, astenia,
conductas basales y pragmatismos). Dolor moral: ruina, culpa,
minusvalía, ideas de muerte o de AE.

===== Síndrome conductual

IAE.

===== Generalidades del cuadro

El cuadro tienen las siguientes características:

* Factor desencadenante: relación temporal entre un estímulo estresante
y el inicio del síndrome, reactivo. * Beneficio secundario (3° para el
psicoanálisis): le permite evitar un perjuicio u obtener un beneficio
del entorno. * Intencionalidad inconsciente: el síntoma no es
voluntario, simboliza un deseo inconsciente. * Inicio súbito, posterior
a una crisis de ansiedad que suele cesar con la instalación del síntoma
* Representa el concepto que la paciente tiene sobre el trastorno
somático * Bella indiferencia hacia el síntoma * Contexto biográfico y
actual que le da sentido al síntoma * Recurrencia en el tiempo

==== Personalidad y nivel

Nivel: pueden haber síntomas conversivos en contexto de nivel marginal /
BNI (DD con la puerilidad que puede verse en algunas histerias). Ante la
duda: test de nivel.

Personalidad:

Historia de conflictiva infantil.

Rasgos neuróticos globales (yo débil)

* Mal manejo de la agresividad * Trastornos de la esfera sexual *
Dependiente/inmaduro

Rasgos histéricos/personalidad histérica

* Egocentrismo
* Histrionismo: hiperexpresividad, dramatismo, fantasía mitomanía
* Labilidad emocional
* Sugestionabilidad plasticidad: autosugestión, sugestión externa
* Dependencia
* Erotización de los vínculos
* Trastornos sexuales
* Superficialidad de vínculos
* Poco interés por lo intelectual
* Baja tolerancia a las frustraciones
* Manipulación del entorno
* Acting-out con escasa o nula previsión de sus actos

En la entrevista destacar:

* bella indiferencia
* impresionsimo, teatralidad, sugestionabilidad
* intento de manipulación o manejo de la entrevista
* puerilidad
* erotización o intento de seducción durante la entrevista

Siguiendo nosografía propuesta por DSM, puede estar asociados a rasgos
histriónicos: patrón de excesiva emotividad y búsqueda de atención con 5
o más de:

* incomodidad si no es el centro
* erotización de los vínculos (comportamiento sexualmente seductor o
provocador)
* expresión emocional superficial y cambiante
* uso del aspecto físico para llamar la atención
* forma de hablar excesivamente subjetiva y carente de matices
* teatralidad, dramatización
* sugestionabilidad
* considera sus relaciones más íntimas de lo que son

TIP: El TP Histriónico se asocia a: Trastorno de Somatización, Trastorno
Conversivo/Disociativo, otros trastornos del grupo B.

==== Diagnóstico positivo

===== Nosografía Clásica

Fragmentos: Neurosis.

====== Neurosis histérica

Por síndrome disociativo histérico + síndrome conversivo (críticos o
permanentes), en un paciente con rasgos de personalidad histérica, con
AP de cuadros similares. Leve/moderada/grave: según grado de repercusión
sociofamiliar-laboral, intensidad y duración de los síntomas.

====== Descompensada

Por:

* Síndrome depresivo
* Ansiedad angustia
* Exacerbación de síntomas con falla de mecanismos de defensa
* Crisis conversiva o estado conversivo
* IAE Causa de descompensación: estrés psicosocial situación vital que
es incapaz de asumir (matrimonio, hijo, episodio conflictivo
intrafamiliar, frustraciones afectivas, situación de abandono o
rechazo).

===== CIE-10 - DSM IV

====== CIE-10

Las posibilidades diagnósticas (CIE) son:

F44 Trastornos disociativos (de conversión)

* F44.0 Amnesia disociativa
* F44.1 Fuga disociativa
* F44.2 Estupor disociativo
* F44.3 Trastornos de trance y de posesión
* F44.4 Trastornos disociativos de la motilidad
* F44.5 Convulsiones disociativas
* F44.6 Anestesias y pérdidas sensoriales disociativas
* F44.7 Trastornos disociativos (de conversión) mixtos
* F44.8 Otros trastornos disociativos (de conversión)
* F44.80 Síndrome de Ganser
* F44.81 Trastorno de personalidad múltiple
* F44.82 Trastornos disociativos (de conversión) transitorios de la
infancia o adolescencia
* F44.88 Otros trastornos disociativos (de conversión)
* F44.9 Trastorno disociativo (de conversión) sin especificación
Recordar que para el DSM pueden o no coexistir un Trastorno de
Conversión (eje I), un Trastorno Disociativo (eje I) y un Trastorno
Histriónico de la Personalidad (eje II).

: Recordar que en el DSM el eje I y el II son independientes (hasta
cierto punto), por lo cual se puede diagnosticar (en teoría) un
trastorno conversivo con o sin un trastorno de la personalidad
comórbido. Desde el punto de vista de la nosografía clásica no se puede
diagnosticar una neurosis histérica y un trastorno de la personalidad
histriónico.

====== DSM

En general es un diagnóstico con un criterio positivo, varios criterios
de exclusión y el requerimiento de qyue haya un malestar "clínicamente
significativo".

* Trastorno de conversión ** Inclusión: Síntoma o déficit motor
voluntario / sensorial que sugiere enfermedad neurológica + factor
psicológico asociado (con desencadenante o conflicto previo) **
Exclusión: Trastorno Facticio, Simulación, enfermedad médica o
sustancias ** Especificadores: con síntoma o déficit motor / con crisis
y convulsiones / con síntoma o déficit sensorial / de presentación mixta
* Amnesia disociativa ** Inclusión: uno o más episodios con incapacidad
para recordar información personal importante (generalmente traumático)
** Exclusión: (no aparece exclusivamente en...) Trastorno de Identidad
Disociativo, Fuga Disociativa, TEPT u otros. * Fuga disociativa: **
Inclusión: amnesia + desplazamiento geográfico + confusión sobre la
identidad personal o asunción de una nueva identidad (parcial o
completa) ** Exclusión: (no aparece exclusivamente en...) Trastorno de
Identidad Disociativo, enfermedad médica, sustancias. * Trastorno de
Identidad Disociativo: ** Inclusión: presencia de 2 o más identidades o
estados de personalidad + al menos 2 de estas identidades controlan de
forma recurrente el comportamiento del individuo + amnesia disociativa.
** Exclusión: efecto fisiológico directo de una sustancia, enfermedad
médica.

: el encare de un trastorno somatomorfo puede tener algunos puntos en
común con el encare de una neurosis histérica, pero con la nosografía
moderna quedan en categorías distintas.

==== Diagnósticos diferenciales

. Epilepsia generalizada TC (DD con crisis de EPM conversiva): por las
características reseñadas que nos permiten catalogar las crisis como
conversivas no pensamos que se trate de una crisis epiléptica. Dada la
frecuencia de coexistencia de ambas patologías realizaremos un minucioso
estudio paraclínico. Nos aleja de la epilepsia el hecho de que en las
crisis no hay pérdida de consciencia, ni mordedura de lengua, ni
incontinencia de orina, ni traumatismo al caer, ni sopor postcrítico).
Epilepsia de lóbulo temporal (DD con amnesia disociativa, fugas). .
Otros trastornos orgánicos que se manifiestan por plejias, trastornos
sensitivos, visuales, como esclerosis múltiple (20-45 años, visión
borrosa, diplopía, escotomas centrales, alteraciones sensitivas,
debilidad muscular) que evoluciona por empujes. Otros: TEC, tumores,
intoxicación, infecciones.. . Trastorno de la personalidad histriónico:
rasgos no son inflexibles ni maladaptativos, no existe pauta de
egosintonía (pide ayuda), se da en contexto intrapsíquico (no
interpersonal), por lo que lo descartamos. NOTA: no es diferencial para
la nosografía DSM. La nosografía clásica exige personalidad + síntomas,
pero la personalidad es de tipo neurótico (egodistónico, autoplástico) y
el TdelaP no (egosintónico, aloplástico). . Neurosis de angustia / otras
neurosis: el cuadro está centrado por la sintomatología
disociativa-conversiva y si existe ansiedad-angustia esta aparece
descompensando la neurosis estructurada. . Trastorno afectivo primario
(melancolía ansiosa): no existe dolor moral, la depresión es subsidiaria
del trastorno neurótico. . Síndrome amnésico orgánico: es más grave para
los hechos recientes que para los remotos, no existe selectividad, no
existe relación con desencadenantes emocionales. . Esquizofrenia
(alejado) cuando se presenta con teatralidad exagerada, sobrecargada
(pero en la esquizofrenia es por manierismo o catatonía). . Trastorno
psicótico breve: por alteración de conciencia + alteraciones
perceptivas. . Trastorno facticio / simulación (expersa voluntad de
engaño) . Otros: intoxicación alcohólica, enfermedad psicosomática.

En los diferenciales por CIE / DSM: lo orgánico, sustancias.

==== Diagnóstico etiopatogénico y psicopatológico

====== Comprensión psicológica Ey define la histeria como "una neurosis
caracterizada por la hiperexpresividad somática de las ideas, imágenes y
afectos inconscientes". Para Ey se necesitan 2 elementos para definir la
histeria: la fuerza inconsciente de la realización plástica de las
imágenes sobre el plano corporal (síntoma) y la estructura inconsciente
e imaginaria del personaje histérico (personalidad).

Para el psicoanálisis, comporta una regresión y fijación a la fase
edípica del desarrollo psicosexual. La reactivación del conflicto
sobrepasa el mecanismo de represión que no basta para contener la
angustia en el inconsciente, por lo que se recurre al mecanismo de
conversión, con el cual el síntoma somático impide el acceso a la
conciencia del conflicto rechazado, siendo el síntoma una expresión
simbólica de éste. El conflicto que no puede hacerse consciente se
disocia, refugiándose en una nueva realidad y aparece representado en
una realidad paralela con lo cual se mitiga la ansiedad. La conversión
sería la expresión somática de un conflicto inconsciente. El síntoma
somático constituye un compromiso que impide el acceso a la conciencia
del conflicto rechazado, al tiempo que implica una realización
sustitutiva y disfrazada del deseo prohibido.

Importa destacar que la sintomatología es involuntaria pero cargada de
intencionalidad inconsciente. Del diagnóstico psicopatológico
jerarquizamos los siguientes aspectos:

* Presenta como beneficio primario la disminución de la angustia o la
anulación de ésta manteniéndola fuera del campo de la conciencia. *
Presenta como beneficio secundario el manejo del entorno con lo que se
gratifican las necesidades de dependencia de la paciente, condiciona la
evolución de la dolencia, ganancia de tipo narcisista. La histeria se
modela en función de la respuesta, adaptándose al deseo del otro). Se
acompaña de "belle indiference" que es la indiferencia con respecto al
síntoma. Este mecanismo implica el uso de mecanismos de defensa como la
represión y la conversión. * Identificación con antecesor u otro enfermo

Con respecto al desarrollo de la personalidad, el Yo histérico no ha
logrado una organización estable conforme a una identificación de su
propia persona. El papel que toma como rol oculta a su persona. Hay una
gran psicoplasticidad (histrionismo) con erotización de la conducta y
los vínculos, produciéndose una "falsificación" de la existencia. Se
sustituye el principio de realidad por el deseo y la fantasía
(pensamiento imaginario). El cuerpo pasa a ser escenario de los
conflictos (disposición conversiva).

====== Comprensión biológica

Se postula la existencia de alteraciones en comunicacion
interhemisferica, hipometabolismo del hemisferio dominante,
hipermetabolismo del no dominante. Alteración de comunicación con la
sustancia reticular.

==== Paraclínica

Para: apoyar diagnóstico, descartar diferenciales, en vistas al
tratamiento, de valoración general. Se realizará desde un triple punto
de vista: biológico, psicológico y social.

===== Biológico

* Consulta con internista con EF completo, con énfasis en lo neurológico
(campo visual, pares craneanos, sensibilidad, fuerzas, reflejos),
incluyendo Fondo de Ojo. Despistaremos entidades de diagnóstico clínico
como Esclerosis Múltiple. Buscaremos signos focales, elementos de
síndrome frontal, polineuropatía sensitiva y motora, flapping, rueda
dentada, hiperreflexia, hiptertensión endocraneana, síndrome cerebelos,
etc. También buscaremos estigmas de UISP ode OH. * EEG: para despistar
foco epiléptico (con registro prolongado, con deprivación de sueño y
estimulación con hiperpnea y fotoestimulación). * Rx cráneo: valorando
repercusión de múltiples caídas. * Valoración general: hemograma,
glicemia, azoemia, creatininemia, orina completa, ionograma., funcional
y enzimograma hepático. * Infeccioso: HIV; VDRL, serología para
hepatitis. * Test de beta-HCG descartando embarazo (adolescente con
reagudización de sintomatología). * Función tiroidea. * Tóxicos en
orina.

Interconsultas con especialistas según hallazgos.

===== Psicológico

Entrevistas que tienen una finalidad diagnóstica y terapéutica. Superada
la agudeza del cuadro evaluaremos características propias del paciente,
sus capacidades y motivaciones para la psicoterapia. De ser necesario
realizaremos tests:

* Tests de Personalidad: proyectivos (TAT, Rorschach), no proyectivos
(MMPI). * Tests de Nivel (Wechsler).

En función de los hallazgos seleccionaremos el tipo de psicoterapia.

Tendremos la precaución de generar un vínculo dentro de un encuadre
adecuado, con adecuada puesta de límites y evitación de la generación de
beneficios secundarios, favoreciendo la verbalización como forma de
expresión, análisis y resolución de conflictos.

===== Social

Entrevistas con terceros, valoración de la magnitud de los beneficios
secundarios. Valoración de medio familiar, vínculos. Evaluación de red
de soporte social, inventario de eventos vitales (en particular eventos
traumáticos) y respuesta a los mismos. HC anteriores, tratamientos,
respuestas.

Indagar VD e historia de AS.

==== Tratamiento

Sintomático y etiológico. Objetivo: compensar el cuadro actual,
tratamiento enfermedad de fondo con profilaxis de recidivas y
complicaciones. El tratamiento será dinámico, adaptándose a la evolución
clínica. El tratamiento salvo excepciones se realizará de forma
ambulatoria: evitar la internación dentro de lo posible. Esta será
indicada cuando:

* Hay un IAE o alteraciones comportamentales que impliquen riesgo para
sí o terceros. * Se necesita aislamiento del foco conflictivo para
combatir el beneficio secundario que refuerza la sintomatología
(complicidad familiar inconsciente) * Si el medio es poco continente y
el cuadro es grave * Para el tratamiento y control del síndrome
depresivo y evitar sus complicaciones

De internarse será breve por alta sugestionabilidad que hace que se
alimente de las patologías de otros y la elevada tendencia a realizar un
manejo del medio. Solo deberán autorizarse acompañantes más aptos, poco
involucrado con los beneficios secundarios

====== Del cuadro actual

.Biológico

Tratamiento sintomático

* Crisis: aislamiento con protección hasta que remita. Eventualmente
puede usarse una benzodiacepina IM (Lorazepam 2mg i/m). Se debe
psicoeducar a la familia con respecto a las crisis para evitar que sean
consideradas producto de una simulación. * Ansiedad-angustia: Diazepam
para disminuir el monto de ansiedad (5-5-10) a regular según evolución
(opciones: Clonazepam, Bromazepam, Alprazolam [segunda línea por
potencial generación de dependencia]). * Depresión - ansiedad: ISRS ->
sedativos (Paroxetina, Fluvoxamina) o no-sedativos (Sertralina,
Citalopram, Fluoxetina) a dosis estándar. * En caso de Disforia
Histeroide, posibilidad de uso de IMAO: Moclobemida 300-600 mg/día (comp
150 mg) * Síntomas seudoperceptivos: hay autores que plantean uso de NL
a bajas dosis para síntomas seudoperceptivos: Haloperidol 1 mg/día.
Otros autores que afirman que los NL están contraindicados, ya que la
aparición de efectos secundarios puede agravar el cuadro preexistente.
También se postula alto grado de imprevisibilidad en la respuesta al
psicofármaco, incluso con reacciones paradojales

.Psicológico

Durante las crisis: habiendo tomado precauciones dejaremos sola a la
paciente, dado que las crisis tienen un sentido vincular al cual no
responderemos. Luego de las crisis haremos sesiones de apoyo breve.
Instruiremos a la familia sobre este punto, evitando denigrar a la
paciente, evitando que se la considere una simuladora.

Durante la internación: psicoterapia de apoyo buscando crear un vínculo
terapéutico que asegure el apego al tratamiento a largo plazo y craendo
un espacio de abordaje maduro de sus conflictos. Psicoeducación.

.Alta

Se efectuará lo antes posible. Controles quincenales que iremos
espaciando. Evitar polifarmacia. Re-evaluar la necesidad de medicación
en forma periódica.

====== De la enfermedad de fondo

Una vez superado el cuadro actual será psicológico y social
fundamentalmente.

.Psicológico

Psicoterapia de corte psicoanalítico, según: edad, nivel intelectual,
duración de la enfermedad, búsqueda de ayuda con deseo de mejoría. Los
objetivos serán mejorar los síntomas, con adecuación al medio y lograr
cambios perdurables en la estructura de su personalidad con uso de
mecanismos de defensa más adaptativos. Será fundamental una comprensión
de la sintomatología por parte de la paciente. El psicodrama como
terapia grupal puede ser beneficioso.

.Social

Si se encuentra inactiva: puede beneficiarse de laborterapia.
Desalentaremos las prácticas religiosas que favorezcan la disociación.
Terapia familiar para atacar el beneficio secundario. Psicoeducación.

==== Evolución y pronóstico

Es un trastorno crónico que evoluciona con remisiones y reapariciones
polimorfas, variadas, con recrudecimiento en relación a conflictos
psicosociales. La cronicidad de los síntomas se puede producir si se
mantienen constantes los beneficios secundarios cristalización fija.
Tiende a disminuir en la madurez. Pueden instalarse trastornos en
comorbilidad con las complicaciones consiguientes. Con psicoterapia
pueden prolongarse los tiempos libres de síntomas.

PVI y PPI: bueno con el tratamiento instituido (excepto por la
posibilidad de lesiones por autoagresión o traumatismo durante las
crisis).

PVA y PPA: depende de:

* Personalidad premórbida * Situación ambiental * Adhesión a
psicoterapia
