== Otros trastornos neuróticos

=== Trastorno de despersonalización-desrealización

==== Clínica

El individuo se queja espontáneamente de la vivencia de que su propia
actividad mental, su cuerpo, su entorno o todos ellos, están
cualitativamente transformados, de manera que se han vuelto irreales,
lejanos o mecánicos (faltos de espontaneidad). El enfermo puede sentir
que ya no es él el que rige su propia actividad de pensar, imaginar o
recordar, de que sus movimientos y comportamiento le son de alguna
manera ajenos, que su cuerpo le parece desvitalizado, desvinculado de sí
mismo o extraño, que su entorno le parece falto de colorido y de vida,
como si fuera artificial o como si fuera un escenario sobre el que las
personas actúan con papeles predeterminados. En algunos casos, el
enfermo puede sentir que se está observando a sí mismo desde cierta
distancia o como si estuviera muerto. La queja de pérdida de los
sentimientos es la más frecuente entre estos diversos fenómenos. El
número de enfermos que sufre este trastorno de forma pura o aislado es
pequeño. Por lo general los fenómenos de
desrealización-despersonalización aparecen en el contexto de
enfermedades depresivas, trastornos fóbicos y obsesivo-compulsivos.

==== Pautas para el diagnóstico

* síntomas de despersonalización tales como que el enfermo siente que
sus propias sensaciones o vivencias se han desvinculado de sí mismo, son
distantes o ajenas, se han perdido, etc.
* síntomas de desrealización tales como que los objetos, las personas o
el entorno parecen irreales, distantes, artificiales, desvaídos,
desvitalizados, etc.
* el reconocimiento de que se trata de un cambio espontáneo y subjetivo
y no ha sido impuesto por fuerzas externas o por otras personas
(persiste una adecuada conciencia de enfermedad) y
* claridad del sensorio y evidencia de que no se trata de un estado
tóxico confusional o de una epilepsia.

Incluye:

- síndrome de despersonalización-desrealización

==== Diagnóstico diferencial

* Individuo sano que experimenta la despersonalización-desrealización
como fenómeno aislado: estados fatiga, privación sensorial, fenómenos
hipnagógicos/hipnopómpicos, situaciones de peligro extremo.
* Secundaria a consumo de sustancias
* Causa orgánica: hipoglicemia, estados pre o posticales en epilepsia
del lóbulo temporal.

DD con otros trastornos en los que se vivencia un "cambio de
personalidad":

* Esquizofrenia: ideas delirantes de transformación o imposición y de
vivencias de ser controlado
* Trastornos disociativos: donde no existe conciencia de que se ha
producido un cambio
* Algunos casos de demencia incipiente.

Jerarquía: si el síndrome de despersonalización-desrealización aparece
como parte de un trastorno depresivo, fóbico, obsesivo-compulsivo o
esquizofrénico que satisfacen las pautas diagnósticas respectivas, este
último diagnóstico tiene preferencia como diagnóstico principal.
