= Clozapina
:icons: font
:pdf-theme: libro-theme.yml

== Clasificación

Antipsicótico atípico - antagonista de la serotonina-dopamina - antipsicótico de segunda generación - estabilizador del humor.

== Mecanismo de acción

< afinidad por D2, > por D1. Bloqueo 5HT2.

* Bloqueo de receptores D2, reduciendo los síntomas positivos en la psicosis y estabilizando síntomas afectivos.
* Bloqueo de receptores 5HT-2A provocando aumento de la liberación de DA en algunas áreas del cerebro reduciendo efectos motores y probablemente mejorando síntomas cognitivos y afectivos.
* Interacciones en una gran cantidad de receptores de NT
* Interacción con 5HT-2C y 5HT-1A icon:arrow-right[] puede contribuir a la eficacia para síntomas cognitivos y afectivos en algunos pacientes
* Mecanismo de acción en la refractariedad: desconocido.

== Indicaciones

=== Aprobadas
* Tratamiento de la esquizofrenia resistente / refractaria (3 tratamientos previos a dosis adecuada, duración adecuada, de antipsicóticos de 2 familias diferentes).
* Reducción de riesgo de comportamiento suicida recurrente en pacientes con esquizofrenia o trastorno esquizoafectivo

=== No aprobadas

* Tratamiento del trastorno bipolar resistente
* Paciente violentos agresivos con psicosis y otros trastornos del cerebro que no responden a otros tratamientos.

=== Otros usos

Disquinesia tardía, prevención de suicidio, trastorno esquizoafectivo refractario. Reducción en IAEs.

=== Efecto
* Síntomas psicóticos y manía: mejoría dentro de 1 semana en el uso en primera línea, con VARIAS semanas hasta que se note el efecto completo a nivel cognitivo, comportamental y afectivo (s/t en casos resistentes).
* Se recomienda esperar 4-6 semanas para determinar la eficacia
* En la práctica: 16-20 semanas para completar una prueba terapéutica en casos resistentes.
* Efecto en síntomas positivos, negativos y desorganización. 5-15% de F20 experimentan mejoría > 60% (s/t en tratamiento > 1 año) icon:arrow-right[] super-respondedores icon:arrow-right[] pueden llevar vida autónoma.

=== Ausencia de respuesta

* Niveles plasmáticos para evaluar cumplimiento
* Agregar: divalproato o lamotrigina
* Comenzar rehabilitación y psicoterapia
* Descartar UISP

TIP: Mejores combos: Divalproato, Lamotrigina, Carbamazepina / Oxcarbamazepina, Antipsicóticos típicos, benzodiacepinas, litio.

== Farmacocinética

Pico 1-4 horas, 95% de unión a proteínas, eliminación bifásica (vida media 12 horas, rango 6-33 horas). Niveles plasmáticos muy variables.

== Paraclínica
Previo al tratamiento:

* Hemograma: leucocitos >= 3500/mm3 y recuento diferencial normal.
* Peso, IMC, circunferencia abdominal, PA
* Glicemia
* Perfil lipídico
* ECG
* FyEH

Derivar pacientes de riesgo metabólico a nutricionista.

WARNING: Pacientes de riesgo: IMC > 25, prediabetes (glicemia 100-125 mf/dl), HTA, dislipemia.


== Dosis

Inicio: 25 mg/día (en 2 dosis), aumentos de 25 mg/día por medio hasta llegar a 300-450 mg/día.

En fase inicial 450-600 mg/día máximo.

Luego: máximo 900 mg/día.

Semanas 1-2: 300 mg/día (100 mg c/8)

Semanas 3-4: 400-500 mg/día y dejar un período de observación antes de aumentar la dosis.

En caso de abandono > 2 días: retomar a menor dosis.

Discontinuación: reducción gradual en 1-2 semanas. Si está indicada la discontinuación abrupta, continuar monitorizando efectos secundarios y síntomas psicóticos. Si se interrumpió el tratamiento por más de 1 semana comenzar con titulación inicial de dosis. Tomar precauciones extras ya que los efectos adversos pueden intensificarse. Puede haber psicosis de rebote al retirar rápido. Luego de interrumpir: controles 1 vez x semana x 1 mes.

Administración: 1 vez al día hasta 300 mg, luego dividido sin dosis > 300 mg x > riesgo de convulsiones.
Con o sin comidas. No usar jugo de pomelo.

Dosis > 550 mg pueden requerir de adiminstración concomitante de anticonvulsivante para reducir probabilidad de convulsiones.

== Efectos secundarios

Por bloqueo: H1 (sedación), alfa-1 A (mareo, sedación, hipotensión), muscarínicos-1 (boca seca, constipación, sedación, íleo paralítico), muscarínicos-3 icon:arrow-right[] probable efecto metabólico.

=== Más importantes:

* Aumento de riesgo de diabetes y dislipidemia
* Aumento de salivación (puede ser severo)
* Sudoración, mareos, sedación, cefaleas, taquicardia, hipotensión, náuseas, constipación, boca seca, auemtno de peso.

=== Más riesgosos:

* Hiperglicemia con cetoacidosis
* Agranulocitosis
* Convulsiones
* SNM (s/t en uso con otros AP)
* TEP
* Miocarditis
* Ileo paralítico
* Aumento de riesgo de ACV en pacientes con demencia

=== Que pueden causar abandono

* Aumento de peso
* Sedación

== Precauciones
Glaucoma de ángulo cerrado, trastornos CV, trastornos renales o hepáticos, hipertrofia prostática. Conducción de maquinaria. Historia de convulsiones. Eosinofilia, trombocitopenia. Niños, ancianos, embarazo, lactancia.

== Interacciones

Metabolizado por: 1A2, 2D6, 3A4

* Inhbidores de 1A2 (Fluvoxamina): bajar dosis de CLZ
* Inductores 1A2 (tabaquismo): aumentar dosis de CLZ
* Inhibidores 2D6 (Paroxetina, Fluoxetina, Duloxetina) en general no se necesita ajustar dosis de CLZ.
* Inhibidores 3A4 (Nefazodona, Fluvoxamina, Fluoxetina) en general no se necesita ajustar dosis de CLZ.
* CLZ puede aumentar efecto de antihipertensivos.

Otros:
Alcohol, depresores del SNC, anticolinérgicos. Drogas que deprimen MO. IMAOs, narcóticos, antihistamínicos, BZD, anticolinérgicos, antihipertensivos, adrenalina, depresores respiratorios. Warfarina. Fármacos con alta unión a proteínas, cimetidina, fenitoina, CBZ, eritromicina, ISRS, litio.
No administrar CBZ ni DFH para tratar convulsiones.

Precaución: otros agentes que puedan causar agranulocitosis, glaucoma, prostatismo.

== Contraindicaciones

* Hipersensibilidad previa a la Clozapina o a cualquier otro componente de las formulaciones.
* Historia de granulocitopenia o agranulocitosis tóxica o idiosincrática (excepto granulocitopenia o agranulocitosis por quimioterapia previa). Alteraciones funcionales de la médula ósea. Trastornos mieloproliferativos.
* Epilepsia no controlada.
* Psicosis alcohólica y otras psicosis tóxicas. Intoxicación por fármacos.
* Condiciones comatosas. Colapso circulatorio. Depresión del SNC.
* Enfermedad renal o cardíaca severa. Enfermedad hepática activa asociada con náuseas, anorexia o ictericia, enfermedad hepática progresiva, insuficiencia hepática.
* Ileo paralítico


== Monitorización

* Hemogramas (ver más abajo)
* IMC mensual x 3m y luego c/4 meses
* Perfil lipídico mensual por 6m en pacientes de riesgo metabólico.
* PA, glicemia, perfil lipídico en 3m y luego anual.


=== Hemogramas: nuevas pautas 2015

==== Neutrófilos ≥ 1500/mm3

* Recomendación: iniciar / continuar tratamiento
* Monitoreo:
** Semanal hasta los 6 meses
** Quincenal hasta 1 año
** Mensual mientras continúe el tratamiento

==== Neutropenia leve: 1000-1499/mm3

* Recomendación: continuar
* Monitoreo:
** Repetir hemograma en el día
** 3 hemogramas por semana hasta ≥ 1500/mm3

==== Neutropenia moderada: 500-999/mm3

* Recomendación: INTERRUMPIR CLOZAPINA
** Consulta con hematólogo
** Se puede retomar con neutrófilos ≥ 1000/mm3
* Monitoreo
** Repetir hemograma en el día
** Hemograma diario hasta ≥ 1000/mm3
** Luego 3 hemogramas por semana
** Luego hemograma semanal por 4 semanas
** Luego hemograma mensual

Neutropenia severa: < 500/mm3

* Recomendación:
** Consulta con hematólogo
** No retomar a menos que los beneficios superen los riesgos
* Monitoreo
** Repetir hemograma en el día
** Hemograma diario hasta ≥ 1000/mm3
** Hemogramas 3 por semana hasta ≥ 1500/mm3
*	* Si se retoma: hemograma semanal como al inicio

.Reinstauración
Luego de retirar por leucopenia: monitoreo semanal por 12 meses.

== Presentaciones

Comprimidos de 25mg]: Luverina.
Comprimidos de 100 mg: Leponex*, Luverina

== Situaciones clínicas especiales

=== Nueva prueba con Clozapina luego de eventos adversos significativos
En una revisión [^1] se encontraron 138 pacientes esquizofrénicos que retomaron el tratamiento con Clozapina luego de desarrollar neutropenia (112), agranulocitosis (15), síndrome neuroléptico maligno (5), miocarditis (4), pericarditis (1) y lupus eritematoso (1). El reinicio del tratamiento fue exitoso en 78/112 pacientes (69.6%, IC: 60.6–77.4) luego de una neutropenia; 3/15 (20%, IC: 7.1–45.2) luego de una agranulocitosis; 5/5 (100%, IC: 56–100) luego de un SNM, 3/4 (75%, IC: 30–95) luego de una miocarditis, 1/1 luego de una pericarditis y 0/1 luego de un lupus inducido por clozapina. Los pacientes se siguieron por 16–96 semanas. Ninguno de los pacientes murió. En suma: excepto en los casos de agranulocitosis o miocarditis, se podría reconsiderar reiniciar clozapina luego de un evento adverso.

=== Pacientes añosos
Mayor mortalidad con el uso de antipsicóticos atípicos.

=== Otros
Embarazo: B. En RN de madres tratadas con CLZ mayor riesgo de movimientos anormales, alteraciones en tono muscular, somnolencia. Uso: solo si beneficio > riesgo.

Lactancia: desconocido. Se asume que pasa a la leche. Se recomienda discontinuar o suspender lactancia.
Bibliografía

* Folletería del laboratorio (Leponex(r) - Sandoz).
* Manu, P., Sarpal, D., Muir, O., Kane, J. M., & Correll, C. U. (2012). When can patients with potentially life-threatening adverse effects be rechallenged with clozapine? A systematic review of the published literature. Schizophrenia research, 134(2-3), 180-186.
* Meltzer H. Suicide in Schizophrenia: Risk factors and clozapine treatment. J Clin Psychiatry 1998:59 (Suppl 1).
* Meltzer H. et al. Reduction of suicidallity during clozapine treatment of neuroleptic resistant Schizophrenia. Am J Psychiatry 1995:152 183-190
* Stahl, Stephen M. Prescriber's Guide: Antidepressants: Stahl's Essential Psychopharmacology. Cambridge University Press, 2017.
