== Confusión Mental

=== Notas clínicas

=== Encare

==== En suma

Destacar algo de la patología orgánica (alcoholismo, infección, TEC, anciano, postoperatorio, fiebre, deshidratación, IAM, AVE, diabetes, EPOC).

Destacar la agudeza de la instalación y lo fluctuante.

==== Agrupación sindromática

===== Síndrome confuso-onírico

El paciente se encuentra sumergido en un trastorno global y profundo de la conciencia, de instalación brusca, de x tiempo de evolución, con síntomas fluctuantes, configurando:

.Síndrome confusional
Evidenciado en:

Presentación

Una mirada ausente, lejana, perdida, con facies perplejo, comportamiento oscilante entre una agitación desordenada e inhibición marcada, con vestimenta desordenada (con medidas de contención física). Por momentos sale de ese estado y hace esfuerzos por captar lo que sucede a su alrededor con gran ansiedad. Esto denota una transitoria mejoría donde tiene conciencia de morbidez, con un aumento del juicio y la autocrítica, configurando una perplejidad ansiosa, intento de poner en orden la confusión de sus pensamientos.

Conciencia

Obnubilada, embotada, con falta de lucidez y de claridad del campo de la conciencia. No puede presentificar la entrevista y no tiene conciencia de morbidez, con imposibilidad de efectuar una síntesis adecuada de los contenidos psíquicos. Oscila hacia un estado de transitoria mejoría pasando por la perplejidad ansiosa. A partir de este trastorno fundamental derivan los otros elementos del síndrome.

Atención

Incapacidad de dirigir la atención y mantenerla concentrada en un objetivo. Gran distraibilidad. Se afecta la atención voluntaria y la espontánea.

Memoria

Alteración de la memoria de fijación, con una evocación penosa y dificultosa, produciéndose falsos reconocimientos y fabulaciones en el intento de ordenar los pensamientos (luego queda amnesia del episodio).

Orientación

Desorientación autopsíquica (es la última en perderse y es indicador de gravedad) y alopsíquica (espacial y temporal).

Pensamiento

Puesto de manifiesto por el lenguaje, el cual es desordenado, fragmentario. en el pensamiento reconocemos elementos que describiremos a continuación, como un síndrome delirante con características particulares.

Afectividad

Un afecto fluctuante entre la tranquilidad, la irritación, la agitación ansiosa y la perplejidad.

Psicomotricidad

Oscilante entre una gran agitación principalmente nocturna, con grados variables de desorden y una inhibición.

Todo esto nos traduce la incapacidad del paciente de ordenar y sintetizar su vida psíquica en el aquí y ahora, con pérdida de la unicidad y el orden de los contenidos psíquicos, los que se aglutinan y confunden, mostrándonos la vivencia de un mundo caótico y fragmentado.

.Síndrome delirante onírico

Sobre la alteración descrita reconocemos un conjunto de ideas y vivencias mórbidas, de instalación brusca, incompartibles, irreductibles a la lógica, carentes de juicio de realidad, que le generan conductas, que vive con convicción, vivencias que calificamos como delirantes.

Este delirio es a temática laboral, profesional, zoopsias (90% son orgánicas), erótica, mística, celos, ideas aterradoras. El mecanismo es sobre todo alucinatorio visual y auditivo, pero también con ilusiones (dismorfopsias, dismegalopsias), con una mala sistematización, sin orden, coherencia ni claridad.

Este delirio tiene una característica peculiar que nos remite al ensueño. Se presenta como una sucesión de imágenes alucinatorias encadenadas escénicamente, es fragmentario, fluctuante, oscilante, en oleadas, caótico. El paciente está íntimamente adherido a él, se entrega plenamente a él, manifestándolo no solo por su relato, sino que lo vive y actúa (habla, trabaja, deambula, agrede, grita, huye, pide ayuda, da órdenes). Presenta fuerte carga emocional ansiosa, exacerbándose de noche, con predominio en la fase hipnagógica.

El cuadro tiene ___ días de evolución, con alteración de las conductas basales (inversión del ritmo circadiano, anorexia).

===== Síndrome somático

Destacar aquí todos los elementos que pueden ser causa del cuadro clínico.

Destacar si existe adelgazamiento, fiebre, temblor, deshidratación, postoperatorio o preoperatorio, traumatismos, síndrome de abstinencia alcohólica, repercusión orgánica del alcoholismo (endócrino, cardiovascular, digestivo).

===== Síndrome conductual

Cuadro actual

Lo relacionado al motivo de consulta. Conductas basales y pragmatismos.

Curso de vida

Poner conductas vinculadas a consumo de alcohol y otras sustancias. Describir patrón de consumo. Destacar conductas que sean factores de riesgo par ETS.

==== Personalidad y nivel

Puede presentarse en cualquier patrón de personalidad y en cualquier nivel intelectual.

==== Diagnóstico positivo

===== Nosografía clásica

.Psicosis
El paciente presenta una psicosis ya que se encuentra sumido en un mundo propio, incompartible, con el que se relaciona de una manera nueva, por él creada, del que no puede salir voluntariamente, con pérdida del juicio de realidad, con presencia de delirio, sin conciencia mórbida, estableciendo con el paciente un mal rapport.

.Aguda
Por tratarse de una experiencia sensible y actual, intensamente vivida, cursando con oscilaciones, variabilidad y fluctuaciones del estado de conciencia, de X tiempo de evolución, con compromiso de las conductas basales.

.Confusión mental
Otros nombres: psicosis confusional, psicosis confuso-onírica, delirium.
Por el síndrome confuso-onírico. Es un diagnóstico inespecífico en lo nosográfico, pero que implica gravedad.

.Causa
Es un cuadro de causa orgánica, en general multifactorial, estando involucrados factores de riesgo tales como: adad (adulto mayor), consumo de sustancias, abstinencia de sustancias, psicofármacos, patología médica (fiebre, sepsis, EPOC, IAM, arritmias, ACV, AIT, TEP).

==== Diagnósticos diferenciales

. Otras casusas de confusión mental: no nos impresiona clínicamente por los elementos analizados, pero que descartaremos por la paraclínica: anemia carencial o por sangrado, infecciones, TEC, drogas, medicación, hepatopatía, endocrinopatía, disionías (encefalopatía por derivación porto-cava, descompensación de una hepatopatía crónica, con flapping y otros signos de hepatopatía, es por hiperamoniemia). Si debemos destacar factores de comorbilidad.
. Otras cuadros vinculados con alcohol (si es un DASA).
.. Delirium Tremens: no pensamos, pues si bien es un cuadro confusional guado que complica la evolución del alcoholismo crónico vinculado a un período de abstinencia con delirio onírico, es más grave, con deshidratación, alteraciones hemodinámicas, alteraciones neurovegetativas, fiebre de 40°C, temblor intenso, agitación intensa y agotadora e insomnio. La evolución del delirium tremens puede ser favorable (sueño, apirexia, desaparece la confusión) o desfavorable (hipertermia, convulsiones, PCR).
.. Alucinosis de los bebedores de Wernicke: es una psicosis alucinatoria, complicación aguda del alcoholismo crónico, vinculado a un cambio en la ingesta, con alucinaciones, pero cursa sin confusión mental, las alucinaciones son auditivo-verbales, hostiles, hipnagógicas, con ansiedad y son parcialmente criticadas. Sería un síndrome de automatismo mental subagudo. Puede evolucionar a la mejoría, a la esquizofrenia o a la cronicidad.
.. Encefalopatía de Wernicke: clínicamente reconocida por la existencia de Confusión Mental (puede ser solo desorientación TE) + oftalmoplejia (parálisis del 3° par, con diplopía y debilidad a la conjugación) + nistagmo + ataxia postural y de la marcha. Es por carencia de vitamina, reversible, puede evolucionar a Korsakoff.
. Otras psicosis agudas: no pensamos que se trate de otra psicosis aguda (manía, melancolía, delirante aguda) dado que predomina el trastorno de la conciencia y las características oníricas del delirio.
. Psicosis crónicas:
.. Encefalopatía de Korsakoff (Psicosis de Korsakoff): irreversible. Síndrome amnésico persistente + polineuropatía de MMII. El síndrome amnésico es anterógrado y retrógrado, con falsos reconocimientos, fabulaciones e incapacidad para la adquisividad. Es por carencia de Tiamina, es de mal pronóstico (ponerla en la evolución).
.. Demencia: comparte el trastorno de memoria pero la demencia tiene además: inicio gradual, tiempo de evolución prolongado, vigilia mantenida, la OTE se mantiene, la atención conservada, pensamiento más pobre que desorganizado, el sueño conservado, cuadro clínico fijo, con indiferencia y conformismo (pueden coexistir).
.. Esquizofrenia descompensada: pensamos en ella por las alucinaciones, pero nos aleja el trastorno de conciencia, el delirio onírico, la fluctuación, la causa orgánica reconocida, la falta de una historia longitudinal de déficit.

Hay que tomar en cuenta que durante la confusión mental, no se puede identificar clínicamente estructuras psicopatológicas subyacentes, por lo cual hay diagnósticos que solo se pueden realizar luego de que cede el cuadro agudo.

==== Diagnóstico etiopatogénico y psicopatológico

El delirium es un cuadro de expresión clínica psiquiátrica que tiene una etiología orgánica. Es la manifestación de una noxa principalmente biológica. Es la forma inespecífica de reacción del encéfalo vulnerable ante una noxa que supera las reservas funcionales del mismo. Se produce un disblance entre las diferentes redes neuronales de los sistemas subcorticales homeostáticos y del córtex y de las funciones neuroendócrinas (electrolíticos, eje hipotálamo-hipofiso-suprarrenal y nutricionales). La causa de los síntomas se desconoce.

Causas de delirium

1. Tóxicas: alcohol, UISP, medicamentos (sedantes, anticolinérgicos, corticoides, antiparkinsonianos).
2. Infecciosas: por la fiebre, por la acción del agente sobre el SNC, debido a sepsis (IU, neumonia, meningitis, HIV, neurosífilis, encefalitis por herpes, TBC).
3. Enfermedad vascular: ACV, AIT, IAM, ICC, arritmias, HTA, eclampsia.
4. Endócrinas: diabetes, hipertiroidismo, hiperparatiroidismo.
5. Metabólicas: hipoglicemia, trastornos hidroelectrolíticos.
6. Otras: EPOC, anemia carencial o por sangrado, encefalopatía por hepatopatía crónica.

Psicopatología

Para la Teoría Organodinámica de Ey, el delirium comporta una desestructuración del campo de la conciencia de 3° nivel, siendo la confusión el aspecto deficitario, negativo, pero fundamental, del cuadro. El delirio onírico es el aspecto positivo, que se manifiesta al tiempo que el campo de la conciencia se desorganiza y se estrecha. Es una experiencia cercana al ensueño, pero más desorganizada y superficial. El individuo se incorpora a los contenidos de su delirio (representantes de sus fantasías inconscientes) y los actúa.

Quedan en un segundo plano los determinantes psicológicos y sociales intercurrentes, si bien siempre influyen en la vulnerabilidad. Destacar patología psiquiátrica previa, trabajo (riesgo vinculado a determinadas profesiones).

==== Paraclínica

El diagnóstico es clínico.

La paraclínica está destinada a realizar una valoración general del paciente, investigar la causa orgánica, los factores de comorbilidad, descartar diferenciales y con miras a los diferentes recursos terapéuticos de los que disponemos, sin retrasar el inicio del tratamiento dada la gravedad del cuadro.

La solicitaremos desde un punto de vista integral: biológico, psicológico y social, orientada por los diagnósticos hechos hasta ahora.

Solicitaremos la historia clínica previa o su resumen para objetivar los antecedentes clínicos y de tratamiento. Entrevistaremos a terceros para clarificar los desencadenantes y antecedentes del cuadro actual.

===== Biológico

Realizaremos una anamnesis médica somática al paciente o terceros y un examen físico completo con énfasis en la búsqueda de estigmas de alcoholismo, signos de infección y los elementos planteados como etiológicos.

Neurológico (polineuropatía sensitiva y motora, flapping, rueda dentada, hiperreflexia, hipertensión endocraneana, síndrome cerebeloso, TEC).

Focos infecciosos (deshidratación, fiebre).

Cardíaca: HTA, arritmias, cardiomegalia, insuficiencia cardíaca.

Pleuropulmonar: EPOC

Insuficiencia hepatocítica: hieprestrogenismo, coagulopatías, equimosis, palmas hepáticas, ictericia, angiomas estelares, telangiectasias, ginecomastia, vello ginoide, atrofia testicular.

Hipertensión portal: ciculación colateral, hepatomegalia, esplenomegalia.

Digestiva: pancreatitis, gastritis, esofagitis, várices esofágicas.

Estigmas de UISP.

Elementos que nos pondrán en la pista de una patología potencialmente reversible determinante de la la expresión clínica actual.

Realizaremos valoración general:

Hepática: funcional y enzimograma hepático.

Crasis sanguínea: tiempo de protrombina aumentado, factores / vitamina k disminuidos.

Metabólica: glicemia, ionograma (Ca, Mg, Zn: son cofactores de Vitamina B), proteinograma (albúmina baja).

Hematológica: hemograma con lámina (anemia macrocítica, VCM aumentado que se normaliza luego de la abstinencia).

Renal: azoemia, creatininemia, orina (las vitaminas son hidrosolubles).

Infecciosa: VES, VIH, VDRL (cuando la situación clínica lo determina: HVB, HVC).

ECG, fondo de ojo.

Se evaluará la necesidad de RxTx, EEG, TAC, RMN (hematoma subdural, atrofia cortical, búsqueda de otras drogas o fármacos en sangreo/orina).

Si es pertinente: test de embarazo.

Algunos de estos exámenes pueden diferirse.

De haber algún valor fuera del rango normal, evaluaremos la necesidad de interconsulta con especialistas (gastroenterólogo, neurólogo, cardiólogo, internista, nutricionista).

===== Psicológico

Las entrevistas tienen una finalidad terapéutica y diagnóstica simultáneamente. Serán reiteradas tanto para completar el diagnóstico como para afianzar el vínculo. Superada la agudeza del cuadro actual evaluaremos las características propias del paciente y sus capacidades y motivaciones para una de las diferentes líneas de psicoterapia.

Si fuera necesario realizaremos en diferido test de personalidad proyectivos (Rorschach, TAT) y no proyectivos (Minnesotta), que nos informarán sobre los mecanismos de defensa, integridad del yo, rasgos de personalidad, tolerancia a la frustración. Si fuera necesario realizaremos en diferido test de nivel.

===== Social

Realizaremos entrevistas con familiares a los efectos de valorar la repercusión del alcoholismo en: red de soporte social y económica, red de vínculos y dinámica familiar, desempeños habituales, características de los tratamientos previos y sus resultados.

==== Tratamiento

Es una urgencia médica con riesgo vital.

El tratamiento será dinámico, adaptado constantemente a la evolución clínica y a la aparición de complicaciones, será en las áreas biológica, psicológica y social, integrado por recursos farmacológicos, psicológicos y sociales.

Con directivas inmediatas y a largo plazo.

Directivas inmediatas: tratamiento etiológico, remisión del cuadro sintomático acortando la duración del episodio, tratamiento de la comorbilidad y factores intercurrentes, prevención de complicaciones, abstinencia alcohólica total.

Directivas a largo plazo: reinserción del paciente en su mejor nivel de desenvolvimiento en su vida, prevención y tratamiento de comorbilidad y complicaciones crónicas, abstinencia alcohólica total.

Lo internaremos, según la gravedad en sala de medicina, CI o CTI por: ser un cuadro grave de etiología orgánica, necesitar para su tratamiento de un equipo interdisciplinario, estar delirando/agresivo/ansioso, acceder fácilmente a interconsultas y paraclínica.

Lo ideal sería en una sala individual, bien iluminada (la deprivación sensorial aumenta los síntomas), sin elementos de riesgo para sí y el personal (ventanas, espejos), con asistencia de enfermería especializada las 24 horas, con medidas orientadoras (almanaque, reloj, acompañante continentador las 24 horas).

Paciente en cama semisentado, evitaremos en lo posible las medidas de contención físicas, pues exacerban los síntomas. El personal de enfermería especializado en salud mental vigilará la prevención de intentos de fuga, auto y heteroagresividad. Controles vitales (temperatura, pulso, PA, diuresis). Adecuado aporte nutricional. Verificación de toma de medicación.

Biológico

Adaptar según el cuadro de base.
