=== 12 Fobia social

==== Notas clínicas

===== Definición
Temor ante situaciones que requieren exposición social: iniciar o mantener conversaciones, participar en pequeños grupos, tener citas, hablar con figuras de autoridad, asistir a fiestas. Percepción del temor como irracional o exagera-do. Preocupación por la posibilidad de estar en una situación embarazosa o que los demás le vean como ansioso, débil, “loco”. Temor a que los demás se den cuenta de que sus manos tiemblan. Temor a no poder articular correctamente las palabras. Pueden evitar: comer, beber, escribir en público. Síntomas de ansiedad ante la exposición: palpitaciones, temblores, sudoración, molestias gastrointestinales, diarrea, tensión muscular, rubor. Temor a evaluaciones indirectas (exámenes). De forma típica aparece en la adolescencia (rango 5 a 35 años) con el antecedente de timidez o inhibición social en la infancia. La aparición puede estar marcada por algún su-ceso vivido como humillante.

====== Curso
Crónico o continuo (puede oscilar por circunstancias ambientales, por ejemplo: disminución del temor ante conversaciones con personas del sexo opuesto que desaparece luego de casarse; cambio de puesto laboral que obliga a interactuar con público).

Examen psiquiátrico Dificultad para sostener la mirada. Comprobación de manifestaciones objetivas de ansiedad (rubor, manos pegajosas y frías, temblor, voz vacilante). Afectación de pragmatismos.

===== Epidemiología

Prevalencia: 3-13%. Síntoma más frecuente: temor a hablar en público. Prevalencia a 6 meses: 2-3% de población general. En estudios epidemiológicos: mujeres > hombres. En mues-tras clínicas: hombres > mujeres (causa de variación: desconocida). Prevalencia de aproximadamente un 10% en pacientes con otro trastorno de ansiedad. Mujeres con FS tienen más probabilidades de desarrollar una Agorafobia.

==== Encare

===== Agrupación sindromática

====== Síndrome fóbico

Entendiendo por fobia, la presencia de un temor irracional y exagerado con objeto colocado en el exterior que le genera conductas de evitación y de tranquilización. De X tiempo de evolución dado por:

* Temor irracional intenso, independiente del control voluntario
* Reconocido como absurdo por parte del paciente
* Originado por objeto o situación que en sí misma no tiene características de peligrosidad
* Cuya presencia desencadena crisis de ansiedad-angustia que puede tomar forma de crisis de pánico.
* Que desaparece al margen del objeto-situación (lo que favorece la aparición de conductas de evitación).
* Que genera conductas tranquilizadoras: elementos que cumplen función aseguradora de protección: personaje, habitación, objeto, ingesta de alcohol.

En este caso la ansiedad se vincula a situaciones sociales y se presenta como miedo a ser examinado por otras personas, que conduce a evitar situaciones de encuentro social. Puede estar asociado a baja autoestima y temor a las críticas. Se presenta generalmente en situaciones tales como comer o hablar en público, encontrarse con conocidos en público o introducirse o permanecer en actividades de grupo reducido (fiestas, reuniones de trabajo, clases). Se destaca la presencia de elementos somáticos tales como: ruborización, temblor de manos, náuseas o urgencia miccional. Afecta de X modo los pragmatismos.

====== Síndrome de ansiedad-angustia

Bajo la forma de ansiedad anticipatoria (vinculada a síndrome fóbico), ansiedad generalizada (ver F41.1) o crisis de pánico (ver F41.0).

====== Síndrome conductual

Subsidiario de la fobia ya analizada

* consumo de alcohol y/o benzodiacepinas
* pragmatismos: indican gravedad de la fobia, de X evolución

====== Síndrome depresivo

Secundario a la sintomatología de ansiedad (o en comorbilidad).

===== Personalidad y nivel

Nivel: cualquiera (independencia de ejes I y II).

Personalidad: susceptibilidad a la crítica aumentada, susceptibilidad a la valoración negativa por parte de los demás. Temor al rechazo. Dificultad para autoafirmarse y baja autoestima.

===== Diagnóstico positivo

====== Nosografía Clásica

Neurosis
Neurosis fóbica

Gravedad

Leve-moderada-grave- incapacitante.

Descompensada

Por:

* Síndrome de ansiedad angustia
* Depresión (disfórica)
* Exacerbación de síntomas

====== DSM-IV - CIE-10

F40.1: Fobia social Entendiendo por fobia social el temor irracional persistente y reconocible de turbarse o verse humillado cuando se desempeña en situaciones sociales.

DSM-IV

A. temor acusado y persistente por una o más situaciones sociales o actuaciones en público en las que el sujeto se ve expuesto a personas que no pertenecen al ámbito familiar o a la posible evaluación por parte de los demás. Teme actuar de un modo que resulte humillante o embarazoso
B. la exposición provoca respuesta de ansiedad (con o sin crisis de pánico)
C. reconoce que el temor es excesivo o irracional
D. evitación (o las soporta con malestar intenso)
E. interferencia con desempeño
F. más de 6 meses en menores de 18 años
G. descartar sustancias, enfermedad médica y otros trastornos mentales
H. si hay otro diagnóstico, la fobia no se relaciona con estos procesos (por ejemplo, el miedo no es debido a tartamudez o a exhibición de conductas vinculadas a un trastorno de la alimentación)

Especificadores: generalizada: si los temores hacen referencia a la mayoría de las situaciones sociales.

CIE-10

Requiere:

A. Dos criterios:
1. Miedo marcado a ser foco de atención o miedo a comportarse de un modo que sería embarazoso o humillante.
2. Evitación notable de ser el centro de atención, o de situacio-nes en las cuales hay miedo de comportarse de un modo que sería embarazoso o humillante.
B. Uno de los síntomas siguientes: ruborización, temor a vomitar, necesidad imperiosa o temor a orinar o defecar.
C. Malestar significativo.
D. Los síntomas se limitan a las situaciones temidas o a la contemplación de las mismas.
E. Exclusión de: trastornos mentales orgánicos, esquizofrenia, trastornos afectivos, TOC, factores culturales.

===== Diagnósticos diferenciales

Nosografía clásica

1. Neurosis de angustia: no existen conductas de evitación ni tranquilización. En la NF los elementos de AA son subsidiarios al síndrome fóbi-co que aparece descompensando. En la NA no existen mecanismos de defensa estructurados.
2. Otras neurosis.
3. Fobia sintomática de Trastorno de la Persona-lidad.
4. Crisis de angustia: descartar origen orgánico:

* Hiperglicemia
* Feocromocitoma
* Prolapso de válvula mitral (comorbilidad)
* Hipertiroidismo
* Drogas: abstinencia (barbitúricos, benzodia-cepinas), intoxicación (anfetaminas y simi-lares)

5. Si hay un So depresivo: Trastorno afectivo primario

DSM / CIE-10

Los diagnósticos diferenciales son diferentes dado que estos sistemas clasificatorios permiten acumular diagnósticos en uno o más ejes. Los principales diagnósticos diferenciales son:

. Entre los diferentes trastornos de ansiedad:
.. Agorafobia con/sin crisis de pánico: aparición de crisis de angustia inesperada que no se limitan al contexto de interacciones sociales. En la Fobia Social no hay crisis inesperadas recidivantes. Si se cumplen ambos criterios, pueden diagnosticarse a la vez.
.. Fobia específica: x ej. evitación limitada a situaciones aisladas (ascensores).
.. TOC: x ej. evita situaciones vinculadas a obsesión (evita suciedad si hay ideas obsesivas de contaminación.
.. TEPT: evitación de estímulos relacionados con situación altamente estresante o traumática.
.. Trastorno por ansiedad de separación: evitación de abandonar el hogar o la familia.
. Causas médicas
. Inducidos por sustancias
. Trastorno Esquizoide de la Personalidad: se evitan situaciones sociales por falta de interés por relacionarse con los demás.
. Como diagnósticos adicionales (más que diferenciales) considerar Trastorno de la Personalidad del grupo C (sobre todo TP por Evitación). Existe cierto consenso en considerar al TPE como una forma crónica de Fobia Social (ya que responde al mismo tipo de tratamiento).
. Otros diagnósticos que pueden tener síntomas en común o estar presentes por comorbilidad: Trastorno Depresivo Mayor, Trastorno Distímico, Trastorno Dismórfico Corporal, Trastornos Alimentarios, temor o vergüenza asociada a patología médica (obesidad, estrabismo, cicatrices faciales).
. Normalidad: temor a actuar en público, temor a escenarios o timidez en reuniones sociales donde no participan personas del entorno familiar. No deben calificarse como Fobia Social a menos que interfieran significativamente con el funcionamiento del individuo.

===== Etiopatogenia y psicopatología

Se propone una gran heterogeneidad causal, aplicándose en general el modelo de estrés-diátesis. Los modelos vigentes apuntan a interacción entre mecanismos ambientales, biológicos, cognitivos y comportamentales . Los eventos sociales se presentarían como amenazantes, activando los circuitos innatos vinculados a la ansiedad (punto de acción de los ISRS, IMAOs, Benzodiacepinas y alcohol), lo que genera a través de vías corticales, cogniciones negativas (punto de acción de la Psicoterapia Cognitiva). A su vez, por activación del sistema nervioso autónomo (punto de acción de beta bloqueantes) se produce el aprendizaje de conductas de evitación (punto de acción del entrenamiento en habilidades sociales y de la Terapia Comportamental).

====== Biológico

Algunos autores proponen un modelo vulnerabilidad-estrés, citando una predisposición constitucional en personas que nacen con un temperamento específico conocido como "inhibición conductual a lo desconocido", que ante factores de estrés constituirían una fobia. Este patrón conductual se observa frecuentemente en niños cuyos padres están afectados por un trastorno de angustia.

.Genética
Los factores genéticos son más importantes en el subtipo de FS generalizada. EL riesgo para familiares de pacientes con FSG es 10 veces mayor. Hay alta concordancia entre gemelos monocigóticos. Los familiares de primer grado de pacientes con fobia social tiene 3 veces más probabilidades de tenerlas que los familiares de personas sanas. Para el caso de la fobia social, diversos autores postulan la existencia de alteraciones en sistemas de neurotransmisión (adrenérgico, serotoninérgico y dopaminérgico), basado en la eficacia de fármacos.

.Pruebas de estimulación:

* Lactato: similar respuesta que en controles, lo que indicaría ausencia de alteraciones en quimiorreceptores (a diferencia del Tras-torno de Pánico).
* CO2: Mayor respuesta que controles, pero menor que pacientes con TP.
* Colecistoquinina (CCK): resultados contra-dictorios.
* Cafeína: igual respuesta que en TP y mayor respuesta que en controles.
* Epinefrina: resultados contradictorios.

.Sistema adrenérgico
Basado en la eficacia de antagonistas beta-adrenérgicos (Propranolol) para fobias de ejecución (éstos pacientes liberarían más adrenalina tanto a nivel central como periférico). La estimulación beta adrenérgica periférica provocaría sudoración, temblor y rubor. La clonidina (antagonista alfa2 adrenérgico) alivia síntomas tales como la sudoración axilar. Los sujetos con FS presentan una respuesta de PA exagerada ante una maniobra de Valsalva y una menor disminución de la PA al pasar a posición de pie en relación a controles normales.

.Sistema GABA
Las pruebas de estimulación con el antagonista gabaérgico Flumazenil muestra un aumento de los síntomas de ansiedad en relación a controles normales. Sistema dopaminérgico: basada en la eficacia de los IMAO y del Bupropion para el tratamiento de la Fobia Social generalizada. Además se cita como evidencia:

* Desarrollo de síntomas de ansiedad social luego del tratamiento con fármacos que bloquean la Dopamina
* Correlación existente entre rasgos de intro-versión y bajos niveles de Dopamina en el LCR
* Altas tasas de Fobia Social en pacientes con Enfermedad de Parkinson.
* Baja actividad dopaminérgica detectada en cepas de ratones "tímidos"
* Bajos niveles en LCR de ácido homovanílico en pacientes con T de Pánico y Fobia Social.
* En SPECTs aparece una disminución en la densidad de sitios de recaptación de Dopa-mina a nivel del estriado.

.Sistema serotoninérgico
Basada en la eficacia de los ISRS. Los sujetos con FS expuestos a Fenfluramina (agente liberador de serotonina) aumentan los síntomas de ansiedad en relación a con-troles (podría indicar hipersensibilidad de receptores 5HT2), dado que esto se contradice con el efecto terapéutico de los ISRS, pero se interpreta esto como el efecto de 2 vías serotoninérgicas diferentes, siendo el efecto terapéutico en la FS proporcional a la importancia de cada vía en el trastorno. Se plantea la existencia de una conexión inhibitoria 5HT2 y una conexión excitatoria 5HT1A al estriado que afectan a su vez al sistema dopaminérgico.

.Neuroimagen
Los estudios sugieren la presencia de circuitos neurales específicos involucrados en la Fobia Social:

* cíngulo anterior
* córtex prefrontal dorsolateral derecho y córtex parietal izquierdo (involucrados en la planificación de respuestas afectivas y consciencia de la posición del cuerpo).
* córtex orbitofrontal.

Por otro lado hay estudios que muestran una mayor disminución del volumen del putamen con la edad en sujetos con FS en relación a con-troles.

====== Psicológico

.Psicoanálisis
Para Freud la ansiedad es una señal del Yo que se pone en marcha cuando algún impulso in-consciente prohibido (pulsiones genitales edípicas incestuosas) está luchando para expresarse en forma consciente, con falla del mecanismo de Represión (mecanismo destinado a mantener la pulsión fuera de la representación consciente), lo que lleva al Yo al uso de mecanismos de defensa auxiliares:

* Desplazamiento: separa el afecto de la re-presentación prohibida y lo desplaza a una situación u objeto en el exterior, aparente-mente neutro, pero en conexión asociativa con la fuente del conflicto (simbolización como mecanismo de defensa).
* Evitación como mecanismo adicional de defensa. El objeto sobre el que se desplaza la angustia puede ser evitado. La reactivación del conflicto sobrepasa los me-canismos de defensa ya estructurados y se mani-fiesta como angustia. Se trata de una regresión y fijación a etapa edípi-ca del desarrollo psicosexual, vinculado a inten-sa angustia de castración (el impulso sexual continuaría teniendo una marcada connotación incestuosa en el adulto por lo que la activación sexual tiende a transformarse en ansiedad que de forma característica es un miedo a la castración).

.Teoría Cognitivo-comportamental

El modelo teórico del aprendizaje (Watson) vincula la fobia y la evitación consiguiente al modelo estímulo-respuesta pavloviano tradicional de los reflejos condicionados, donde un estímulo originalmente neutro se transforma en condicionado para producir ansiedad al presentarse apareado a un estímulo amenazante. Si bien el condicionamiento clásico puede explicar el origen de la fobia, no explica el mantenimiento, para lo cual se postula la intervención del condiciona-miento operante: el patrón de evitación se muestra eficaz para reducir la ansiedad por lo que se refuerza el mantenimiento de la fobia. Otro mecanismo de aprendizaje que podría estar implicado es el moldeamiento (por observación de reacciones de un tercero).

====== Social

Estrés psicosocial en el curso de vida, en especial: muerte de un progenitor, separación de progenitores, crítica o humillación por terceros (por ejemplo hermanos mayores), violencia intrafamiliar: activarían la diátesis latente con la consiguiente aparición de síntomas. Datos estadísticos indican que los progenitores de pacientes con Fobia Social, tendían a ser padres menos cariñosos, más críticos y sobreprotectores que otros padres.

===== Paraclínica

El diagnóstico es clínico.

====== Biológico

Examen físico completo: neurológico, signos de intoxicación por psicoestimulantes (midriasis, PA, pulso), tiroides, CV (eventual EcoCG, ECG, para uso de AD y buscando trastornos de la con-ducción). Paraclínica general. Con interés académico: los individuos con Fobia Social tienen menos probabilidades de padecer una crisis de angustia en respuesta a la perfusión de lactato sódico o a la inhalación de CO2.

====== Psicológico

Superado el cuadro actual: tests de personalidad proyectivos (TAT, Rorscharch), no proyectivos (Minnesota), evaluando:

* Fortaleza yoica
* Elementos para el análisis de los mecanismos de defensa • Implementación de psicoterapia Tests de nivel (Weschler)..

====== Social

Familiares y terceros. Valoración de red de so-porte. Otros: para el seguimiento del trastorno, pueden ser útiles las escalas de cuantificación de síntomas.

===== Tratamiento

* Ambulatorio con control en policlínica
* Hospitalizar según entidad de síndromes asociados (ej. depresión) Objetivos del tratamiento:
* Alivio de afectos y cogniciones vinculadas al temor
* Reducción de la ansiedad anticipatoria
* Atenuar el comportamiento de evitación
* Reducir los síntomas autonómicos y fisiológicos de ansiedad
* Lograr mejores niveles de funcionamiento Directivas: compensar el cuadro actual y tratar la enfermedad de fondo.

====== Biológico

.Fobia social restringida o limitada (de ejecución):

Primera línea: beta bloqueantes:

* Propranolol 20-40 mg 30 minutos antes de la previsible exposición.
* Atenolol 50-100 mg 1 hora antes. Segunda línea: benzodiacepinas, dosis de 5-15 mg de equivalentes Diazepam.

.Fobia social generalizada o difusa
Si bien el fármaco mejor estudiado y con mayo-res índices de eficacia es la Fenelzina, su manejo complicado (con contraindicaciones y restricciones) lo relegan a un segundo plano.

Primera línea: Paroxetina 20 - 60 mg/día > Sertralina > Fluvoxamina (orden según calidad de evidencia en estudios realizados)

Segunda línea: Fenelzina 45-90 mg/día, inician-do con 15 mg/día, aumentando hasta 45-60 mg/día, esperando 4 semanas y luego, según resultados y tolerancia puede aumentarse hasta.

Casos resistentes: pueden asociarse benzodiacepinas: Alprazolam o Clonazepam (la terapia única con BZD es de eficacia dudosa o limitada). Opciones: Clorimipramina, Moclobemida.

En casos de fobia generalizada se mantendrá el tratamiento hasta 12 meses luego de remisión sintomática, a las dosis con las que se logró me-joría. Luego pueden disminuirse de forma progresiva, si aparece recidiva se vuelve a las dosis eficaces que se mantendrán por 12 meses más. Tratamientos superiores al año podrían estar indicados en: pacientes con síntomas significativos persistentes, presencia de comorbilidad, inicio precoz con TP por Evitación severo y pacientes con historia previa de recaídas.

====== Psicológico

Entrevistas en ambiente cálido y de escucha, afianzar vínculo, realizar psicoeducación.

Terapia cognitivo-comportamental: uso de diferentes técnicas:

* Reestructuración cognitiva
* Desensibilización
* Ensayos durante sesiones
* Asignación de tareas para la casa.
* Técnicas de inoculación de estrés
* Entrenamiento en asertividad y habilidades sociales.

====== Social

Terapia familiar, grupo de apoyo. Alianza terapéutica con familiar por tendencia de los fóbicos a abandonar la terapia.

===== Evolución y pronóstico

Puede seguir varios caminos evolutivos:

* Mejoría total
* Mejoría parcial permaneciendo síntomas residuales
* Refractariedad
* Comorbilidad con depresión y abuso de sustancias (sobre todo alcohol) Es una enfermedad crónica con tendencia a la recidiva.

PVI: bueno

PPI: crisis y depresión bueno.

PVA: depende de complicaciones del cuadro.

PPA: depende de adhesión al tratamiento.

El pronóstico depende de:

* Gravedad del trastorno al inicio del tratamiento
* Edad de comienzo del tratamiento
* Continuidad del tratamiento
* Nivel intelectual
* Nivel socioeconómico
* Comorbilidad (depresión, alcoholismo, TP)
* Antecedentes familiares (predictor negativo para el caso de la fobia social).

Evaluación de resultados del tratamiento :

* Síntomas: disminución o desaparición de síntomas (Escala de Liebowitz de Ansiedad Social).
* Disfunción: Escala de Discapacidad de Sheehan.
* Evolución general: CGI.

Se define respuesta como una reducción del 50% o más en las escalas usadas. Remisión completa se define como la resolución completa de los síntomas por un período de por lo menos 3 meses.
