=== 14 Trastorno de ansiedad generalizada

15.1 Historia tipo

15.2 Agrupación sindromática

15.3 Personalidad y nivel

15.4 Diagnóstico

15.4.1 DSM IV

Criterios diagnósticos:

A. Ansiedad/preocupación excesivas ante amplia gama de estímulos de más de 6 mese de duración.

B. Dificultad para controlar la ansiedad.

C. 3 o + de 6 (en niños solo 1): inquietud / impaciencia, fatigabilidad, alteraciones en concentración, irritabilidad, tensión muscular, alteración del sueño (IFCITA).

D. Excluye: síntomas debido a otros trastornos del eje I (sobre todo trastornos de ansiedad).

E. Malestar clínicamente significativo.

F. Descartar sustancias, enfermedad médica y otros trastornos de eje I.

15.5 Diagnósticos diferenciales

Comorbilidad más frecuente: depresión.

15.6 Diagnóstico etiopatogénico y psicopatológico

15.7 Paraclínica

15.8 Tratamiento

El abordaje farmacológico es de primera línea.

Recomendaciones: duloxetina > pregabalina > venlafaxina > escitalopram. Alternativa: bupropion.Slee, A., Nazareth, I., Bondaronek, P., Liu, Y., Cheng, Z., & Freemantle, N. (2019). Pharmacological treatments for generalised anxiety disorder: a systematic review and network meta-analysis. The Lancet, 393(10173), 768-777.. Con menor evidencia: mirtazapina, sertralina, fluoxetina, buspirona y agomelatina. Quetiapina: efecto marcado pero con mala tolerabilidad. Paroxetina y benzodiacepinas: mala tolerabilidad.

Duloxetina: comenzar con 30 mg/día por 1 semana y luego 60 mg/día. Si hay respuesta parcial: aumentar hasta 120 mg día.

Pregabalina: comenzar con 150 mg/dia en 2 o 3 tomas, aumentos semanales hasdta dosis máxima de 600 mg/día.

Venlafaxina: comenzar con 75 mg/día por 4 días, luego 150 mg/día. Máximo 225 mg/día en 2 o 3 tomas (preparados de liberación sostenida: 1 toma diaria)

15.9 Evolución y pronóstico
