=== 19 Cleptomanía

==== Encare

===== Agrupación sindromática

====== Síndrome de alteración del control de impulsos.

Dado por fracaso reiterado en los intentos de resistirse al impulso de robar objetos que no se utilizan para uso personal o por fines lucrativos (los objetos suelen deshecharse, regalarse o esconderse). El acto está precedido por sensación de tensión emocional y seguido de gratificación durante e inmediatamente después de realizar el acto. El acto se realiza de forma solitaria sin grandes esfuerzos para evitar ser descubierto. B. Otros síndromes síndrome de ansiedad angustia, síndrome depresivo (vinculado a culpa). Esto no impide la repetición del acto.

===== Personalidad y nivel

===== Diagnóstico positivo

Cleptomanía

===== Diagnóstico diferencial

• Hurto recurrente sin trastorno mental manifiesto: son actos planificados y existe un motivo de ganancia personal.
• Deterioro cognitivo (olvido de pagar objetos, alteración de juicio con desinhibición que lleva a conductas de robo)
• Psicosis: hurto en contexto discordante, delirante o por comando alucinatorio.
• Trastorno de la personalidad borderline o antisocial: en este caso no hay una conducta maladaptativa sino un patrón que afecta todas las áreas de la vida de la persona

===== Etiopatogenia y psicopatología

===== Paraclínica

Biológico: ninguna. Psicológico: tests de personalidad.

===== Tratamiento

====== Biológico

Antidepresivos + tratamiento de cuadros comórbidos.

====== Psicologico

• exposición in vivo + prevención de respuesta
• reestructuracion cognitiva
• sensibilización encubierta
• desensibilización sistematica

===== Evolución y pronostico

===== Fuentes

Comité de consenso de Catalunya. Recomendaciones
