=== F84 Trastornos generalizados del desarrollo

- F84.0 Autismo infantil (Psicosis Infantil, Síndrome de Kanner)
- F84.1 Autismo atípico
- F84.2 Síndrome de Rett
- F84.3 Otro trastorno desintegrativo de la infancia
- F84.4 Trastorno hipercinético asociado a RM y movimientos estereotipados
- F84.5 Síndrome de Asperger (Trastorno Esquizoide de la Infancia)

==== Encare

===== Tratamiento

====== Biológico
En metaanálisis no hay diferencias significativas entre el placebo y los siguientes tratamientos footnote:[Yu, Yanjie, et al. "Pharmacotherapy of restricted/repetitive behavior in autism spectrum disorder: a systematic review and meta-analysis." BMC psychiatry 20.1 (2020): 1-11.]: fluvoxamina, risperidona, fluoxetina, citalopram, oxitocina, N-Acetilcisteína, buspirona.

Aripiprazol: potencialmente útil para uso transitorio en el tratamiento de aspectos comportamentales (irritabilidad, hiperactividad, estereotipias). Debe prestarse atención a los efectos secundarios (ganancia de peso, sedación, sialorrea, temblor). Un estudio muestra que a largo plazo no se diferencia del placebo -> se recomienda usar por períodos cortos footnote:[Hirsch, Lauren E., and Tamara Pringsheim. "Aripiprazole for autism spectrum disorders (ASD)." Cochrane Database of Systematic Reviews 6 (2016).].
