== Fragmentos

En los lugares marcados con el ícono ``pegar'' () pueden insertarse
textos similares a los que se encuentran a continuación. No se
recomienda la copia textual, porque puede tener un efecto negativo a los
ojos del tribunal.

=== Neurosis

Por la presencia de sintomatología en el corte longitudinal de la
existencia con alteraciones estructurales de la personalidad,
expresiones de un conflicto intrapsíquico, con inhibición de conductas
sociales y fondo de ansiedad-angustia. Es egodistónico (provoca
malestar), autoplástico (exigencias dirigidas hacia sí mismo, no al
entorno). Tiene conciencia de enfermedad, pide ayuda (colabora con la
entrevista). En la entrevista hay un buen rapport y no se evidencia
pérdida del juicio de realidad.

=== Nivel en diferido

Lo evaluaremos luego de remitido el cuadro actual, sobre la base de
escolaridad, logros, entrevistas, entrevistas con terceros.
Oportunamente valoraremos la necesidad de realización de test de nivel.
Sabemos que todos estos elementos están teñidos por el medio
socio-económico-cultural. Clínicamente impresiona X.

=== Psicosis

Porque el paciente perdió contacto con la realidad, encontrándose sumido
en un mundo propio, incompartible, por él creado, con el cual se
relaciona de una manera nueva y del cual no puede sustraerse
voluntariamente, con pérdida del juicio de realidad, sin conciencia de
morbidez, estableciéndose en la entrevista un mal rapport.

=== Psicosis aguda

Por ser una experiencia sensible y actual, de X días de evolución, más
vivida que relatada, con alteración importante del humor y la
afectividad y con afectación de las conductas basales.
