== Esquizofrenias
=== Notas clínicas
==== Historia
===== Hebefrenia de Hecker
Eclosión en la pubertad. Su estado terminal permite calificarlo como "estupidez" hebefrénica. Tendencia a la actividad exagerada y a menudo extravagante, conducta errática y absurda con tendencia al vagabundeo, extravagancias, de carácter cambiante, relato pueril (humoradas bobas, elucubraciones fantásticas pueriles). Anomalías en la construcción de frases, modo de expresión y lenguaje descendido bastante por debajo del nivel de educación alcanzado previamente. Propensión a desbordes verbales, frases huecas y ampulosas. Aparición precoz de "debilitamiento intelectual".

===== Catatonía de Kahlbaum
Recibe el nombre de su alteración motora : "locura del tono muscular". Síntomas psíquicos: patetismo (exaltación teatral, forma de éxtasis religioso trágico). Discordancia entre la expresión afectiva y el contenido del discurso. Verbigeración: emisión repetida de palabras y frases desprovistas de significación. Mutismo: síntoma opuesto al anterior. Negativismo. Síntomas somáticos. Flexibilidad cérea. Accesos epileptiformes o histeriformes.

===== Kraepelin y la demencia precoz
Considera que la enfermedad mental se individualiza y define por su evolución: el verdadero diagnóstico es el que permite un pronóstico preciso, sólo la evolución puede confirmar el diagnóstico y por lo tanto fundamentarlo (la enfermedad sólo puede ser definida por su estado terminal). Demencia precoz : estado mórbido que implica un menoscabo marcado de la vida afectiva y de la voluntad que evoluciona hacia una disgregación completa de la personalidad. Pérdida de la dirección sobre la voluntad y la capacidad de actuar en forma independiente. Pérdida de la unidad interna de las actividades del intelecto, de las emociones y de la voluntad (en sí mismas y entre unas y otras). Equivale a la pérdida de la coordinación intrapsíquica de Stransky y al trastorno de las asociaciones de Bleuler.

==== Formas clínicas
* Hebefrénica : postpuberal, puerilismo, pasividad, comportamiento inadecuado, acentuada disgregación de la personalidad.
* Catatónica
* Paranoide : gran actividad delirante alucinatoria.

Forma paranoide atenuada : Parafrenia

Parafrenias: no presentan empobrecimiento afectivo ni trastorno de la voluntad / armonía interna de la vida psíquica bastante conservada / inicio en la vida media / desarrollo lento y continuo de persecución y de exaltación.

* Sistemática : inicio insidioso de un delirio de persecución progresivo + ideas de exaltación sin decaimiento de la personalidad. Luego se agregan alucinaciones auditivas e ideas de in-fluencia. Pragmatismo laboral conservado
* Expansiva: megalomanía exuberante con exaltación del humor, erotomanía (s/t en mujeres), también ideación delirante mística, aparición más precoz de alucinaciones y alteración pragmática pero se conserva un comportamiento dócil y razonable sin desintegración de la personalidad.
* Confabulatoria : seudorecuerdos, experiencia delirante de índole extraordinaria, ideas de persecución, reinterpretación de su biografía, descendencia de la realeza o personajes históricos.
* Fantástica: delirios exuberantes, extraordinarios, inconexos y cambiantes, ideas de persecución, viajes extraordinarios. Independencia nosográfica controvertida: un seguimiento en 1921 comprobó que 40% desarrollaron signos claros de demencia precoz / cobró fuerza la idea de que sería una variante de la esquizofrenia que compromete menos la personalidad por su edad de comienzo tardía

==== Bleuler y la esquizofrenia

Introduce el término en 1911 Diferencia c/ Kraepelin: privilegio del cuadro de estado intentando determinar los elementos de éste que permiten hacer el diagnóstico precozmente sin necesidad de esperar la evolución. Critica concepto de Demencia Precoz: no todos llegan a deterioro, si llega no siempre lo hace precozmente. Pone de relieve la escisión (Spaltung) como trastorno fundamental de la esquizofrenia / en su opinión la escisión de las funciones psíquicas es una de las características + relevantes / concepto ya presente en la obra de otros autores : Stransky (ataxia intrapsíquica), Chaslin (locura discordante). Pese a utilizar el término en singular para él es evidente que se trata de un grupo que incluye varias enfermedades. Concepto que vuelve + imprecisos los límites con los trastornos de la personalidad y con la normalidad, permitiendo que los pacientes sean considerados personas menos extrañas y + cercanas a la experiencia normal (esquizofrenia latente). 
Definición : grupo de psicosis cuyo curso es a veces crónico y a veces está marcado por ataques intermitentes, pudiendo detenerse o retroceder en cualquier etapa, pero que no permite una completa restitutio ad integrum. Presenta un tipo específico de alteración del pensamiento, afectos y relación con el mundo exterior que no aparece en ningún otro trastorno bajo esta forma particular. Trastorno en la unidad de la persona: insuficiente integración de los diferentes impulsos, las ideas se elaboran parcialmente y se pone en relación de una manera ilógica a fragmentos de ellas para constituir una nueva idea. Alteración en el proceso de asociación: opera c/ meros fragmentos de ideas y conceptos llevando a asociaciones extrañas e imprevisibles; bloqueo: detención o cese del flujo de pensamiento en el intento de pasar a otra idea, afloran nuevas ideas que ni el paciente ni el observador pueden relacionar con la corriente anterior de pensamiento. No hay una alteración 1ª de percepción, orientación ni memoria. Afectividad : carente de expresión emocional, res-puestas afectivas exageradas, inadecuada. Síntomas accesorios que tienen su carácter esquizofrénico específico: delirios, alucinaciones, confusión, estupor, manía, melancolía, síntomas catatónicos.

==== Síntomas fundamentales

Presentes en todos los casos y durante todos los períodos de la enfermedad.

TIP: AAAA: asociación, afectividad, ambivalencia, autismo

===== Trastorno de la Asociación

Rotura del hilo asociación por lo que el pensamiento se hace ilógico, el pensamiento opera con ideas o conceptos no relacionados o que tienen relación insuficiente con la idea principal, y que por lo tanto deberían ser excluidos del proceso mental. Bloqueo : pérdida de todos los procesos asociativos, actividad asociativa parece hacer un alto brusco y completo: "cierre de una llave de paso". Al reanudarse la corriente de pensamiento las ideas que sur-gen guardan escasa o nula relación con las preceden-tes, a veces el paciente lo atribuye a influencia extraña. Conexiones accidentales, condensaciones, asociación por el sonido, asociaciones intermedias, persistencia de la idea (estereotipias)

===== Trastorno de la Afectividad

Más grave : desaparición de las emociones / - grave : indiferencia afectiva Alteración en la coherencia de la manifestación afectiva / inadecuada o incongruente en relación al relato / alteración en la modulación afectiva (afectos aparecen rezagados con la idea y pueden prolongarse patológicamente)

===== Ambivalencia

Otorga a los contenidos psíquicos un índice positivo y otro negativo al mismo tiempo Afectiva : coexistencia simultánea de sentimientos agradables y desagradables Voluntad (ambitendencia) : actos que no alcanzan su finalidad Intelectual

===== Autismo

Desapego de la realidad junto al predominio, absoluto o relativo, de la vida interior / equivale a Freud (autoerotismo), Janet (pérdida de la función de lo real) + graves: suspenden contacto con el mundo exterior y se encierran en sus deseos o se ocupan de las tribulaciones de sus ideas persecutorias. - graves: mantienen capacidad de desenvolverse en el mundo exterior pero ni la evidencia ni la lógica influyen sobre sus esperanzas o ideas delirantes. A veces los pacientes perciben la desviación de su pensamiento hacia uno autista experimentándolo como penoso.

==== Síntomas accesorios

Pueden faltar en ciertos períodos o nunca estar presentes / otras veces pueden dominar el cuadro clínico. Pueden aparecer también en otras enfermedades pero exhiben peculiaridades que sólo se hallan en la esquizofrenia. Con frecuencia le proporcionan el sello externo al cuadro clínico poniendo de manifiesto la psicosis, alertando al entorno familiar y requiriendo la atención psiquiátrica. síndrome delirante alucinatorio / alteración de len-guaje y escritura / síntomas somáticos y catatónicos / síndrome de alteración de conciencia

Subgrupos

Paranoide

Inicio x lo general gradual, desrealización y despersonalización, autorreferencia (relaciona c/ él sucesos completamente neutros). Al principio puede dudar pero luego las ideas delirantes alcanzan total certeza y credibilidad. Al delirio se agregan AAV y somestésicas, crisis de EPM. En otras, inicio súbito: “rayo en cielo despejado”, buscar siempre prodromos sutiles, oscilaciones prominentes a línea de base y alejamiento de ésta, ideas persecutorias, de grandeza, eróticas.

Catatónico

Por lo gral inicio por EPM / pasaje de estupor a estados catalépticos / tb puede empezar x sd paranoide / raro curso crónico, por lo general periódico

Hebefrenia

Característica tendencia al deterioro y la "demencia" / para Bleuler la cuestión de la edad es irrelevante / sería una categoría residual donde previa-mente hay que descartar otros subtipos

Simple

Debilitamiento afectivo e intelectual progresivo / deterioro de la voluntad, capac de trabajo y cuidado de sí mismos / evolucionan a "demencia" grave KAPLAN : pérd insidiosa del interés, motivación, ambición e iniciativa Se encuentran poco en hospitales : vagabundos, jornaleros, criados / excéntricos, salvadores del mundo

Minkowski

Considera que la perturbación esencial de la esquizofrenia es la pérdida de contacto vital con la realidad, no el trastorno asociativo. Esquizoidismo vs sintonía Vínculo entre los temperamentos y las constituciones y su relación con la patología / previo al inicio manifiesto de la psicosis, en el pasado del individuo, se proyectan los rasgos esenciales de ésta : las cosas son así porque ya lo eran anteriormente Conceptos emparentados c/ esquizofrenia latente de Bleuler y esquizoidismo de Kretschmer Actitud respecto al ambiente : rasgo esencial para dx diferencial entre las dos grandes entidades nosográficas descritas por Kraepelin Espectro esquizofrénico se mueve entre los dos polos : hiperestesia / anestesia afectiva : "no es demasiado sensible o demasiado frío, sino que es las dos cosas a la vez" El maníaco depresivo permanece sintónico respecto al ambiente mientras que el esquizofrénico ya no lo es (incapaz de vibrar al unísono c/ el ambiente y permanecer en contacto c/ la realidad) El contacto vital con la realidad Tanto en Kraepelin como en Bleuler hay una fusión de formas clínicas diversas en una misma noción / introduce el concepto de pérdida de contacto vital c/ la realidad como perturbación fundamental La enfermedad no ataca tal o cual función, sino a su cohesión, a su juego armonioso de conjunto : así lo revelan Chaslin (discordancia), Stransky (ataxia intrapsíquica), Kraepelin (pérdida de la unidad interior), Bleuler (esquizofrenia) Metáforas : "máquina sin combustible" (Chaslin) / "libro desprovisto de encuadernación" cuyas páginas están mezcladas y en desorden, pero sin que ninguna falte (Anglade) La noción de autismo, fact referentes a las relac c/ el ambiente, la ausencia de fines reales, de ideas directrices y de contacto afectivo convergen hacia la noción de pérdida de contacto vital c/ la realidad El autismo 1. PENSAMIENTO autístico : no trata de adaptarse a la realidad, por el contrario, está apartado de ésta / opuesto al pensamiento realista que trata de adaptarse a la realidad tratando de alcanzar el máximo de valor pragmático "No busca ni ser comunicado a los demás de una manera comprensible, ni dirigir la conducta conforme a las exigencias de la realidad...Sólo tiene un alcance subjetivo; sirve sólo al individuo y única-mente cuando está apartado de la realidad; así puede hacer uso libremente de signos y de procedimientos especiales, que pueden volverlo más rápido, más cómodo, más apropiado a los caracteres particulares de los complejos que expresa" Mecanismo similar al de los sueños / da preferencia a su mundo imaginario en detrimento de la realidad, lo que se traduce exteriormente por una actitud de hostilidad, pasividad e inmovilidad respecto al ambiente 2. no son seres pasivos y replegados sobre sí mismos, también OBRAN y esa actividad lleva un sello profundamente mórbido que por sí sola traduce la perturbación esquizofrénica Realiza su acto o su obra en el mundo ambiente, sin preocuparse de las exigencias de éste, como si en realidad ese mundo no existiera en absoluto El autismo radica en la pérdida de contacto vital c/ la realidad El ciclo de la actividad personal Impulso personal : "agresión y retirada" del ambiente c/ post integración a la realidad Cuando se quiere crear algo absolutamente personal y no se quiere más que eso, la obra no se integra a la realidad y no se hace más revolucionaria o más original, sino que se degrada y no es sino el gesto de un enfermo Ruptura del contacto íntimo con el devenir ambiente, opuesto a la sintonía presente en PMD Formas (todos carecen de finalidad) Actos sin proyección en el mañana Actos atiesados Actos en cortocircuito o al margen Actos que no tratan de terminar Egocentrismo activo . tendencia a hacer del propio yo el campo de una actividad incesante

Crow

Subtipos no son identificados por el cuadro clínico de estado sino por otras medidas clínicas o biológicas como la respuesta al tratamiento o la evidencia de alteraciones estructurales del cerebro Sínt (+) : alucinaciones / delirio / trast formales del pensam (buena respuesta a NL) Sínt (-) : aplanam afectivo / pobreza del discurso / apatía / retraimiento social (resp nula o pobre a NL) Escalas para determinar ambos tipos de sínt : SANS - SAPS / PANSS Crow : en crónicos : resist a los efectos de drogas de tipo anfetamínico / trast cognitivos / aumento del tamaño ventricular en la TAC / marcados sínt negativos 1980 : (a) sd tipo I : "esquizofrenia aguda" : sínt (+) / alt en transmisión dopaminérgica / potencialmente reversibles / predictores de buena respuesta al tto NL / pueden ser seguidos x el desarrollo de sd tipo II o presentarse combinados (b) sd tipo II : "estado defectual" : sínt (-) / asoc a trast cognitivos y cambios estructurales del cerebro / por lo gral indican irreversibilidad y mala evolución a largo plazo / pobre resp a NL Andreasen : esquizofrenia (+) / (-) : pobreza del discurso, del afecto y del contenido del pensam, retardo psicomotor y anhedonia / mixta / creó escalas SANS y SAPS Carpenter : diferencia sg deficitarios 1º de 2º a otra condición ya que los considera como inespecíficos Criterios dx para esquizofr deficitaria : 1. Se cumplen los criterios para Esquizofrenia 2. sínt deficitarios : afecto restringido / < fluctuaciones emocionales / pobreza del discurso con < interés y curiosidad / < sent de finalidad / < impulso social 3. no totalmente explicados por : autoprotección frente a los sínt (+) / depresión - ansiedad - disforia / fármacos / deprivación ambiental 4. criterio longitudinal : 2 de los síntomas están presentes en los 12 meses previos B.

=== Encare

==== Agrupación sindromática

===== Síndrome disociativo-discordante
Ambos términos son equivalentes, intentan poner orden a un "caos" y califican el mismo fenómeno mórbido que consiste en la descomposición o ruptura de la vida psíquica con pérdida de la integración armónica de los campos constitutivos de la persona, afectando conducta, humor-afectividad y pensamiento, que se manifiesta al observador por 4 síntomas capitales:

Impenetrabilidad: hermetismo y tonalidad enigmática que caracteriza al desorganizado mundo del sujeto por lo cual no se encuentra sentido a sus expresiones. Desapego: vuelta del sujeto sobre sí mismo, con abandono a la ensoñación interior , en la cual afectos e intereses no se vuelcan en la realidad. Ambos síntomas (impenetrabilidad y desapego) evocan la retracción a un mundo autista. Ambivalencia: antagonismo simultáneo y sucesivo de 2 experiencias contradictorias sin que el paciente capte contradicción alguna, objetivable por terceros, lo que configura una ambivalencia psicótica. Extravagancia: carácter insólito, bizarro e incomprensible para el observador de conductas, palabras y afectos expresados.

Se manifiestan en: pensamiento, afecto y conducta. Pensamiento Impenetrabilidad: pensamiento: oscuro, enmaraña-do, incoherente, caótico, con pérdida de la secuencia asociativa lógica que nos muestra un trastorno asociativo a este nivel, junto a las pararrespuestas, alteraciones fonéticas, sintácticas y semánticas (neologismos).

Desapego: este "modo" de pensamiento responde a un simbolismo mágico interno, que lleva al lenguaje a un desvío de su legítima función, no estando destinado a establecer contacto con el entrevistador.

Extravagancia: en las explicaciones que da a su motivo de ingreso.

Ambivalencia: su relato está poblado de contradicciones.

TIP: IDEA: Impenetrabilidad Desapego Extravagancia Ambivalencias

Estas alteraciones nos muestran una ataxia intrapsíquica, hecho fundamental de la discordancia del pensamiento, en la cual, pese a la no existencia de un déficit intelectual, está profundamente alterado el uso y la eficacia de sus operaciones intelectuales. Afectividad Impenetrabilidad: se manifiesta por las relaciones afectivas incomprensibles (bruscas reacciones emocionales, calma inexplicable) que escapan a toda comprensión de su motivación psicológica. Las expresiones provienen de un mundo interior hermético, resultando enigmáticas al observador. Resp emocionales paradojales

Desapego: se manifiesta por la incapacidad de vibrar con el relato, la dificultad en el encuentro, la indiferencia. Atimormia: desinterés afectivo, apariencia desvitalizada, inercia aparente, interrupción del continuo intercambio entre el mundo y el sujeto. Intento de negar la afectividad, de destruir su significación (grado máximo de desapego).

Extravagancia: está dada por las manifestaciones paradójicas y absolutamente desconcertantes: odio feroz por un niño pequeño, deseo incontrolable de poseer un piano en una casa chica, pánico ante una corbata azul.

Ambivalencia: se observa en la presencia simultánea de deseos de abrazar y escapar de su novia. Conductas: Impenetrabilidad: en cuanto a su motivación psicológica.

Desapego: actos desvitalizados, ruptura con el de-venir ambiente, acciones absolutamente personales, "obrar autístico"

Extravagancia: muestra liberación de pulsiones (conductas alimentarias, excrementos, sexuales)

Ambivalencia: con ambitendencia síndrome catatónico Destacamos en la psicomotricidad: elementos cata-tónicos (catatonismo).

síndrome catatónico: máximo de discordancia en la psicomotricidad. CINE MIE Catalepsia: plasticidad, rigidez, fijación de actos o perseverancia de actitudes (impuestas o espontáneas), flexibilidad cérea.

Inercia: actitudes de pasividad y automatismo, latencia en las respuestas, obediencia automática. Sugestionabilidad: ecomimia, ecopraxia, ecolalia.

Negativismo: conductas de rechazo, mutismo, oposición al entrevistador, rechazo de alimentos.

Estupor: máximo de inhibición psicomotriz. Perdida de la iniciativa motriz sobre el cual se instalan impulsiones, episodios excitomotrices heteroagresivos en cortocircuito: ® de reactividad al entorno se caracteriza por lo enigmático y absurdo.

Manierismos: tonalidad de afectación teatral, pateticismo: paramimias, risas inmotivadas.

Impulsiones: actos incoercibles que escapan al control del paciente: hetero o autoagresivos,defenestración, fugas, verbales. Son imnotivados, incompartibles.

Estereotipias: conductas caracterizadas por la iteración: de movimientos, de actitudes, lenguaje (verbigeración), de conductas.

===== Síndrome delirante o síndrome de alteración del pensamiento

En lo formal: incoherente, sin finalidad, con pérdida de la secuencia asociativa lógica. Interceptación: alto brusco y completo de la actividad asociativa. Conexiones accidentales, asociación por el sonido. Estereotipias (persistencia de la idea). Fading mental.

En el contenido: conformando un síndrome delirante que se manifiesta por ideas mórbidas incompartibles, irreductibles a la lógica, carentes de juicio de realidad y que le generan conductas.

A temática: persecutoria, de daño y perjuicio, mística, megalomaníaca, transformación corporal, higiene, influencia, posesión.

A mecanismo: intuitivo (se le aparece como verdad revelada), interpretativo (percepciones reales que el paciente interpreta a la luz de sus propias convicciones), alucinatorio (eco, robo, adivinación, enunciación de comentarios o actos, anticipación de actos, órdenes).

Mal sistematizado: sus componentes no guardan una lógica, presentan movilidad, carácter cambiante y mínima organización, sin progreso discursivo, carencia de hilo argumental, por lo cual decimos que corresponde a una estructura paranoide.

En lo conductual: conductas generadas por el delirio (auto y heteroagresividad, etc.)

Dentro del síndrome delirante puede formarse un:

.Síndrome de automatismo mental
Dado por la pérdida de la intimidad del espacio intrapsíquico, en su forma de triple automatismo, conformado por fenómenos de desdoblamiento alucinatorio del pensamiento que se imponen a la conciencia del sujeto a pesar de su yo, dado a nivel:
- Sensorial: sensaciones parásitas (alucinaciones psicosensoriales, visuales, cenestésicas, táctiles, gustativas). Fenómenos sensoriales puros, anideicos.
- Triple automatismo: motor, ideico e ideoverbal (elocución, ideación, formulación ideoverbal espontánea, articulación verbal forzada)
- Desdoblamiento mecánico del pensamiento: eco del pensamiento, eco de la lectura, comentario de actos. Pueden ser anticipados, simultáneos o retardados con respecto al acto.
- Pequeño automatismo mental: emancipación de abstracciones, "nebulosa anticipada de un pensamiento indiscernible"

.Síndrome de Influencia o control externo
El individuo se siente manejado, influido por fuerzas externas a él.

.Síndrome de despersonalización
Pérdida del sentido de familiaridad de la persona consigo misma y con el entorno, que afecta la integridad somática corporal, la identidad y la conciencia del yo y que acompaña a la expresión de extrañeza e incluso de cambio total del mundo exterior.

* Alteración del esquema corporal: alucinaciones somatognósticas, ilusión de desplazamiento o distorsión, metamorfosis segmentarias, miembros fantasmas.
* Desrealización: cambio de ambiente, falta de familiaridad con el ambiente.
* Desanimación: sentimiento de vacuidad, sin vida.
* Tendencia al autoanálisis (signo del espejo).

.Síndrome del humor y la afectividad
Humor oscilante, lábil, humor inadecuado, inadaptado (discordancia). Exaltación, oscilante de acuerdo al contenido temático. Ansiedad.

===== Síndrome deficitario social
En el corte longitudinal pragmatismos. Retracción social de X evolución, con abandono de metas y proyectos de futuro, con pérdida de relación con sus amigos y familia con deterioro en su actividad como ser social. Déficit de rendimiento como persona social (CB y Prg).

===== Síndrome conductual
Conductas que motivan el ingreso: impulsión catatónica, comando alucinatorio, IAE. Se objetiva en conducas basales y pragmatismos.

==== Personalidad y nivel

Nivel: buen nivel y rendimiento, hasta que se produce un corte.

Personalidad premórbida: deben confirmarse datos con terceros ya que no es un paciente confiable. Esquizoide. Corte existencial: cambio de conductas con introducción lenta en un mundo cada vez más personal que lo lleva en X tiempo a un deterioro social.

==== Diagnóstico positivo

ps crónica – tipo esquizofrenia – tipo clínico – descompensada por... – causa de descompensación

Psicosis: por hallarse el paciente sumido en un mundo propio, incompartible, con el que se relaciona de una forma nieva, por él creada, del cual no puede salir voluntariamente, por haber perdido el juicio de realidad, la presencia de un delirio, por el mal rapport y la carencia de conciencia de morbidez.

Psicosis crónica: por tratarse de un trastorno perdurable de X años de evolución que ha modificado el sistema de la personalidad llevando a una transformación delirante del yo y su mundo constituyendo-se el paciente en un ser delirante, siendo el delirio más relatado que vivido, no existiendo elementos de agudeza tales como alteración de la conciencia y oscilaciones del humor.

Esquizofrenia: síndrome disociativo-discordante o elementos de síndrome catatónico, impregnado de elementos disociativos discordantes.síndrome delirante de estructura paranoide expresado sin calor afectivo. Corte existencial a los X años con ruptura histórico-biográfica. Curso progresivo deteriorante con elementos de retracción a un mundo autista. Además: edad, AF de esquizofrenia, leptosómico, personalidad previa esquizoide.

En período de estado: por estar el SDD ya instalado, porque su relación con el mundo no ha claudicado en su totalidad. 

Tipo clínico: 

A. Hebefrénico: Adolescente o adulto joven (15-25 años), SDD, jovialidad pueril, desorganización conductual, irresponsables, imprevisibles, rápido deterioro, no predomina el delirio (transitorio y fragmentario). 
B. Catatónico: Según el síndrome catatónico. Cuadro de inercia sobre el que sobrevienen bruscos brotes de impulsividad. Estuporosa (reacciones violentas), agitada (violencia extrema), catanonismo (discordancia PM). 
C. Paranoide: >> 20 años (adulto joven), cuadro centrado en el delirio paranoide, aunque existen elementos DD, pese al tipo de evolución no existe deterioro marca-do. 
D. Simple: Pérdida insidiosa del interés o motivación, ambición o iniciativa. 
E. Indiferenciado CIE-10, DSM, sin claro predominio de ningún tipo.

Según el caso clasificar con criterios de esquizofr (+) ó (-) Estado Descompensada: por presentar alteración de las conductas basales, empeoramiento en pragmatismos, oscilaciones o alteraciones del humor. Está descompensado debido a: . aumento de productividad delirante con elementos paranoides, de influencia. . incremento en el monto de agresividad: impulsión catatónica. . exacerbación de sintomatología: delirante, catatónica. trastornos conductuales.

Causa de descompensación: 
. abandono de medicación
. stress psicosocial
. evento vital desfavorable 

DSM IV
. 2 ó más : delirios / alucinaciones / discurso desorganizado / comportamiento desorganizado o catatónico / sínt negativos (aplanamiento afectivo / pobreza del discurso / apatía / retraimiento social)
. disfunción social / ocupacional
. > 6 meses
. exclusión de : trastorno humor, esquizoafectivo, alt médica, sustancias

(posibilidad de plantear dx diferenciales con otros trast de eje I : humor – c/ síntomas psicóticos -, esquizofreniforme, psicótico breve, delirante, esquizoafectivo, trast médico, sust)

. especificadores de curso longitudinal

==== Diagnóstico diferencial

Con PDA: consideramos que se trata de un brote delirante, descompensación aguda de una enferme-dad crónica. Hay SDD, hay períodos intercríticos no libres de síntomas, presenta un curso progresivo deteriorante. Con EPA en determinada patología.

Con causas orgánicas de delirio: consumo de sustancias.

Con otros delirios crónicos:

A. Paranoia: que descartamos ya que la paranoia presenta un delirio sistematizado, expresado con calor afectivo, de estructura paranoica y en la cual no existe una evolución deficitaria con retirada a un mundo autista como en nuestro paciente.

B. Parafrenia: que descartamos porque la parafrenia se caracteriza por un pensamiento paralógico, fantástico, a mecanismo imaginativo, pero s/t por el mantenimiento de los pragmatismos, sin deterioro, con la característica bipolaridad con la que coexisten el polo delirante y el polo adaptado a la realidad (edad 30-35 años).

Puede plantearse con Psicosis Infantil (DSM : trast gralizado del desarrollo) si se sospecha inicio muy temprano.

RM : 3 veces más frec que en población gral

Con respecto a la forma clínica de esquizofrenia.

Otros: depresión psicótica, neurosis (obsesiva)

==== Diagnóstico etiopatogénico y psicopatológico

Es una enfermedad multifactorial:

Biológicos Genéticos: familiares de primer grado riesgo aumentado para el desarrollo de la enfermedad. Biotipológicos: leptosómico de Kretschmer. Bioquímicos: alteración/disregulación dopaminérgica en el sistema mesolimbo-cortical ( de sensibilidad de receptores postsinápticos de dopamina) que explicarían la acción de los neurolépticos. También se postula alteración a nivel de los receptores de serotonina que explicaría la acción de neurolépticos de nueva generación. Anatómicos: vinculados a formas deficitarias, con anomalías estructurales inespecíficas en la TAC y RNM con de ventrículos laterales / PET y SPECT ( utilización de glucosa por el cerebro y valorac del flujo sanguíneo ) muestran hipoactividad en lób frontal y act anormal en varias á del cerebro Psicológicos Personalidad premórbida esquizoide (OJO) Social Lo que haya en su historia personal que actuaría en un terreno vulnerable. Factores de relación con el medio familiar, más vinculado a las recaídas que al debut.

En la causa de descompensación: • Abandono de medicación • Empuje evolutivo de la enfermedad • Estrés psicosocial

Psicopatología

Para el psicoanálisis, significa una regresión (regresión narcisista de la libido) y fijación a etapas pre-genitales del desarrollo psicosexual, con utilización de mecanismos de defensa psicóticos, de negación de la realidad proyectando la angustia en el delirio. Se trataría de una pérdida de la autonomía narcisista del yo, vinculada a una falla en las identificaciones primarias.

Para Jaspers, la esquizofrenia es un proceso que cambia la estructura con fragmentación y creación de nuevo estado de personalidad con ruptura histórico-biográfica de la existencia.

==== Paraclínica

El diagnóstico es clínico. Historia anterior: corroborar curso de la enferme-dad, rendimiento pragmático / trat recibidos y res-puesta a ellos, gr de adhesión al tto / comunicación c/ psiq tratante

Biológico: valoración general, s/t neurológica y fondo de ojo. TAC: aspecto estructurales.

Valoración pre-ECT para descartar contraindicaciones:

ECG y consulta con cardiólogo para descartar IAM reciente y arritmias inestables.

Examen neurológico completo con fondo de ojo para descartar hipertensión endocraneana por masa supratentorial.

RxTx FyP para descartar aneurisma de aorta.

Psicológico: profundizar en los datos aportados por el paciente. Superado el cuadro actual: test de personalidad proyectivos y no proyectivos, test de nivel. Apreciaremos el grado de psicoticismo, así como ansiedades primitivas.

Social: adquiere jerarquía y empezar por él si sólo hay datos aportados por el paciente. Consentimiento informado para la realización de ECT. Despejar temores, explicar riesgos, beneficios y efectos secundarios. Historias anteriores, medicación recibida y respuesta a ella, períodos intercríticos con nivel de adaptabilidad socio-familiar. Vínculos con los otros familiares, funcionamiento dentro del hogar. Impulsiones. Valoración de la red de apoyo psicosocial (A.S. – citar flia) y manejo de recursos emocionales de la flia c/ vistas al alta

==== Tratamiento

Internación: en hospital psiquiátrico.

Justificación: por intenso cuadro delirante alucina-torio, con peligro para sí mismo y para terceros, para continencia int. y/o ext. Visitas: restringidas a familiares más aptos.

Destinado a:

1. Cuadro actual: Bps, compensación orgánica.
2. Largo plazo: bPS, si bien mantendremos antipsicóticos a dosis mínimas eficaces de mantenimiento, será fundamentalmente psicosocial, destinado a actuar sobre los pragmatismos y reinserción social.

Equipo multidisciplinario. Visitas continentadoras.

Catatónico: reposición del punto de vista general: hidratación nutrición.

===== Cuadro actual

.Biológico

* (NOTA) según situación clínica valorar inicio c/ APS típicos o atípicos

Haloperidol: neuroléptico incisivo, antidelirante, 5 mg i/m c/12 hs (H 8:00 y H 20:00). Estaremos alertas a la aparición de efectos secundarios extrapiramidales (rigidez, rueda dentada, bradiquinesia, temblores). Si aparecen, concentraremos las dosis en la noche ya que durante el sueño éstos no se producen. Si con esta medida no podemos controlar-los,

agregaremos antiparkinsonianos de síntesis tales como el Biperideno 2 mg

v/o H 8:00 y H 14:00. Lo agregaremos de entrada si existen AP de parkinsonismo o efectos secundarios o AF de enfermedad de Parkinson.

En caso de tratarse de un hombre joven < 35 años, hay > riesgo de distonía aguda: actitud expectante. Si aparece: 5 mg i/m de Biperideno, con lo que calma inmediatamente, manteniéndolo cada 8 horas x 24-48 horas y luego pasaremos a v/o al tiempo que ® el Haloperidol a dosis mínima eficaz.

Sedación con (preferible BZD)

. Levomepromazina: 25 mg i/m H 8:00 y 50 mg i/m h: 20:00.
. Clonazepam (Rivotril) 2 mg c/8 (control de impulsos y sedación)
. Lorazepam (Ativan) vía I/M
. Propericiazina (Neuleptil) 5 mg c/8 (control de impulsos)

Para insomnio: Flunitrazepam 2 mi v/o h:20:00.

Si el cuadro no mejora, no apareciendo autocrítica delirante, agregaremos a los pocos días otros 5 mg IM de Haloperidol H 14:00.

Al lograr la estabilización de los síntomas, pasa-remos la medicación a v/o a igual dosis, lo que equivale a una ® de la dosis del punto de vista de la biodisponibilidad.

Si a los 10-15 días no existe mejoría considerable del cuadro delirante alucinatorio, indicaremos ECT a realizar por psiquiatra y anestesista. Realizaremos una sesión día por medio, con oxigenoterapia, monitoreo ECG y EEG con barbitúricos de acción corta y curarizantes como la succinilcolina... (resto del papo).

Importa destacar que se trata de un tratamiento de segunda elección que procurará atacar el síndrome delirante, intentando ® dicha sintomatología no teniendo incidencia en el proceso crónico.

APS ATÍPICOS (SDAs)

RISPERIDONA . actualmente se utiliza de 1ª línea

. fuerte antagonismo 5HT 2 / acc selectiva a nivel del sist límbico con igual efecto APS : < EP / SNM < 1% / < DT / < hiperprolactinemia / < alt CV (mejor en viejos)

. dosis : 1º día – 1mg / 2º día – 2 mg / dosis usual de 2 a 4 mg

. resistentes : se puede llegar hasta 4 a 6 mg / muy resistentes : + de 6 mg, hasta 12 mg (dosis máx)

. se invoca > efectividad que clásicos sobre sínt (-)

CLOZAPINA

Criterios de administración

* NO RESPUESTA : al menos 6 semanas de prueba terapéutica previa con 2 antipsicóticos convencionales de clases diferentes.
* INTOLERANCIA : reacciones adversas intratables provocadas por APS convencionales.

Mecanismo de acción :< afinidad D2 que los clásicos / bloq D1 equivalente a D2 + bloq 5HT2 / > especificidad en D2 mesolímbico razón por la cual raramente ocurren ef 2º EP (acatisia, disk aguda, parkinson) y no existen reportes de Disquinesia Tardía (otra indicación de clozapina)

. riesgo de agranulocitosis : 2% en 1er año de trat / enteramente reversible si el tto se suspende en forma precoz : monitoreo sanguíneo regular / CON-SENTIMIENTO INFORMADO / hemograma semanal x 18 sem y luego mensual / ef 2º idiosincrásico / 75% de casos reportados entre 4 -18 sem

Valoración pre tto : anamnésico : AP de agranulocitosis por drogas - alt MO / hemograma c/ fórmula leucocitaria (rango normal : leucocitos 4 a 11 mil - neutrófilos 2500 a 7500 / AP neurológicos ( s/t convulsiones) / evaluación cardiológica

. contraindicaciones : AP de agranulocitosis x dro-gas / recuento leucocitario bajo previo (< 3,5 x 10 a la nueve) / trast M.O. actual o en AP / uso concomitante de otro supresor de M.O. (cbz, ojo c/ fenotiazínicos)
. posología : inicio por 25 mg / día probar tolerancia (sedación y P.A.) y aumentos diarios de 25-50 mg hasta 300 / día en 7-14 días / eficacia antipsicótica entre dosis de 300 y 450 mg / día / dosis máx recomendada 600 mg, a/v requieren hasta 900
. Hipotensión ortostática en administración inicial: tomar precauciones si hay administración concomitante de anticolinérgicos, hipotensores, BZD
. sedación, ef colateral frecuente, concentrar la po-sología en la noche
. convulsiones, ef 2º dosis dependiente, riesgo por encima de 450 mg, agregar valproato siempre (anti-convulsivante que no aumenta riesgo de agranulocitosis) / riesgo : enf cerebral previa - dosis : 4-5 % entre 600-900 mg / reducir dosis y buscar patología subyacente responsable / continuar con dosis < /
. luego de benef terap máx se puede pasar a mantenimiento titulando hacia abajo hasta un rango de 150- 300 / día
. índice de resp en resistentes a tto convencional : 30% mejoran en 6 sem / 55% mejoran luego de un año
. luego de beneficio terap máx se puede pasar a do-sis de mantenimiento titulando hacia abajo hasta un rango de 150-300 mg / día
. el índice de respuesta en ptes resistentes a tto convencional es de mejoría de 30 % en 6 sem y 55 % luego de un año
. respuesta pobre luego de 6 meses : niveles plasmáticos : 350 nanogr / ml (s/t si es fumador)
. ideal descenso lento c/ wash out de 24 hs y titulación lenta de Clozapina / si hay graves elementos de des-compensac se pueden superponer / post depot espe-rar 4-6 sem / adición de otro NL > riesgo de ef 2º EP
. "olvido de tomar" : < 48 hs : reiniciar tto c/ = dosis / > 48 = patrón que esquema inicial
. interrupción del tto LENTA a razón de 25-50 mg/d en período de 1-2 sem
. psicoeducación : reporte inmediato de cualquier sg de infección
. monitoreo leucocitario : semanal en 1ª 18 sem / luego mensualmente / 4 sem post a discontinuación
. si disminuye x debajo de 3500 o hay sgs de infección repetir urgente / si se interrumpe y el nº de leucocitos no baja de 3000 ni neutrófilos de 1500 se puede reiniciar con esquema inicial / si encontramos leucocitos entre 3 mil-3500 o neutrófilos entre 1500-2 mil realizar 2 hemogramas por semana
. efectos 2º ( por acc sobre receptores muscarínicos, adrenérgicos, anti H1)
. sedación y fatiga : usualmente transitorio / reducir dosis, titulación lenta / descartar interacc c/ OH u otras drogas / concentrar mayoría de dosis en la noche
. sialorrea : reducir dosis, titulación lenta / dormir sobre toalla / dosis bajas de amitriptilina (10 a 25) o clonidina
. hipertermia benigna
. aumento de peso (por antagonismo 5HT)
. hipotensión : usualmente transit / ojo ancianos y cardiópatas / titulación lenta / educación
. taquicardia
. leucocitosis

Psicosocial Entrevistas frecuentes para control evolutivo, pro-moviendo una relac individualizada médico-paciente, tratando de ser flexibles ante un pte hostil y negativista

Laborterapia intrahospitalaria ni bien mejore su contacto con la realidad.

Psicoeducación de la familia: con explicación del pronóstico, jerarquizando la importancia de la familia en cuanto a su participación en controles, medicación y detección de sintomatología temprana de descompensación y efectos secundarios.

Otorgaremos el alta hospitalaria cuando haya retrocedido el cuadro delirante alucinatorio, sabiendo que la remisión puede ser parcial.

Controlaremos semanalmente en policlínica e iremos espaciando los controles según la evolución hasta hacerlo mensualmente.

===== A largo plazo

. medicación efectiva + entrenamiento socializante (rehabilitación / psicoeducación)

Biológico

Realizaremos medicación neruoléptica: al principio con igual dosis con la que tuvo mejoría, ya que el ingreso al hogar puede significar un estrés importan-te. Por tratarse de un paciente con bajo perfil de cumplimiento, si bien preferimos la medicación v/o que nos permite un mejor manejo de la dosis, indi-caremos previo al alta NL de depósito como:

. Decanoato de Haloperidol 50-100 mg c/21 días i/m
. Palmitato de Pipotiazina 50 mg i/m cada 4 semanas.

Controlaremos la aparición de efectos secundarios extrapiramidales y el recrudecimiento de su sintomatología delirante, Eventualmente y según la evolución agregaremos antiparkinsonianos de síntesis y/o benzodiacepinas, sustituyendo a la levomepromacina, ya que preferimos no asociar dos neurolépticos en el tratamiento crónico.

A largo plazo valoraremos la ® de la medicación hasta dosis mínima eficaz (luego del 1º año asintomático).

Psicosocial Realizaremos entrevistas de apoyo, conectaremos con talleres grupales y comunidad terapéutica para rehabilitación y resocialización.

Dada la fragilidad de estos pacientes y su baja tolerancia a las exigencias debemos ser cautos y gradualistas en las metas planteadas.

Si trabaja: destinado a mantener el pragmatismo laboral y mejorar los otros. La rehabilitación es fundamental en el pronóstico actuando sobre el retraimiento y los elementos negativos de discordancia. Procuraremos la mejoría de su funciona-miento global, buscando proporcionarle un mayor grado de autonomía, reducir su tendencia al aislamiento estimulando contactos sociales. Se realizará entrenamiento en habilidades sociales potenciando sus actividades conservadas y reorientación ocupacional adaptándola a sus capacidades.

Realizaremos psicoeducación incluyendo a la familia: buscando aceptación de la enfermedad (ya que tienden a la negación), explicaremos las características de ésta para mejor manejo de la familia, procuraremos, con criterio realista, reducir las expectativas del núcleo familiar tratando de disminuir la emotividad expresada y la hostilidad, factores responsables de recaídas. Insistiremos acerca de la importancia de los controles y motivaremos la rápida consulta en caso de descompensación y conecta-remos a grupos de autoayuda.

NOTA: si es tipo catatónico: Haloperidol 5 mg y ver , e ir hasta 10 ya que puede (¿?) signos de catatonía según la tolerancia del paciente (si no recibió nunca). Para la impulsividad catatónica en la esquizofrenia catatónica: Clonazepam 2 mg VO c/8 hs, rápida sedación, teniendo cuidado con el aumento del umbral convulsivo. Ir aumentando de a 2 mg/día hasta 16 mg: 4 - 4 - 8).

No preferimos la Pipotiazina porque el tratamiento debe ser mantenido a largo plazo y al agregar Haloperidol aumenta la posibilidad de disquinesias tardías.

Complicaciones de la esquizofrenia catatónica: estupor, actos ML, actos impulsivos.

==== Evolución y pronóstico

Pronóstico vital y psiquiátrico inmediato: lo consideramos bueno con las medidas instituidas.

Pronóstico psiquiátrico alejado: es una enfermedad crónica con frecuentes recaídas con tendencia al deterioro psicointelectual y social progresivos (ausencia de iniciativa, aplanamiento de respuestas emocionales, descuido personal y declinación de la competencia laboral). Intentaremos mitigar esta evolución con las medidas mencionadas. La forma clínica influye en el pronóstico siendo la forma paranoide la de más bajo potencial evolutivo autista (las hebefrénicas son más rápidas).

En lo vital alejado:

* menor expectativa de vida por mayor morbi-mortalidad que población general (tabaquismo intenso)
* IAE frecuente en contexto discordante • IAE por de frecuencia de depresiones • efectos secundarios del tratamiento biológico

Elementos de mal pronóstico:

* Menor edad de comienzo: ley de masividad
* Bajo nivel intelectual
* Inicio insidioso
* MSEC deficitario
* Múltiples internaciones previas (sobre todo que sean más de 3 recaídas).
* Funcionamiento premórbido alterado
* AF esquizofrénicos
* Aplanamiento afectivo u otros síntomas negativos
* Forma clínica hebefrénica o catatónica
* Poca colaboración familiar
* Perfil de adhesión pobre al tratamiento / antecedentes de abandono de la medicación
* Consulta tardía
* Mala respuesta a la terapéutica

Elementos de buen pronóstico:
* Comienzo agudo
* Buena adaptación social premórbida
* Coexistencia de alteraciones afectivas (cuadros depresivos). En caso de ser prominentes, considerar diagnóstico diferencial con Trastorno Esquizoafectivo.

=== Encare

==== Agrupación sindromática

===== Síndrome disociativo-discordante

Ambos términos son equivalentes y califican el mismo fenómeno mórbido que consiste en la descomposición segregativa (ruptura, disociación) de la vida psíquica con pérdida de la integración armónica de los campos constitutivos de la persona, involucrando conductas, humor, afectividad y pensamiento, que se manifiesta al observador por 4 síntomas capitales (IDEA):

• Impenetrabilidad: hermetismo y tonalidad enigmática que caracteriza al desorganizado mundo del sujeto por lo cual no se encuentra sentido a sus expresiones.

• Desapego: vuelta del sujeto sobre sí mismo, con abandono a la ensoñación interior, en la cual afectos e intereses no se vuelcan en la realidad. Ambos síntomas (impenetrabilidad y desapego) evocan la retracción a un mundo autista.

• Extravagancia: carácter insólito, bizarro e incomprensible para el observador de conductas, palabras y afectos expresados.

• Ambivalencia: antagonismo simultáneo / sucesivo de 2 experiencias contradictorias sin que el paciente capte contradicción alguna objetivable por terceros, lo que configura una ambivalencia psicótica.

Estos síntomas se manifiestan en: pensamiento, afecto y conducta.

Pensamiento

Impenetrabilidad: pensamiento: oscuro, enmarañado, incoherente, caótico, con pérdida de la secuencia asociativa lógica que nos muestra un trastorno asociativo a este nivel, junto a las pararrespuestas, alteraciones fonéticas, sintácticas y semánticas (neologismos).

Desapego: este "modo" de pensamiento responde a un simbolismo mágico interno, que lleva al lenguaje a un desvío de su legítima función, no estando destinado a establecer contacto con el entrevistador.

Extravagancia: en las explicaciones que da a su motivo de ingreso.

Ambivalencia: su relato está poblado de contradicciones.

Estas alteraciones nos muestran una ataxia intrapsíquica, hecho fundamental de la discordancia del pensamiento, en la cual, pese a la inexistencia de un déficit intelectual, está profundamente alterado el uso y la eficacia de sus operaciones intelectuales.

Afectividad

Impenetrabilidad: se manifiesta por las relaciones afectivas incomprensibles (bruscas reacciones emocionales, calma inexplicable) que escapan a toda comprensión de su motivación psicológica. Las expresiones provienen de un mundo interior hermético, resultando enigmáticas al observador. Respuestas emocionales paradojales.

Desapego: se manifiesta por la incapacidad de vibrar con el relato, la dificultad en el encuentro, la indiferencia. Atimormia: desinterés afectivo, apariencia desvitalizada, inercia aparente, interrupción del continuo intercambio entre el mundo y el sujeto. Intento de negar la afectividad, de destruir su significación (grado máximo de desapego).

Extravagancia: está dada por las manifestaciones paradójicas y absolutamente desconcertantes: "odio feroz por un niño pequeño, deseo incontrolable de poseer un piano en una casa chica, pánico ante una corbata azul" (de Ey, textual).

Ambivalencia: se observa en la presencia simultánea de deseos de abrazar y escapar de su novia (ejemplo de la historia clínica).

Conductas

Impenetrabilidad: en cuanto a su motivación psicológica.

Desapego: actos desvitalizados, ruptura con el devenir del ambiente, acciones absolutamente personales, "obrar autístico".

Extravagancia: muestra liberación de pulsiones (conductas alimentarias, sexuales, etc.).

Ambivalencia: con ambitendencia.

===== Síndrome catatónico

Máximo de discordancia en la psicomotricidad. CINE MIE

Catalepsia: plasticidad, rigidez, fijación de actos o perseverancia de actitudes (impuestas o espontáneas), flexibilidad cérea.

Inercia: actitudes de pasividad y automatismo, latencia en las respuestas, obediencia automática.

Sugestibilidad: ecomimia, ecopraxia, ecolalia.

Negativismo: conductas de rechazo, mutismo, oposición al interrogador, rechazo de alimentos.

Estupor: máximo de inhibición psicomotriz. Perdida de la iniciativa motriz sobre el cual se instalan impulsiones, episodios excitomotrices heteroagresivos en cortocircuito. Disminución de reactividad al entorno se caracteriza por lo enigmático y absurdo.

Manierismos: tonalidad de afectación teatral, pateticismo: paramimias, risas inmotivadas.

Impulsiones: actos incoercibles que escapan al control del paciente: hetero o autoagresivos, defenestración, fugas, verbales. Son inmotivados, incompartibles.

Estereotipias: conductas caracterizadas por la iteración: de movimientos, de actitudes, lenguaje (verbigeración), de conductas.

===== Síndrome delirante o síndrome de alteración del pensamiento

En lo formal: incoherente, sin finalidad, con pérdida de la secuencia asociativa lógica. Interceptación: alto brusco y completo de la actividad asociativa. Conexiones accidentales, asociación por el sonido. Estereotipias (persistencia de la idea). Fading mental. 
En el contenido: conformando un síndrome delirante que se manifiesta en lo vivencial por ideas mórbidas incompartibles, irreductibles a la lógica, carentes de juicio de realidad y que le generan conductas. 
A temática: persecutoria, de daño y perjuicio, mística, megalomaníaca, transformación corporal, higiene, influencia, posesión. 
A mecanismo: intuitivo (se le aparece como verdad revelada), interpretativo (percepciones reales que el paciente interpreta a la luz de sus propias convicciones), alucinatorio (eco, robo, adivinación, enunciación de comentarios o actos, anticipación de actos, órdenes). Mal sistematizado: sus componentes no guardan una lógica, presentan movilidad, carácter cambiante y mínima organización, sin progreso discursivo, carencia de hilo argumental, por lo cual decimos que corresponde a una estructura paranoide. En lo conductual: conductas generadas por el delirio (auto y heteroagresividad, etc.) 

Dentro del síndrome delirante puede formarse un: síndrome de automatismo mental Dado por la pérdida de la intimidad del espacio intrapsíquico, en su forma de triple automatismo, conformado por fenómenos de desdoblamiento alucinatorio del pensamiento que se imponen a la conciencia del sujeto a pesar de su yo, dado a nivel: Ideoverbal: por alucinaciones acústico-verbales que enuncian y comentan actos y pensamientos, eco del pensamiento y de la lectura, robo y adivinación del pensamiento, estribillos verbales, juegos verbales, jaculatorias fortuitas, psitacismo. Pequeño automatismo: interpretación, parasitismos, coacción. Ideación impuesta, telepatía, mentismo xenopático. Sensorial-sensitivo: parasitación de las percepciones. Alucinaciones: visuales, gustativas, olfativas, cenestésicas. Psicomotor: impresiones cinestésicas de imposición de movimientos, articulación verbal forzada. Dada la jerarquía se puede individualizar: síndrome de Influencia o control externo: el individuo se siente manejado, influido por fuerzas externas a él. síndrome de despersonalización Pérdida del sentido de familiaridad de la persona consigo misma y con el entorno, que afecta la integridad somática corporal, la identidad y la conciencia del yo y que acompaña a la expresión de extrañeza e incluso de cambio total del mundo exterior. . Alteración del esquema corporal: alucinaciones somatognósticas, ilusión de desplazamiento o distorsión, metamorfosis segmentarias, miembros fantasmas. . Desrealización: cambio de ambiente, falta de familiaridad con el ambiente. . Desanimación: sentimiento de vacuidad, sin vida. . Tendencia al autoanálisis (signo del espejo). 

síndrome del humor y la afectividad Humor oscilante, lábil, humor inadecuado, inadaptado (discordancia). Exaltación, oscilante de acuerdo al contenido temático. Ansiedad.

===== Síndrome deficitario social

En el corte longitudinal pragmatismos. Retracción social de X evolución, con abandono de metas y proyectos de futuro, con pérdida de relación con sus amigos y familia con deterioro en su actividad como ser social. Déficit de rendimiento como persona social (CB y Pragmatismos).

===== Síndrome conductual

Conductas que motivan el ingreso: impulsión catatónica, comando alucinatorio. Se objetiva en conductas basales y pragmatismos.

==== Personalidad y nivel

Nivel: buen nivel y rendimiento, hasta que se produce un corte. Personalidad premórbida: deben confirmarse datos con terceros ya que no es un paciente confiable. Esquizoide. Corte existencial: cambio de conductas con introducción lenta en un mundo cada vez más personal que lo lleva en X tiempo a un deterioro social.

==== Diagnóstico positivo

===== Nosografía clásica

.Psicosis
Ver definición.

.Psicosis crónica
Por tratarse de un trastorno perdurable de X años de evolución que ha modificado el sistema de la personalidad llevando a una transformación delirante del yo y su mundo constituyéndose el paciente en un ser delirante, siendo el delirio más relatado que vivido, no existiendo elementos de agudeza tales como alteración de la conciencia y oscilaciones del humor.

.Esquizofrenia
Síndrome disociativo-discordante o elementos de síndrome catatónico, impregnado de elementos disociativos discordantes. síndrome delirante de estructura paranoide expresado sin calor afectivo. Corte existencial a los X años con ruptura histórico-biográfica. Curso progresivo deteriorante con elementos de retracción a un mundo autista. Además: edad, AF de esquizofrenia, leptosómico, personalidad previa esquizoide. En período de estado: por estar el SDD ya instalado, porque su relación con el mundo no ha claudicado en su totalidad.

Tipo clínico

A. Hebefrénico: adolescente o adulto joven (15-25 años), SDD, jovialidad pueril, desorganización conductual, irresponsables, imprevisibles, rápido deterioro, no predomina el delirio (transitorio y fragmentario).

B. Catatónico: según el síndrome catatónico. Cuadro de inercia sobre el que sobrevienen bruscos brotes de impulsividad. Estuporosa (reacciones violentas), agitada (violencia extrema), catatonismo (discordancia PM).

C. Paranoide: adulto joven, cuadro centrado en el delirio paranoide, aunque existen elementos DD, pese al tipo de evolución no existe deterioro marcado.

D. Simple: pérdida insidiosa del interés o motivación, ambición o iniciativa.

E. Indiferenciado: CIE-10, DSM, sin claro predominio de ningún tipo.

Descompensada

Por presentar alteración de las conductas basales, empeoramiento en pragmatismos, oscilaciones o alteraciones del humor.

Causa de descompensación

Está descompensado debido a:

• Aumento de la productividad delirante con elementos paranoides, de influencia.
• Aumento en el monto de agresividad: impulsión catatónica.
• Exacerbación de sintomatología: delirante, catatónica.
• Trastornos conductuales.

Causa de descompensación: abandono de medicación - estrés psicosocial.

DSM IV

Esquizofrenia:

• A. 2 síntomas de 5 (delirio, alucinaciones, lenguaje desorganizado, comportamiento desorganizado o catatónico, síntomas negativos [aplanamiento afectivo, alogia, abulia]). (1 síntoma solo si las ideas delirantes son extrañas). O AAV y SAM.

• B. Disfunción social/laboral.

• C. Durante más de 6 meses con al menos 1 mes de síntomas que cumplen el criterio A .

• D. Exclusión de T. Esquizoafectivo y T del E de Animo.

• E. Exclusión de consumo de sustancias y enfermedad médica.

Especificaciones de curso longitudinal:

• episódico (con o sin síntomas residuales)
• continuo
• episodio único (en remisión parcial/total)
• menos de 1 año desde el inicio de síntomas de fase activa

Otros especificadores:

• con síntomas negativos acusados
• Tipo: paranoide, desorganizado, catatónico, indiferenciado, residual.

Trastorno Esquizoafectivo:

• A. En algún momento: episodio afectivo + criterio A de esquizofrenia

• B. En el mismo período: 2 semanas de ideas delirantes o alucinaciones en ausencia de síntomas afectivos (para descartar Episodio Afectivo con síntomas psicóticos).

• C. Síntomas afectivos durante una parte sustancial del total de la duración (fases activa y residual) de la enfermedad (para descartar síntomas afectivos puntuales en una Esquizofrenia).

• D. Descartar sustancias y enfermedad médica.

Especificadores: tipo bipolar o tipo depresivo.

Según Kaplan: todo trastorno "cuyo síndrome clínico quedaría tergiversado si se considera sólo como una Esquizofrenia o solo como un Trastorno del Estado de Animo". También según Kaplan: Esquizoafectivo parecería ser el diagnóstico más apropiado ante la duda con una Esquizofrenia.

Diagnóstico diferencial

Con psicosis agudas

PDA: Consideramos que se trata de un brote delirante, descompensación aguda de una enfermedad crónica. Hay SDD, hay períodos intercríticos no libres de síntomas, presenta un curso progresivo deteriorante.

EPA en X patología

Causas orgánicas de delirio

Consumo de sustancias.

Con psicosis crónicas

T Esquizoafectivo :si hay síntomas afectivos en algún momento de la evolución. (Y con TEA en el caso de diagnóstico de T Esquizoafectivo). Con otros delirio crónicos:

A. Paranoia: que descartamos ya que la paranoia presenta un delirio sistematizado, expresado con calor afectivo, de estructura paranoica y en la cual no existe una evolución deficitaria con retirada a un mundo autista como en nuestro paciente.
B. Parafrenia: que descartamos porque la Parafrenia se caracteriza por un pensamiento paralógico, fantástico, a mecanismo imaginativo, pero s/t por el mantenimiento de los pragmatismos, sin deterioro, con la característica bipolaridad con la que coexisten el polo delirante y el polo adaptado a la realidad (edad 30-35 años).

Otros

Puede plantearse con Psicosis Infantil (DSM: Trastorno Generalizado del Desarrollo) si se sospecha inicio muy temprano.

Retraso Mental: esquizofrenia es 3 veces más frecuente que en la población general.

Depresión psicótica.

Neurosis obsesiva / TOC

De forma clínica de esquizofrenia

Con respecto a la forma clínica de esquizofrenia.

Diagnóstico etiopatogénico y psicopatológico

Etiopatogenia

Es una enfermedad multifactorial.

Biológico

Genéticos: familiares de primer grado riesgo aumentado para el desarrollo de la enfermedad.

Biotipológicos: leptosómico de Kretschmer.

Bioquímicos: alteración/disregulación dopaminérgica en el sistema meso-limbo-cortical ( de sensibilidad de receptores postsinápticos de Dopamina) que explicarían la acción de los neurolépticos. También se postula alteración a nivel de los receptores de Serotonina que explicaría la acción de neurolépticos de nueva generación.

Anatómicos: vinculados a formas deficitarias, con anomalías estructurales inespecíficas en la TAC y RNM con de ventrículos laterales. PET y SPECT (utilización de glucosa por el cerebro y valoración del flujo sanguíneo) muestran hipoactividad en lóbulo frontal y actividad anormal en varias áreas del cerebro.

Psicológico

Personalidad premórbida esquizoide o esquizotípica.

Social

Lo que haya en su historia personal que actuaría en un terreno vulnerable. Factores de relación con el medio familiar, más vinculado a las recaídas que al debut.

Causa de descompensación:

* abandono de medicación
* empuje evolutivo de la enfermedad
* estrés psicosocial

Psicopatología

Para el psicoanálisis, significa una regresión (regresión narcisista de la libido) y fijación a etapas pregenitales del desarrollo psicosexual, con utilización de mecanismos de defensa psicóticos, de negación de la realidad proyectando la angustia en el delirio. Se trataría de una pérdida de la autonomía narcisista del yo, vinculada a una falla en las identificaciones primarias.

Para Jaspers, la esquizofrenia es un proceso que cambia la estructura con fragmentación y creación de nuevo estado de personalidad con ruptura histórico-biográfica de la existencia.

==== Paraclínica

El diagnóstico es clínico. Historia anterior: corroborar el curso de la enfermedad, rendimiento pragmático, tratamientos recibidos y respuesta a ellos, grado de adhesión al tratamiento, comunicación con psiquiatra tratante.

Biológico

Valoración general, s/t neurológica y fondo de ojo. TAC: aspectos estructurales. Valoración pre-ECT para descartar contraindicaciones: ECG y consulta con cardiólogo para descartar IAM reciente y arritmias inestables. Examen neurológico completo con fondo de ojo para descartar hipertensión endocraneana por masa supratentorial. RxTx FyP para descartar aneurisma de aorta.

Psicológico

Profundizar en los datos aportados por el paciente. Superado el cuadro actual: test de personalidad proyectivos y no proyectivos, test de nivel. Apreciaremos el grado de psicoticismo, así como ansiedades primitivas.

Social

Adquiere jerarquía y empezar por él si sólo hay datos aportados por el paciente. Consentimiento informado para la realización de ECT. Despejar temores, explicar riesgos, beneficios y efectos secundarios. Historias anteriores, medicación recibida y respuesta a ella, períodos intercríticos con nivel de adaptabilidad socio-familiar. Vínculos con los otros familiares, funcionamiento dentro del hogar. Impulsiones. Valoración de la red de apoyo psicosocial (AS, citar familia) y manejo de recursos emocionales de la familia con vistas al alta.

==== Tratamiento

Internación: en hospital psiquiátrico. Justificación: por intenso cuadro delirante alucinatorio, con peligro para sí mismo y para terceros, para continencia int. y/o ext. Visitas: restringidas a familiares más aptos. Destinado a:

1. Cuadro actual: Bps, compensación orgánica. 2. Largo plazo: bPS, si bien mantendremos neurolépticos a dosis mínimas eficaces de mantenimiento, será fundamentalmente psicosocial, destinado a actuar sobre los pragmatismos y reinserción social. Equipo multidisciplinario. Visitas continentadoras. Catatónico: reposición del punto de vista general: hidratación nutrición.

Cuadro actual

Biológico

Antipsicótico

Primera línea Como medicación principal usaremos un antipsicótico siendo de primera elección el uso de antipsicóticos atípicos, proponiendo el uso de Risperidona, con antagonismo a nivel de receptores 5HT y acción selectiva a nivel del sistema límbico, con similar efecto antipsicótico que los neurolépticos incisivos clásicos pero con menor incidencia de efectos secundarios extrapiramidales, síndrome neuroléptico maligno, discinesias tardías e hiperprolactinemia (con el beneficio de menor alteración a nivel cardiovascular, sobre todo en personas añosas). Comenzaremos con 1 mg c/12 horas el primer día, pasando a 2 mg c/12 horas el segundo día, siendo la dosis habitual ente 2 a 4 mg/día, pudiendo llegar a 6 mg/día. Dosis superiores hacen que éste antipsicótico tenga un comportamiento similar a los neurolépticos típicos.

.Nota
Síndrome Neuroléptico Malgino: puede ser causado por TODOS los antipsicóticos. Incidencia 0.2%, sobre todo con AP1G incisivos (Haloperidol en el 44% de los casos), menor con AP2G. AP1G sedativos no tienen registro como causa única de SNM. Factores de riesgo: patología orgánica preexistente, uso concomitante de litio, infección, retirada de anticolinérgicos o alcohol. footnote:[Schneider, M., Regente, J., Greiner, T., Lensky, S., Bleich, S., Toto, S., ... & Heinze, M. (2020). Neuroleptic malignant syndrome: evaluation of drug safety data from the AMSP program during 1993–2015. European Archives of Psychiatry and Clinical Neuroscience, 270, 23-33.]. Es más frecuente en hombres en un 50%, sobre todo jóvenes. footnote:[Gurrera, R. J. (2017). A systematic review of sex and age factors in neuroleptic malignant syndrome diagnosis frequency. Acta Psychiatrica Scandinavica, 135(5), 398-408.] Se plantea que es causado por el bloqueo de receptores D2 de centros reguladores del hipotálamo y tronco cerebral que provocan un síndrome hipermetabólico generalizado sistémico. Otros factores: agitación psicomotriz, extenuación, deshidratación, malnutrición, episodios previos de SNM (17-30% de incidencia si se someten nuevamente a antipsicóticos), aumento rápido de dosis, via parenteral, dosis altas totales. Clínicamente: alteración de conciencia / delirium / estupor catatónico, rigidez muscular generalizada (plúmbea), fiebre, temblor, sialorrea, aquinesia, distonía, trismo, mioclono, disartria, disfagia, rabdomiolisis. Secuencia habitual: alteración de conciencia → rigidez muscular → fiebre → disfunción autonómica.

Notas: Trastorno Esquizoafectivo Se agregan pautas de tratamiento de Trastornos Afectivos (estabilizadores en subtipo Bipolar, antidepresivos en subtipo Depresivo), con menor énfasis en el tratamiento con antipsicóticos (preferentemente atípicos).

ECT planteable en cualquier nivel del protocolo terapéutico.

Segunda línea En caso de no ser posible el uso de la vía oral, usaremos Haloperidol (neuroléptico incisivo, antidelirante) 5 mg i/m c/12 hs (H 8:00 y H 20:00). Estaremos alertas a la aparición de efectos secundarios extrapiramidales (rigidez, rueda dentada, bradiquinesia, temblores). Si aparecen, concentraremos las dosis en la noche ya que durante el sueño éstos no se producen. Si con esta medida no podemos controlarlos, agregaremos antiparkinsonianos de síntesis tales como el Biperideno 2 mg v/o H 8:00 y H 14:00. Si existen AP de parkinsonismo o efectos secundarios o AF de enfermedad de Parkinson, valoraremos la posibilidad de uso de neurolépticos atípicos. En caso de tratarse de un hombre joven < 35 años, hay > riesgo de distonía aguda: actitud expectante. Si aparece: 5 mg i/m de Biperideno, con lo que calma inmediatamente, manteniéndolo cada 8 horas x 24-48 horas y luego pasaremos a v/o al tiempo que disminuimos el Haloperidol a dosis mínima eficaz. Por otro lado valoraremos la posibilidad de usar un antipsicótico atípico. Refractariedad En caso de tratarse de un paciente en tratamiento, que no ha mostrado respuesta a 2 antipsicóticos diferentes usados por tiempo adecuado a dosis adecuada, puede plantearse el uso de otros antipsicóticos atípicos como la Olanzapina o la Clozapina. Preferimos la primera por la menor incidencia de efectos secundarios. En caso de usar Olanzapina, comenzaremos con 5 mg/día probando tolerancia y aumentando luego a 10 mg/día. En caso de no haber respuesta puede aumentarse a un máximo recomendado de 20 mg/día. El beneficio de este fármaco es la baja incidencia de efectos secundarios y acción sobre los síntomas negativos de la enfermedad. Con respecto a la Clozapina, su mecanismo de acción tiene la particularidad de presentar menor afinidad por los receptores D2 que los NL típicos. Tiene un bloqueo D1 equivalente a D2, y además bloquea los receptores 5HT2, con mayor especificidad por los D2 del sistema meso-límbico, por lo cual no solo son extremadamente raros los ES extrapiramidales sino que la presencia de éstos con otro antipsicótico puede ser una indicación para el uso de Clozapina (especialmente en el caso de la Disquinesia Tardía). El uso de Clozapina requiere de una valoración clínica y paraclínica previa con controles sistemáticos a nivel hematológico por el riesgo de agranulocitosis (2% en el primer año de tratamiento, reversible si se suspende el tratamiento en forma precoz): hemograma semanal por 18 semanas, luego mensual. La agranulocitosis, efecto secundario idiosincrático, en un 75% de los casos aparece entre las semanas 4 y 18. También serán excluidos aquellos pacientes con AP de crisis comiciales por la posibilidad de descen so del umbral convulsivo. Son contraindicaciones para el uso de Clozapina: • un recuento leucocitario bajo (<3500) • trastornos de la médula ósea actuales o previos • uso concomitante con otro medicamento que pueda tener efecto supresor sobre la MO (Carbamazepina, Fenotiazinas). Se inicia con 25 mg v/o al día probando tolerancia (sedación, hipotensión), con aumentos diarios de 25-50 mg hasta llegar a 300 mg/día en 7-14 días. Las dosis usuales están entre 300 y 450 mg/día, con un máximo de 600 mg/día (dosis superiores requieren de una estricta supervisión clínica y paraclínica, siendo el riesgo de convulsiones dosis-dependiente). Se destaca la necesidad de adhesión al tratamiento por parte de paciente y familiares al requerir controles hematológicos, destacándose que en caso de abandono de medicación mayor a 48 horas, debe reiniciarse el tratamiento con el esquema posológico mencionado. En caso de retirar la Clozapina, se ha descrito peoría del cuadro subyacente y menor eficacia de la medicación al reinstaurarla. En caso de retirarla, deben continuarse los controles hematológicos por 4 semanas post-discontinuación. Efectos secundarios: por acción sobre receptores muscarínicos, adrenérgicos e histamínicos (sedación, fatiga, sialorrea, hipertermia benigna, aumento de peso [antagonis mo 5HT], hipotensión, taquicardia).

Sedación

Preferimos el uso de benzodiacepinas frente a los neurolépticos sedativos: . Lorazepam i/m . Clonazepam 2 mg v/o c/8. De segunda línea: Levomepromazina: 25 mg i/m H 8:00 y 50 mg i/m h: 20:00.

Insomnio

Para insomnio: Flunitrazepam 2 mg v/o - i/m h:20:00 . La medicación para lograr sedación (Lorazepam) y para el insomnio (Flunitrazepam) se puede realizar vía i/m si el cuadro así lo amerita, pasando tan pronto como sea posible a la v/o.

Si no mejora

Si el cuadro no mejora, no apareciendo crítica del delirio, agregaremos a los pocos días otros 5 mg i/m de Haloperidol H 14:00.

Si estabiliza

Al lograr la estabilización de los síntomas, pasaremos la medicación a v/o a igual dosis, lo que equivale a una disminución de la dosis desde el punto de vista de la biodisponibilidad.

ECT

Si a los 10-15 días no existe mejoría considerable del cuadro delirante alucinatorio, indicaremos ECT (ver speech para ECT en otros encares). Importa destacar que se trata de un tratamiento de segunda elección que procurará atacar el síndrome delirante, intentando disminuir dicha sintomatología no teniendo incidencia en el proceso crónico. Existen circunstancias en las que la ECT puede considerarse de primera elección: • En pacientes catatónicos que no responden al tratamiento intramuscular en 48 horas y que presenten riesgos del punto de vista físico. • Si existe riesgo grave de suicidio • Casos de evolución desfavorable reiterada con AP de buena respuesta a ECT Secuencia preferible: NLA -> NLT -> ECT -> Clozapina. Cada prueba terapéutica por 6-7 semanas (Clozapina x 12 semanas). En cada cambio suprimir gradualmente el anterior mientras se inicia gradualmente el siguiente.

Psicosocial

Haremos entrevistas diarias para un control evolutivo y para afianzar el vínculo, promoviendo una relación individualizada médico-paciente, tratando de ser flexibles ante un paciente que puede ser hostil y negativista. Laborterapia intrahospitalaria ni bien mejore su contacto con la realidad. Psicoeducación de la familiar: con explicación del pronóstico, jerarquizando la importancia de la familia en cuanto a su participación en controles, medicación y detección de sintomatología temprana de descompensación y efectos secundarios.

Alta

Otorgaremos el alta hospitalaria cuando haya retrocedido el cuadro delirante alucinatorio, sabiendo que la remisión puede ser parcial. Controlaremos semanalmente en policlínica e iremos espaciando los controles según la evolución hasta hacerlo mensualmente.

A largo plazo

Biológico

Continuaremos con medicación antipsicótica: al principio con igual dosis con la que tuvo mejoría, ya que el ingreso al hogar puede significar un estrés importante. De tratarse de un paciente con bajo perfil de cumplimiento, si bien preferimos la medicación v/o que nos permite un mejor manejo de la dosis, indicaremos previo al alta NL de depósito como: . Decanoato de Haloperidol 50-100 mg c/21 días i/m . Palmitato de Pipotiazina 50 mg i/m cada 4 semanas. Controlaremos la aparición de efectos secundarios extrapiramidales y el recrudecimiento de su sintomatología delirante, Eventualmente y según la evolución agregaremos antiparkinsonianos de síntesis y/o benzodiacepinas. A largo plazo valoraremos la disminución de la medicación hasta dosis mínima eficaz (luego del primer año asintomático). La dosis mínima eficaz nunca es menor al 25% de la dosis empleada para el control de sintomatología aguda. En caso de Episodio Psicótico Agudo con remisión completa: mantener tratamiento x 1-2 años + controles x 2 años más. Rediagnosticar como Trastorno Psicótico Breve o Trastorno Esquizofreniforme. Primera recaída: reiniciar tratamiento y mantenerlo x el doble de plazo. Segunda recaída: tratamiento de x vida. Psicosocial Realizaremos entrevistas de apoyo, conectaremos con talleres grupales y comunidad terapéutica para rehabilitación y resocialización. Dada la fragilidad de estos pacientes y su baja tolerancia a las exigencias debemos ser cautos y gradualistas en las metas planteadas. Si trabaja: destinado a mantener el pragmatismo laboral y mejorar los otros. La rehabilitación será fundamental en el pronóstico actuando fundamentalmente sobre el retraimiento y los elementos negativos de discordancia. Procuraremos la mejoría de su funcionamiento global, buscando proporcionarle un mayor grado de autonomía, reducir su tolerancia al aislamiento estimulando contactos sociales. Se realizará entrenamiento en habilidades sociales potenciando sus actividades conservadas y reorientación ocupacional adaptándola a sus capacidades. Realizaremos psicoeducación incluyendo a la familia, para mejor manejo de la misma (ya que tienden a la negación), explicaremos las características de ésta para mejor manejo de la familia, procuraremos, con criterio realista reducir las expectativas del núcleo familiar, tratando de disminuir la emotividad expresada y la hostilidad, factores responsables de recaídas. Insistiremos acerca de la importancia de los controles y motivaremos la rápida consulta en caso de descompensación y conectaremos a grupos de autoayuda.

NOTA: si es tipo catatónico: ECT -> Haloperidol 5 mg y ver , e ir hasta 10 mg ya que puede dar signos de catatonía según la tolerancia del paciente (si no recibió nunca). Para la impulsividad catatónica en la esquizofrenia catatónica: Clonazepam 2 mg v/o c/8 hs, rápida sedación, teniendo cuidado con el aumento del umbral convulsivo con vistas a la ECT. Ir aumentando de a 2 mg/día hasta 16 mg: 4 - 4 - 8). Valorar en todos los casos el uso de atípicos. Complicaciones de la esquizofrenia catatónica: estupor, actos ML, actos impulsivos.

==== Bibliografía

* Encares: Dr. Curbelo, Dr. Hazan, Dr. Paullier, Dr. Escobal.
* RTM II
* DSM IV
* Consenso de expertos 1999
