== Trastorno Delirante

=== Notas clínicas

Una buena revisión clínica del trastorno es la realizada por Manschreck footnote:[Manschreck, T. C., & Khan, N. L. (2006). Recent advances in the treatment of delusional disorder. The Canadian Journal of Psychiatry, 51(2), 114-119. ISO 690].

==== Delirio sensitivo de relación (Kretschmer)
Descrito en 1919. 3 componentes footnote[Widakowich, C., Van Wettere, L., Hubain, P., & Snacken, J. (2013). 1938–Actuality of the Kretschmer's sensitive delusion of reference in the DSM V era: two case reports. European Psychiatry, 28(S1), 1-1.]:
* Carácter sensitivo: timidez, hiperemotividad, sensibilidad, sentido elevado de los valores morales, orgullo, hiperestesia emocional, hiperestesia en los contactos sociales. Resulta en alta vulnerabilidad en los contactos sociales, tendencia a la autocrítica, susceptibilidad y tendencia a internalizar fallas percibidas como dolorosas.
* Evento "traumático" vivido como "falla" o "humillación" en plano ético.
* Desarrollo del delirio en si: remordimiento depresivo con miedos hipocondríacos e ideación persecutoria en conversaciones banales cotidianas. Delirio concéntrico: el sujeto es el centro de la experiencia, rodeado por un grupo (cónyuge, familia, vecinos). Formato tipo "proceso".

Aparece en adultos, > 35 años, solteros añosos. En general complicado con un episodio depresivo severo. Evolución menos crónica que la paranoia con tendencia a recurrir ante nuevas humillaciones.
La escuela francesa lo incluye entre los delirios crónicos no disociativos, entre la paranoia, la psicosis alucinatoria crónica y la parafrenia.
Para el DSM queda incluido entre los trastornos delirantes. En otras partes del mundo conceptualizado como "delirio de referencia". La idea delirante queda "suspendida" del acontecimiento desencadenante (divulgación de una enfermedad, denuncia de un robo, acusación de una falta, exclusión de una comunidad). Prototipo: "paranoia de los gobernantes", "delirio de persecución de las solteronas"
 
=== Encare

==== Agrupación sindromática

.Síndrome delirante

De X evolución, en los últimos meses de intensidad, dado en

Lo vivencial

Por ideas mórbidas, incompartibles, irreductibles a la lógica Temática: una predominante y temas derivados: persecutorio, autorreferencial, de daño y perjuicio, acusación moral, hipocondríaca, celos, erotomaníaca, integridad física, bienes. Mecanismos: interpretativo (a partir de hechos reales extrae conceptos erróneos a la luz de sus propias convicciones), intuitivo (se le presenta como verdad revelada) (poco o nada alucinatorio). Bien sistematizado por:

* precedido en el carácter y en la personalidad del paciente
* construido de modo lógico a partir fundamentalmente de interpretaciones falsas
* expuesto con orden, coherencia y claridad por lo que se presenta al observador como relativamente plausible
* polariza la conciencia del paciente, subordinando toda la actividad psíquica a sus fines. El sujeto vive para su delirio y en demanda de un auditorio comprensivo, dedicado a demostrar sus convicciones, las que defiende con calor afectivo. Todo lo cual caracteriza la estructura paranoica del delirio.

Lo conductual

Conductas reivindicativas, heteroagresivas.

.Síndrome de alteración del humor y la afectividad
A. Exaltación, llegando a la indignación, solidario al contenido del relato (que nos muestra el calor afectivo con el que el paciente defiende sus convicciones delirantes) pasional reivindicativo.
B. Configurando a nivel del humor un síndrome depresivo de X evolución (humor, psicomotricidad, dolor moral, CB y pragmatismos) sensitivo de relación con angustia en la afectividad. 

.Síndrome de alteración de las conductas basales y pragmatismos

.síndrome conductual motivando la consulta

==== Personalidad y nivel

Nivel: generalmente bueno.

Personalidad: que confirmaremos con terceros ... adaptación social... rasgos de la serie:

* Sensitivo: susceptibilidad, hiperemotividad, indecisión, timidez y escrupulosidad, inseguridad, rencoroso con sufrimiento interno, tendencia a la inacción ante las ofensas ("guarda ofensas como medallas"). Inhibido, insatisfecho, hiperestesia a los contactos sociales. Asténico.
* Paranoico: desconfianza, aislamiento, orgullo, agresividad, psicorrigidez, falsedad de juicio, hipertrofia del yo (incapacidad de cambiar su posición mental), fanatismo, celoso, rencoroso, estricto moralista, obstinación, reproches, cuestiona lealtad de los demás, lógica falseada por la pasión. Esténico.

==== Diagnóstico positivo

.Nosografía clásica

Psicosis

Por hallarse el paciente sumido en un mundo propio, incompartible, con el que se relaciona de un modo nuevo por él creado, del cual no se puede sustraer voluntariamente, por haber perdido el juicio de realidad, la presencia del delirio analizado, el mal rapport y la carencia de conciencia de morbidez.

Psicosis crónica

por tratarse de un trastorno mental perdurable en el tiempo de X años de evolución, que ha modificado el sistema de la personalidad, llevando a una transformación delirante del yo y su mundo, constituyéndose el paciente en un ser delirante y que se manifiesta como un modo de ser y no de estar en el mundo, siendo el delirio un sistema de creencias inamovibles, con las cuales convive y en el cual existe un trabajo delirante.

Psicosis paranoica

Edad adulta (mitad de la vida), predisposición caracteriológica de la personalidad premórbida, pero s/t por la sistematización y estructura paranoica del delirio ya analizado, con ideas seudológicas que defiende con calor afectivo.

Tipo

Reivindicativo

Ya que está basado en la apreciación delirante de que ha sufrido un perjuicio que lo conduce a plantear quejas o denunciar hechos. Delirio caracterizado por la exaltación (hipertimia, exhuberancia, hiperestesia) con el cual el paciente expone sus convicciones delirantes inamovibles, con la existencia de una idea persecutoria prevalente que subordina toda la actividad psíquica a sus fines, razones para catalogar a éste delirio como de elevado potencial agresivo ya que se trata de perseguidos perseguidores que pueden caer en conductas agresivas de implicancias ML, procurando tomar represalias ante sus perseguidores imaginarios. • Querellantes: reivindica un derecho. • Inventores: revindican un mérito. • Apasionados idealistas, • Hipocondríacos: más o menos querellantes a partir de un acto médico.

Pasional

Exaltación, idea prevalente, potencial agresivo, temible pasaje al acto.

* Celotípico (OH): transformación de una relación de pareja en una relación triangular. Delirio de infidelidad. Pruebas, seudocomprobaciones, falsos recuerdos, interpretaciones delirantes, ilusiones de la percepción o memoria.
* Erotomaníaco: ilusión delirante de ser amado 3 etapas: esperanza - despecho - rencor (alto riesgo de acciones contra el objeto amado). NOTA: Las formas reivindicativas y pasionales comparten características:
** Exaltación: exhuberancia, hiperestesia o hipertimia.
** Idea prevalente: subordina toda su vida, convicción absoluta.
** Desarrollo en sector: el delirio penetra "como una cuña" en la realidad.
* Sensitivo de relación: delirio de bajo potencial agresivo ya que el fondo caracteriológico es menos rígido con reacciones hiposténicas y depresiones. Se desarrolla con angustia y tensión bajo la convicción de ser objeto de un interés enojoso o humillante. El delirante se siente el centro de una malevolencia. Pueden estar prendidos a un acontecimiento pasado y son expresión de conflictos inconscientes entre el paciente y un grupo (delirio de relación). Tendencia a reacciones depresivas. Delirio de relación: es vivido como un conflicto del sujeto con otro o con un grupo (delirio de persecutorio de las solteronas).
* Delirio de interpretación (Serieux y Capgras): temas persecutorios o de grandeza, interpretación, avanza en red, tomando elementos para afirmar el delirio, combativo, convincente. Necesidad de explicación global, interpretación según sistema de significación fundamental (interpretaciones, ilusiones, seudorrazonamientos, suposiciones) elaboración delirante sistematización).

Descompensado

Por: • síndrome depresivo • Aumento de producción delirante (con o sin cambio cualitativo) • síndrome conductual Que ha llevado en los últimos tiempos a una alteración de las conductas basales y pragmatismos (ejemplos).

Causa de descompensación

• Biológico: abandono de la medicación.

• Psicosocial: amenaza a su: intimidad, moralidad rígida, problemática homosexual inconsciente, herida narcisista.

EN SUMA: Delirio crónico paranoico de tipo: • Reivindicativo = inventor, querellante, apasionado idealista • Pasional = celotípico, erotomaníaco. • Sensitivo de relación Actualmente descompensado por X.

.CIE-10 - DSM-IV

Requiere:
A. Ideas delirantes no extrañas (implican situaciones que ocurren en la vida real) de al menos 1 mes de duración +
B. Nunca cumple criterio A de esquizofrenia (pueden haber alucinaciones táctiles u olfatorias si están vinculadas al tema delirante) +
C. Sin deterioro de pragmatismos (excepto por impacto directo de ideas delirantes) +
D. Si hubieron episodios afectivos simultáneamente con ideas delirantes, fueron breves en relación a la duración de los períodos delirantes +
E. Descartar sustancias o enfermedad médica.

Especificadores: TIPO: según tema predominante

* Erotomaníaco: idea delirante de que otra persona (generalmente de status superior) está enamorada del sujeto.
* De grandiosidad: ideas delirantes de exagerado valor, poder, conocimiento, identidad o ralación especial con una divinidad o persona famosa.
* Celotípico: ideas delirantes de que la pareja es infiel.
* Persecutorio: ideas delirantes de que la persona (o alguien próximo) está siendo perjudicada de alguna forma.
* Somático: idea delirante de tener algún defecto físico o enfermedad médica.
* Mixto: no predomina ningún tema.
* No especificado.

==== Diagnósticos diferenciales

. Trastorno de la personalidad:
.. Trastorno paranoide de la personalidad: no delirio, no alteración del juicio de realidad.
. Psicosis agudas:
.. Episodio delirante agudo en un Trastorno paranoico de la personalidad. No pensamos ya que este delirio lleva años de evolución, no existe el inicio brusco ni el polimorfismo ni los trastornos de conciencia de los episodios delirantes agudos.
. Psicosis crónica:
.. Esquizofrenia paranoide: descartamos porque no existe en nuestro paciente una evolución deficitaria, el delirio es sistematizado, de estructura paranoica, y existe el calor afectivo con el que defiende su sistema seudológico de creencias.
.. Parafrenia: con la cual comparte la carencia de déficit con mantenimiento de la actividad pragmática. Pero en la parafrenia existe un pensamiento paralógico, fantástico a mecanismo imaginativo, en general es pobremente sistematizado con estructura paranoide.
.. Otras paranoias.
. Causa orgánica del delirio (enfermedades médicas, sustancias): nos aleja de esta posibilidad: • características de la personalidad premórbida • tipo de evolución • no existencia de datos en la HC Pese a lo cual descartaremos por paraclínica.
. Demencia (según edad) • no existen elementos de déficit intelectual • existen AP de ingresos anteriores por la misma causa (no es el 1° episodio) En la demencia el delirio es más pobre y menos sistematizado.
. Melancolía delirante (el 1° a plantear si es un sensitivo de relación). Si bien en ambos existe depresión y delirio, en nuestro paciente consideramos el S° depresivo como secundario al delirio. En este caso el delirio es generador de sintomatología depresiva (en la Melancolía Delirante el delirio es generado por el estado de humor melancólico). Además en nuestro paciente no existen inhibición psicomotriz ni dolor moral. Nuestro paciente proyecta la culpa y no la introyecta como en la melancolía delirante.

==== Diagnóstico etiopatogénico y psicopatológico

===== Etiopatogenia

Los estudios a nivel biológico son escasos. En lo imagenológico footnote:[Vicens, V., Radua, J., Salvador, R., Anguera-Camos, M., Canales-Rodriguez, E. J., Sarro, S., ... & Pomarol-Clotet, E. (2016). Structural and functional brain changes in delusional disorder. The British Journal of Psychiatry, 208(2), 153-159.] se destaca:

- ↓ de la materia gris en la corteza medial frontal y cingulada anterior, así como en la ínsula a nivel bilateral.
- falla en la desactivación de la corteza medial frontal medial y cingulada anterior durante la realización de algunas tareas de desempeño continuo (test N-back, mide memoria de trabajo)
- ↓ de la conectividad de reposo en la ínsula a nivel bilateral.

===== Psicopatología

Se evocan causas fundamentalmente psicológicas. Kretschmer hizo hincapié en la predisposición psicológica de la personalidad premórbida de tipo paranoico/sensitivo-paranoico que está en nuestro paciente dada por... 

Psicoanálisis: comporta una fijación y regresión a estadios arcaicos del desarrollo psicosexual sobre todo a pulsiones agresivas del estado sádico-anal. Se utiliza el mecanismo de defensa psicótico de negación de la realidad y el mecanismo de proyección mediante el cual coloca en otro los sentimientos o ideas inaceptables para su yo. Los conflictos inconscientes se proyectan en el delirio. Freud insistió en el delirio de persecusión como una defensa contra pulsiones homosexuales inconscientes. Un yo relativamente fuerte permite mediante la represión una seudorracionalización que lleva a la elaboración de un sistema relativamente coherente. Lacan: sentido autopunitivo de la Paranoia, que encierra al sujeto en un sistema de persecución imaginaria que simbolizaría un castigo deseado inconscientemente. 

Jaspers: introduce el concepto de desarrollo: la paranoia es un fenómeno morboso que se produce sobre la personalidad del sujeto, cambiando su rumbo pero manteniendo su estructura, no existe quiebre vital, su vida es unitaria. Proceso evolutivo que altera el desarrollo normal de la personalidad. En la personalidad encontramos en la infancia: Un ambiente donde lo extraño es vivido como persecutorio, ambiente donde el paciente desarrolla su enfermedad, de fuerte contenido moral y religioso, con un padre rígido y autoritario como predisponente. Conjuntamente existen factores de estrés psicosocial que confrontan su rígida moral que percibidos como amenazantes actúan sobre un terreno psicológicamente predispuesto amenazando su: intimidad, problemática inconsciente, moralidad rígida.

==== Paraclínica

El diagnóstico es clínico.

BIOLOGICO

1. Lo que tenga
2. Valoración general
3. Con vistas al tratamiento (ECT de 2° elección únicamente)

PSICOLOGICO

Luego de superado el cuadro actual: Tests P y NP. SOCIAL • policía-juez (al que lo envía) • familia: jerarquizar si solo contamos con el relato del paciente (relato con "plausibilidad" obliga a corroborar datos con terceros). • HC anteriores, tratamiento y respuestas • nivel de funcionamiento sociolaboral • ajuste familiar premórbido y períodos intercríticos • valorar red de soporte social • inventario de eventos vitales y objetivar la reacción del paciente a ellos • informar sobre la eventualidad de realizar ECT en caso de pobre respuesta a la medicación. Despejaremos temores al respecto, explicando ventajas y efectos secundarios y obtendremos un consentimiento informado por escrito.

==== Tratamiento

Destinado a:

* compensar el cuadro actual
* actuar sobre enfermedad de fondo, evitando futuras descompensaciones, favoreciendo la adaptación social con reinserción laboral y correcta adopción de roles.

===== Cuadro actual

Internación o no según tipo y gravedad de descompensación. En orden de preferencia: ambulatorio -> internación con consentimiento -> internación compulsiva. Internaremos al paciente en Hospital Psiquiátrico en habitación aislada en lo posible de común acuerdo por lo que procuraremos obtener una relación cordial y de confianza. De no ser posible efectuaremos la internación compulsiva ya que existe peligro potencial (dado que se trata de perseguidos perseguidores) de hechos de implicancias ML por sus frecuentes reacciones heteroagresivas con lo que protegemos al paciente y a terceros. Vigilaremos fuga y heteroagresividad. Equipo multidisciplinario.

.Biológico
Según tipo y gravedad de descompensación: a) i/m o b) v/o.

a) Requiere medicación i/m Haloperidol: NL incisivo con acción sobre el delirio: 5 mg i/m H8 y H20. Como profilaxis de efectos EP (rigidez, rueda dentada, temblor, bradiquinesia) que se pueden ver con esta medicación indicaremos dada la suspicacia persecutoria del paciente, que puede perjudicar la adhesión al tratamiento, desde el inicio, un antiparkinsoniano de síntesis como el Biperideno a dosis de 2 mg v/o H8 y H14. Una vez establecida la dosis de Haloperidol, concentraremos en la noche ya que durante el sueño no aparecen estos efectos. (Si este es el primer episodio. Si ya estaba tomando antes, basarse en AP). Si en 3-4 días no notamos mejoría con aumento del monto delirante, agregaremos 5 mg i/m de Haloperidol H14 con lo que llegaremos a 15 mg/día. A medida que vaya retrocediendo el cuadro delirante y logremos la sedación y el restablecimiento del sueño, pasaremos la medicación a v/o. Sedación con Lorazepam i/m. Hipnótico: Flunitrazepam i/m.

b) Vía oral: se prefiere ya que no perjudica el vínculo. Antipsicótico: preferentemente un atípico: Risperidona: por tener menos efectos secundarios. !Ver pauta de inicio de Risperidona. Sedaremos con Benzodiacepinas: Lorazepam. Diazepam o Clonazepam a regular según evolución. Trataremos el insomnio con Flunitrazepam 2 mg v/o H20 a regular según la evolución.

NOTA: Conducta en caso de paranoico de tipo sensitivo deprimido: abstenerse de antidepresivos en lo posible ya que la depresión es secundaria al delirio. Si en 10-15 días no obtenemos mejoría ostensible con mantenimiento importante de falta de contacto con la realidad, indicaremos ECT a realizar por psiquiatra y anestesista, cada día por medio, con oxigenoterapia y monitoreo EEG y ECG, con barbitúricos de acción corta y curarizantes como la succinilcolina. La cantidad de sesiones la regularemos según la evolución, pero pensamos que serán necesarias entre 8-12 sesiones para lograr el efecto deseado. Vigilaremos al paciente luego de cada sesión sabiendo que pueden presentarse trastornos mnésicos transitorios y cefaleas.

.Psicosocial


Alta

Indicaremos el alta hospitalaria cuando haya disminuido considerablemente el monto delirante ya que sabemos que puede no retroceder totalmente. Controlaremos en policlínica semanalmente e iremos espaciando los controles según la evolución.

===== Tratamiento a largo plazo

El objetivo no es eliminar el delirio sino favorecer la adaptación social, que el paciente no viva en función de éste y favorecer su reintegro laboral.

.Biológico

Mantendremos en un principio la medicación a la misma dosis con que se obtuvo mejoría. Se trata de una enfermedad con bajo perfil de cumplimiento (a/v puede existir AP de abandono de la medicación) por lo que si bien preferimos la v/o que nos permite un mejor manejo de la dosis, recurriremos previo al alta a NLD como: • Palmitato de Pipotiazina 25-50 mg i/m que repetiremos c/21 días • Decanoato de Haloperidol 100-200 mg i/m a repetir una vez al mes La dosis se ajustará según la evolución. En este caso mantendremos la medicación antiparkinsoniana. A largo plazo valoraremos la posibilidad de disminuir la dosis buscando la mínima dosis eficaz. En un plazo de 3 meses, de no haber efectos extrapiramidales, puede disminuirse en forma gradual el antiparkinsoniano.

.Psicológico

Realizaremos entrevistas reiteradas para evaluar las conductas agresivas y evolución, afianzar el vínculo en un marco cálido con límites claros, evitando contradecirlo (y pasar a formar parte del complot) ya que se trata de un paciente extremadamente suspicaz y que realizará múltiples demandas. No realizaremos concesiones y no confrontaremos el núcleo delirante en las primeras entrevistas.

.Social

Realizaremos desde el inicio psicoeducación a la familia, explicando la enfermedad y el pronóstico, buscando su participación en el tratamiento, control de la medicación, concurrencia del paciente a policlínica y reconocimiento precoz de síntomas de descompensación. Eventual terapia familiar dada la distorsión que puede provocar el delirio del paciente en la dinámica familiar. Paciente: enfatizar reinserción social, minimizar interferencia del delirio con su desempeño.

==== Evolución y pronóstico

PPI y PVI: bueno con el tratamiento instituido. Está sujeto a complicaciones: IAE (sensitivo de relación), heteroagresividad (paranoico).

En el psiquiátrico alejado, es pobre por tratarse de una psicosis crónica, por la dificultad para lograr pese al tratamiento una remisión completa, por las frecuentes complicaciones ML en las que reivindicando sus derechos puede caer en actos heteroagresivos. Dependerá de la adhesión al tratamiento (basarse en medio familiar). Es una enfermedad crónica, no esperamos la extinción del delirio sino una disminución del monto delirante que permita una mejor inserción social. La evolución habitual es con oscilaciones en la intensidad del deliro, aunque pueden existir remisiones completas seguidas de recaídas. No existe evolución deficitaria intelectual, pero puede existir deterioro sociofamiliar y laboral generados por el delirio y sus eventuales conductas agresivas. Para los clásicos: eventualidad de evolución hacia otras formas de psicosis crónicas.

El PVA es bueno ya que no existen trastornos orgánicos, pero está sujeto al psiquiátrico.
